// Campañas (10 mapas cada una, uno tras otro) y Batalla de la semana (un mapa hecho a mano con reglas propias, que cambia cada lunes).
// Decisión del 6 sep 2026. Los premios son oro del héroe; los objetos corcel (mapa 8) y corona_rey (mapa 10) ya lo decían en objetos.js.
//
// 9 sep 2026: los diez mapas cuentan UNA historia seguida. El rey ha muerto sin heredero y su condestable,
// Alvar el Cuervo, se ha quedado la corona y la Torre del Rey. Empiezas siendo un señor de un feudo pequeño
// al que le han quitado el molino y acabas delante de él. Cada capítulo tiene:
//   `texto`    una línea de qué vas a jugar (la que se ve en la lista)
//   `historia` el diálogo que sale antes de empezar: dónde estás y por qué peleas
//   `voz`      quién habla en ese diálogo
//   `jefe`     solo el último: el rival principal es Alvar, con héroe de leyenda y más oro
// Los textos están escritos para que los entienda un niño de ocho años (Rodrigo, 9 sep): frases cortas,
// una idea por frase, y nada de palabras de castillo (vado, senescal, feudo…). Cada capítulo empieza
// recordando en qué punto estamos, para que la historia se siga aunque se juegue de semana en semana.
window.FWM = window.FWM || {};
FWM.datosBase = FWM.datosBase || {};

// Campañas (13 sep 2026): una por facción, de diez capítulos cada una, incluida con la facción. La de Castilla es
// la de siempre (Alvar el Cuervo). Las demás cuentan una historia de verdad de su cultura, contada para que la
// entienda un niño de ocho años y sin pelear por religiones: se pelea por tierras, coronas y venganzas.
// Cada capítulo: `enemigos` dice contra quién se juega (una facción o un reino de los de siempre con su nombre
// propio); `jefe`, solo en el último, es el malo final (héroe al nivel 10, más oro y nombre propio).
FWM.datosBase.campanas = {
  // ---------- Castilla: el chico del molino contra Alvar el Cuervo ----------
  castilla: {
    nombre: "El Cuervo", destino: "La Torre del Cuervo", paisaje: "castilla",
    pista: "Diez mapas hechos a mano, cada uno más difícil que el anterior. Cada mapa superado da su premio una sola vez.",
    capitulos: [
  { id: 1, nombre: "El molino del río", mapa: "hoz", rivales: 1, enemigos: [{ bando: "castilla", reino: "Los ladrones del río" }], dificultad: "facil", limite: 12, premio: { oro: 15 },
    voz: "Tu capitán",
    meta: "Cruza el río y acaba con los ladrones: quítales su pueblo y derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
    contra: "Los ladrones del río",
    consejo: "Antes de cruzar, recluta soldados en tu pueblo. Los campesinos trabajan bien, pero pelean mal.",
    historia: "El rey ha muerto y no ha dejado hijos, así que ahora no manda nadie. Anoche unos ladrones cruzaron el río, entraron en tu molino y se llevaron tu grano. Son pocos y tienen armas malas. Pero si nadie los para, volverán cada semana." },

  { id: 2, nombre: "Las minas de la costa", mapa: "costa", rivales: 1, batalla: "clave", objetivo: { tipo: "clave", n: 2, turnos: 2 }, enemigos: [{ bando: "portugal", reino: "El señor de las minas" }], dificultad: "normal", limite: 15, premio: { oro: 20 },
    voz: "Tu capitán",
    meta: "En el mapa hay cuatro atalayas, marcadas con una estrella. Pisa dos de ellas con tus soldados y consigue que sigan siendo tuyas durante dos turnos seguidos. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
    contra: "El señor de las minas",
    consejo: "El señor intentará quitarte las atalayas. Deja un soldado encima de cada una para defenderla.",
    historia: "Ya has echado a los ladrones. Pero hay un problema: tus soldados llevan dos meses sin cobrar. En la costa hay minas de oro. Un señor las vigila desde cuatro atalayas, que son torres para vigilar, pero tiene muy pocos soldados. Quien tenga dos atalayas manda en la costa. Y con el oro de la costa podrás pagar a tu ejército." },

  { id: 3, nombre: "Los tres juramentos", mapa: "torres", rivales: 2, equipos: [0, 1, 1], objetivo: { tipo: "tomar", jugador: 1 }, limite: 36, guion: [{ id: "leales_valle", cuando: { turno: 4 }, hacer: { refuerzos: { jugador: 0, tropas: ["lancero", "arquero", "catapulta", "catapulta"], donde: "2,9" }, aviso: "ayuda1" } }, { id: "leales_valle_2", cuando: { turno: 9 }, hacer: { refuerzos: { jugador: 0, tropas: ["caballero", "caballero", "catapulta"], donde: "3,9" }, aviso: "ayuda2" } }], enemigos: [{ bando: "aragon", reino: "Los Lara" }, { bando: "aragon", reino: "Los Haro" }], dificultad: "facil", premio: { oro: 25 },
    voz: "Tu capitán",
    meta: "Conquista el pueblo principal de los Lara. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
    contra: "Los Lara y los Haro, que van juntos",
    consejo: "Aguanta los primeros turnos: puede que pronto llegue alguien a ayudarte. Y recuerda que para entrar en un pueblo con muralla, antes hay que romperla.",
    avisos: { ayuda1: "Llega gente del valle a ayudarte, abajo del mapa, cerca de los Lara: un lancero, un arquero y dos catapultas. Las catapultas sirven para romper murallas.", ayuda2: "Llega más gente del valle, también abajo del mapa: dos caballeros y otra catapulta." },
    historia: "Con el oro de las minas ya puedes pagar a tus soldados. Pero hay malas noticias. En el valle viven otras dos familias, los Lara y los Haro. Juraron que te ayudarían a defenderlo, pero han roto su promesa y se han pasado al bando de Alvar el Cuervo. Alvar es el general que se quedó con la corona cuando murió el rey. Esta mañana, los Lara y los Haro han traído a sus soldados al centro del valle." },

  { id: 4, nombre: "El paso de la sierra", mapa: "sierra", rivales: 2, batalla: "asalto", ejercito: 12, guion: [{ id: "maquinas_paso", cuando: { turno: 5 }, hacer: { refuerzos: { jugador: 0, tropas: ["catapulta", "catapulta"], donde: "borde" }, aviso: "catapultas" } }], enemigos: [{ bando: "granada", reino: "Los guardias del camino del oeste" }, { bando: "granada", reino: "Los guardias del camino del este" }], dificultad: "normal", limite: 20, premio: { oro: 30 },
    voz: "Un pastor de las montañas",
    meta: "Aquí no tienes pueblo: solo tu ejército. Conquista el fuerte de los guardias del camino del oeste. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
    contra: "Los guardias de los dos caminos. Cada uno va por su cuenta",
    consejo: "Aquí no puedes reclutar soldados, así que cuida los que tienes. Sin catapultas es muy difícil romper una muralla.",
    avisos: { catapultas: "Unos pastores te suben dos catapultas por el monte. Sirven para romper la muralla del fuerte." },
    historia: "El valle ya es tuyo, señor, y ahora hay que seguir hacia el norte. Detrás de estas montañas empiezan las tierras del Cuervo. Solo hay dos caminos para cruzarlas, y sus guardias vigilan los dos. Subir es fácil, pero arriba te estarán esperando." },

  { id: 5, nombre: "Los puentes quemados", mapa: "costa", rivales: 2, guion: [{ id: "barcas_lago", cuando: { turno: 5 }, hacer: { refuerzos: { jugador: 0, tropas: ["espadachin", "arquero", "caballero"], donde: "capital" }, oro: { jugador: 0, cantidad: 40 }, aviso: "barcas" } }, { id: "refuerzos_lago", cuando: { turno: 9 }, hacer: { refuerzos: { jugador: 1, tropas: ["lancero", "arquero"], donde: "capital" }, aviso: "lago" } }], enemigos: [{ bando: "sacro_imperio", reino: "Señores del lago" }, { bando: "sacro_imperio", reino: "Los señores de la playa" }], dificultad: "normal", limite: 20, premio: { oro: 35 },
    voz: "Tu capitán",
    meta: "Acaba con los dos señores: quítales sus pueblos y derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
    contra: "Dos señores del lago, que no se ayudan entre sí",
    consejo: "Como no se ayudan, a veces se pelean entre ellos. Aprovéchalo: ataca al que esté más débil.",
    avisos: { barcas: "Llegan unas barcas con ayuda para ti: un espadachín, un arquero, un caballero y 20 monedas de oro.", lago: "Uno de los señores del lago recibe ayuda: un lancero y un arquero." },
    historia: "Ya hemos cruzado las montañas: estamos en la tierra del Cuervo. El Cuervo ha quemado los puentes del lago para que no podamos pasar, y hemos tenido que bajar hasta la costa. Además, ha prometido mil monedas de oro a quien te gane. Dos de sus señores nos esperan en la playa. Los dos quieren el premio para ellos solos, así que no se ayudan entre sí." },

  { id: 6, nombre: "Cofres vacíos", mapa: "hoz", rivales: 2, guion: [{ id: "ayuda_rey", cuando: { turno: 7 }, hacer: { refuerzos: { jugador: 0, tropas: ["lancero", "arquero"], donde: "capital" }, oro: { jugador: 0, cantidad: 20 }, aviso: "amigo" } }, { id: "gente_del_rio", cuando: { turno: 11 }, hacer: { refuerzos: { equipo: 1, tropas: ["espadachin", "arquero"], donde: "capital" }, aviso: "rio" } }], enemigos: [{ bando: "francia", reino: "Los del otro río" }, { bando: "francia", reino: "Los del puente" }], dificultad: "dificil", limite: 15, hucha: 1, premio: { oro: 40 },
    voz: "Tu capitán",
    meta: "Acaba con los dos señores: quítales sus pueblos y derrota a todos sus soldados. Empiezas con la mitad del oro de siempre. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
    contra: "Dos señores del otro río",
    consejo: "Con poco oro, no lo malgastes. Defiéndete bien al principio: puede que alguien venga a ayudarte.",
    avisos: { amigo: "Un amigo del rey muerto te manda ayuda: un lancero, un arquero y 20 monedas de oro.", rio: "Uno de los señores del otro río recibe ayuda: un espadachín y un arquero." },
    historia: "Estamos lejos de casa, en tierra enemiga. Y esta noche ha pasado algo malo: el hombre que guardaba tu dinero se ha escapado con la mitad. Dicen que se ha ido con el Cuervo. Delante tenemos otro río, y al otro lado nos esperan dos señores del Cuervo." },

  { id: 7, nombre: "El cerco", mapa: "torres", rivales: 3, equipos: [0, 1, 1, 1], objetivo: { tipo: "aguantar", equipo: 0, turnos: 14 }, guion: [{ id: "cerco", repetible: true, cuando: { cadaTurnos: 2, desde: 3 }, hacer: { refuerzos: { equipo: 1, tropas: ["lancero", "espadachin", "catapulta", "caballero"], donde: "borde" }, aviso: "cerco" } }], enemigos: [{ bando: "escocia", reino: "Los señores de las torres" }, { bando: "escocia", reino: "Los guardias de las torres" }, { bando: "escocia", reino: "Los jinetes de las torres" }], dificultad: "dificil", limite: 14, premio: { oro: 50 },
    voz: "Tu capitán",
    meta: "Aguanta {t} turnos sin que acaben contigo. Mientras te quede un pueblo o un soldado, sigues en pie. Si al acabar el turno {t} sigues en pie, ganas.",
    contra: "Los tres señores de las torres, que van juntos",
    consejo: "No hace falta ganarles, solo aguantar. Mete soldados dentro de tus pueblos y no te alejes de ellos.",
    avisos: { cerco: "¡Llegan más soldados enemigos, con una catapulta para romper tus murallas!" },
    historia: "El Cuervo ha mandado a sus mejores señores a por ti. Tres de ellos te han rodeado con sus torres. Te quieren encerrar como a un ratón en una caja." },

  { id: 8, nombre: "La carga", mapa: "costa", rivales: 3, batalla: "campo", ejercito: { yo: 16, rival: 4 }, equipos: [0, 1, 1, 1], enemigos: [{ bando: "hungria", reino: "Los jinetes del Cuervo" }, { bando: "francia", reino: "Los del Cuervo" }, { bando: "francia", reino: "Los lanceros del Cuervo" }], dificultad: "dificil", limite: 15, premio: { oro: 50, objeto: "corcel" },
    voz: "Tu jefe de caballería",
    meta: "Aquí no hay pueblos: solo tu ejército contra el suyo. Derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
    contra: "Tres grupos de soldados del Cuervo, que van juntos",
    consejo: "Tienes más soldados que ellos. Ataca a cada enemigo con varios soldados a la vez.",
    historia: "Hemos escapado del cerco, señor. Ahora somos nosotros los que los perseguimos. Aquí no hay ríos ni torres para esconderse: es campo abierto, entre el mar y las montañas. Eso es bueno para los caballos. Déjame salir el primero y verás cómo corren." },

  { id: 9, nombre: "Sierra de hierro", mapa: "sierra", rivales: 3, objetivo: { tipo: "escapar", equipo: 0, lado: "sur" }, guion: [{ id: "persecucion", repetible: true, cuando: { cadaTurnos: 4, desde: 4 }, hacer: { refuerzos: { equipo: 1, tropas: ["caballero", "caballero"], donde: "borde" }, aviso: "caballeros" } }], enemigos: [{ bando: "sacro_imperio", reino: "Los amigos del Cuervo" }, { bando: "sacro_imperio", reino: "Los guardias de la sierra" }, { bando: "sacro_imperio", reino: "Los vigías de la sierra" }], dificultad: "dificil", limite: 16, premio: { oro: 60 },
    voz: "Tu capitán",
    meta: "Lleva a tu héroe hasta el borde de abajo del mapa: a una de las casillas con bandera 🚩. Tienes {t} turnos. Si se acaban y tu héroe no ha salido, pierdes. Y si matan a tu héroe, ya no podrá salir y perderás.",
    contra: "Tres grupos de amigos del Cuervo. Cada uno va por su cuenta",
    consejo: "No hace falta ganar a nadie: solo que tu héroe llegue abajo. Que tus soldados le abran el camino y lo protejan.",
    avisos: { caballeros: "¡Llegan dos caballeros enemigos más a buscarte!" },
    historia: "Estas montañas son lo último que hay entre nosotros y la Torre del Cuervo. El Cuervo ha llamado a sus amigos para que vigilen los caminos. Solo tienen que aguantar dieciséis días: después llegará la nieve y nadie podrá cruzar hasta la primavera." },

  { id: 10, nombre: "La Torre del Cuervo", mapa: "torres", rivales: 2, batalla: "asalto", ejercito: 18, equipos: [0, 1, 1], guion: [{ id: "leales_1", cuando: { turno: 5 }, hacer: { refuerzos: { jugador: 0, tropas: ["espadachin", "arquero", "lancero"], donde: "borde" }, aviso: "leales" } }, { id: "leales_2", cuando: { turno: 7 }, hacer: { refuerzos: { jugador: 0, tropas: ["caballero", "catapulta", "catapulta"], donde: "borde" }, aviso: "maquinas" } }], enemigos: [{ bando: "noruega", capital: "La Torre del Cuervo" }, { bando: "francia", reino: "Los amigos del Cuervo" }], dificultad: "dificil", limite: 29, premio: { oro: 100, objeto: "corona_rey" },
    voz: "Alvar el Cuervo",
    // el rival 1 es el jefe: héroe de leyenda, más oro y nombre propio
    jefe: { apodo: "Alvar el Cuervo", reino: "Alvar el Cuervo", clase: "nordico", nivel: 10, oro: 1.7, color: "#3a3340" },
    meta: "Aquí no tienes pueblo: solo tu ejército. Conquista la torre de Alvar, que es su pueblo principal. Tienes {t} turnos. Si se acaban y no la has conquistado, pierdes.",
    contra: "Alvar el Cuervo y sus amigos, que van juntos",
    consejo: "Es la última batalla. Alvar es muy fuerte: no le ataques con un soldado solo.",
    avisos: { leales: "Llega gente que quiere que ganes tú: un espadachín, un arquero y un lancero.", maquinas: "Llegan más amigos: un caballero y dos catapultas para romper la muralla de la torre." },
    historia: "«Vaya, el chico del molino. Has llegado más lejos de lo que nadie esperaba.» Alvar te habla tranquilo desde lo alto de su muralla. «Yo no maté al rey. La corona estaba en el suelo y la cogí, nada más. Sube a por ella si te atreves. Aquí te espero, con todos mis soldados.»" },
] },

  // ---------- Vikingos: la saga de Harald Hardrada (1030-1066) ----------
  vikingos: {
    nombre: "La saga de Harald", destino: "El puente de Stamford", paisaje: "norte",
    pista: "De chico que huye de una batalla perdida a rey de Noruega… y un último viaje a Inglaterra. Diez capítulos, uno detrás de otro.",
    capitulos: [
      { id: 1, nombre: "La huida", mapa: "estepa", rivales: 1, batalla: "campo", ejercito: { yo: 5, rival: 3 }, objetivo: { tipo: "escapar", equipo: 0, lado: "oeste" }, guion: [{ id: "jinetes_knut", repetible: true, cuando: { cadaTurnos: 4, desde: 4 }, hacer: { refuerzos: { equipo: 1, tropas: ["caballero"], donde: "borde" }, aviso: "jinetes" } }], enemigos: [{ bando: "noruega", reino: "Los hombres de Knut" }], dificultad: "facil", limite: 15, premio: { oro: 15 },
        voz: "Rognvald, tu amigo",
        meta: "Lleva a tu héroe a una de las casillas con bandera 🚩, abajo a la izquierda: allí está el barco. Tienes {t} turnos. Si se acaban y no ha salido, pierdes. Y si matan a tu héroe, también.",
        contra: "Los hombres de Knut",
        consejo: "No hace falta ganar a nadie. Que tus soldados se pongan delante de tu héroe y le abran el camino.",
        avisos: { jinetes: "¡Más jinetes de Knut vienen a buscarte!" },
        historia: "Tu hermano, el rey Olaf, ha muerto en la batalla. Tú solo tienes quince años y estás herido. Knut, el rey que ha ganado, manda a sus hombres a buscarte por los bosques. Al otro lado de estas tierras hay un barco esperándonos. Si llegamos, podremos huir lejos." },
      { id: 2, nombre: "La guardia del emperador", mapa: "costa", rivales: 1, batalla: "clave", objetivo: { tipo: "clave", n: 2, turnos: 2 }, enemigos: [{ bando: "venecia", reino: "Los piratas del estrecho" }], dificultad: "normal", limite: 12, premio: { oro: 20 },
        voz: "El capitán de la guardia",
        meta: "En el mapa hay torres marcadas con una estrella. Pisa dos de ellas con tus soldados y consigue que sigan siendo tuyas durante dos turnos seguidos. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los piratas del estrecho",
        consejo: "Los piratas intentarán recuperar las torres. Deja un soldado encima de cada una.",
        historia: "Has cruzado el mar hasta Constantinopla, la ciudad más grande del mundo. Su emperador paga en oro a los guerreros del norte que le protegen: su guardia. Pero aquí nadie te conoce. Unos piratas se han quedado con las torres del puerto. Si se las quitas, entrarás en la guardia." },
      { id: 3, nombre: "La isla de los castillos", mapa: "isla", rivales: 2, batalla: "asalto", ejercito: 12, guion: [{ id: "barcos_emperador", cuando: { turno: 3 }, hacer: { refuerzos: { jugador: 0, tropas: ["catapulta", "catapulta"], donde: "borde" }, aviso: "catapultas" } }], enemigos: [{ bando: "abasi", reino: "Los señores de la isla" }, { bando: "abasi", reino: "Los señores del puerto" }], dificultad: "normal", limite: 28, premio: { oro: 25 },
        voz: "El capitán de la guardia",
        meta: "Aquí no tienes pueblo: solo tu ejército, que llega en barco. Conquista el castillo de los señores de la isla, que es su pueblo principal. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "Los señores de la isla y los del puerto. Cada uno va por su cuenta",
        consejo: "Aquí no puedes reclutar soldados, así que cuídalos. Sin catapultas cuesta mucho romper una muralla.",
        avisos: { catapultas: "Llegan más barcos del emperador con dos catapultas. Sirven para romper murallas." },
        historia: "Ya eres de la guardia del emperador. Ahora te manda a Sicilia, una isla del sur llena de castillos. Si tomas el castillo más grande, podrás quedarte con una parte del tesoro. Por primera vez vas a mandar a tus propios hombres." },
      { id: 4, nombre: "El tesoro escondido", mapa: "sierra", rivales: 2, equipos: [0, 1, 1], objetivo: { tipo: "aguantar", equipo: 0, turnos: 14, capital: true }, guion: [{ id: "soldados_emperador", repetible: true, cuando: { cadaTurnos: 2, desde: 3 }, hacer: { refuerzos: { equipo: 1, tropas: ["lancero", "espadachin", "catapulta", "caballero"], donde: "borde" }, aviso: "soldados" } }], enemigos: [{ bando: "bizancio", reino: "Los soldados del emperador" }, { bando: "bizancio", reino: "La guardia del palacio" }], dificultad: "normal", limite: 14, premio: { oro: 30 },
        voz: "Rognvald, tu amigo",
        meta: "Defiende tu pueblo principal (el de la estrella) durante {t} turnos, hasta que llegue el barco. Si te lo quitan, pierdes. Si al acabar el turno {t} sigue siendo tuyo, ganas.",
        contra: "Los soldados del emperador y la guardia del palacio, que van juntos",
        consejo: "Llena tu pueblo principal de soldados y ponle murallas. Los demás pueblos no importan tanto.",
        avisos: { soldados: "¡El emperador manda más soldados a buscar su oro, con una catapulta para romper tus murallas!" },
        historia: "Has ganado mucho oro en Sicilia, y ahora el emperador lo quiere para él. Dice que es suyo. Hemos escondido el tesoro en las montañas y hemos mandado a buscar un barco. Hasta que llegue, tenemos que aguantar aquí." },
      { id: 5, nombre: "El príncipe del este", mapa: "hoz", rivales: 2, equipos: [0, 1, 1], guion: [{ id: "ayuda_elisiv", cuando: { turno: 4 }, hacer: { refuerzos: { jugador: 0, tropas: ["caballero", "caballero", "lancero"], donde: "capital" }, aviso: "ayuda" } }, { id: "ayuda_elisiv2", cuando: { turno: 8 }, hacer: { refuerzos: { jugador: 0, tropas: ["espadachin", "arquero", "caballero"], donde: "capital" }, aviso: "ayuda2" } }], enemigos: [{ bando: "polonia", reino: "Los bandidos del río" }, { bando: "polonia", reino: "Los bandidos del bosque" }], dificultad: "normal", limite: 18, premio: { oro: 35 },
        voz: "Elisiv, la hija del príncipe",
        meta: "Acaba con los dos grupos de bandidos: quítales sus pueblos y derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los bandidos del río y los del bosque, que van juntos",
        consejo: "Van juntos: no dejes tus pueblos vacíos. Aguanta los primeros turnos: el príncipe puede ayudarte.",
        avisos: { ayuda: "Elisiv convence a su padre, y el príncipe te manda dos caballeros y un lancero.", ayuda2: "El príncipe te manda más gente: un espadachín, un arquero y un caballero." },
        historia: "Con el oro a salvo has llegado a Kiev, la tierra del gran príncipe del este. Yo soy su hija, Elisiv. Mi padre dice que me casaré contigo si echas a los bandidos que roban en los caminos. Yo ya he dicho que sí." },
      { id: 6, nombre: "Vuelta a casa", mapa: "torres", rivales: 2, equipos: [0, 1, 0], objetivo: { tipo: "tomar", jugador: 1 }, guion: [{ id: "barco", cuando: { turno: 4 }, hacer: { refuerzos: { jugador: 0, tropas: ["lancero", "espadachin", "catapulta", "catapulta"], donde: "2,9" }, aviso: "barco" } }, { id: "barco2", cuando: { turno: 9 }, hacer: { refuerzos: { jugador: 0, tropas: ["caballero", "caballero", "catapulta"], donde: "3,9" }, aviso: "barco2" } }, { id: "magnus_traiciona", cuando: { turno: 7 }, hacer: { equipo: { jugador: 2, nuevo: 1 }, aviso: "traicion" } }], enemigos: [{ bando: "noruega", reino: "Los jefes del fiordo" }, { bando: "noruega", reino: "Magnus, tu sobrino" }], dificultad: "normal", limite: 34, premio: { oro: 40 },
        voz: "Elisiv, tu esposa",
        meta: "Conquista el pueblo principal de los jefes del fiordo. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "Los jefes del fiordo. Magnus, tu sobrino, empieza de tu lado",
        consejo: "No dejes tus pueblos vacíos. Una corona es difícil de compartir.",
        avisos: { traicion: "¡Magnus no quiere compartir la corona! Se pasa al lado de los jefes del fiordo. Ahora es tu enemigo.", barco: "Tus hombres de confianza llegan en barco, cerca del pueblo de los jefes: un lancero, un espadachín y dos catapultas para romper murallas.", barco2: "Llega otro barco con dos caballeros y otra catapulta, también cerca del pueblo de los jefes." },
        historia: "Volvemos a Noruega con un barco lleno de oro. Ahora el rey es tu sobrino Magnus. Dice que compartirá la corona contigo y que te ayudará contra los jefes del fiordo, que no te quieren aquí. Ojalá sea verdad." },
      { id: 7, nombre: "El rey de Dinamarca", mapa: "costa", rivales: 3, batalla: "campo", ejercito: { yo: 18, rival: 5 }, equipos: [0, 1, 1, 1], enemigos: [{ bando: "noruega", reino: "Los barcos de Svein" }, { bando: "noruega", reino: "Los guerreros de Svein" }, { bando: "noruega", reino: "Los jinetes de Svein" }], dificultad: "dificil", limite: 15, premio: { oro: 50 },
        voz: "Rognvald, tu amigo",
        meta: "Aquí no hay pueblos: solo tu ejército contra el suyo. Derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Tres grupos de barcos de Svein, que van juntos",
        consejo: "Tienes más soldados que cada uno de sus grupos. Júntalos y ataca a cada enemigo con varios a la vez.",
        historia: "Magnus ha muerto y ahora eres el único rey de Noruega. Pero Svein, el rey de Dinamarca, quiere tus tierras, y sus barcos han llegado a nuestras islas. Ellos pelean como nosotros: esto va a ser duro." },
      { id: 8, nombre: "Las islas del norte", mapa: "isla", rivales: 3, equipos: [0, 1, 1, 1], guion: [{ id: "conde_orcadas", cuando: { turno: 4 }, hacer: { equipo: { jugador: 3, nuevo: 0 }, aviso: "conde" } }], enemigos: [{ bando: "escocia", reino: "Los señores de las islas" }, { bando: "escocia", reino: "Los señores del cabo" }, { bando: "escocia", reino: "El conde de las Orcadas" }], dificultad: "dificil", limite: 18, premio: { oro: 50, objeto: "capa_lobo" },
        voz: "Un mensajero inglés",
        meta: "Acaba con los señores de las islas: quítales sus pueblos y derrota a sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los señores de las islas, los del cabo y el conde de las Orcadas, que de momento van juntos",
        consejo: "No todos quieren pelear contigo para siempre. Aguanta sin perder tus pueblos.",
        avisos: { conde: "El conde de las Orcadas decide que prefiere ser tu amigo. Ahora está de tu lado." },
        historia: "Traigo noticias de Inglaterra, señor: nuestro rey ha muerto sin hijos. Muchos dicen que la corona podría ser vuestra. Pero para cruzar el mar con un ejército necesitáis antes las islas del norte, y sus señores no quieren dueño." },
      { id: 9, nombre: "Fulford", mapa: "costa", rivales: 2, batalla: "campo", ejercito: { yo: 16, rival: 6 }, equipos: [0, 1, 1], objetivo: { tipo: "heroe" }, guion: [{ id: "avanzadilla", cuando: { turno: 9 }, hacer: { refuerzos: { equipo: 1, tropas: ["caballero", "caballero", "arquero"], donde: "borde" }, aviso: "avanzadilla" } }], enemigos: [{ faccion: "inglaterra", reino: "El conde Edwin" }, { faccion: "inglaterra", reino: "El conde Morcar" }], dificultad: "dificil", limite: 14, premio: { oro: 60 },
        voz: "Rognvald, tu amigo",
        meta: "Aquí no hay pueblos: solo los ejércitos. Mata a los héroes de los dos condes y que el tuyo siga vivo. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "El conde Edwin y el conde Morcar, que van juntos",
        consejo: "Cuidado con tu héroe: si lo matan a él, pierdes. Ataca a sus héroes con varios soldados a la vez.",
        avisos: { avanzadilla: "¡Llegan los primeros jinetes del rey inglés! El rey no puede estar lejos." },
        historia: "Hemos llegado a Inglaterra con trescientos barcos. Dos condes, Edwin y Morcar, nos esperan con sus hombres junto a un río, cerca de la ciudad de York. Si los vencemos rápido, la ciudad nos abrirá sus puertas antes de que llegue el rey inglés con su ejército." },
      { id: 10, nombre: "El puente de Stamford", mapa: "torres", rivales: 2, batalla: "asalto", ejercito: 18, equipos: [0, 1, 1], guion: [{ id: "eystein", cuando: { turno: 6 }, hacer: { refuerzos: { jugador: 0, tropas: ["espadachin", "espadachin", "arquero", "caballero"], donde: "borde" }, aviso: "eystein" } }, { id: "maquinas_fiordo", cuando: { turno: 9 }, hacer: { refuerzos: { jugador: 0, tropas: ["caballero", "catapulta", "catapulta"], donde: "borde" }, aviso: "maquinas" } }], enemigos: [{ bando: "inglaterra", capital: "York" }, { bando: "inglaterra", reino: "Los sajones" }], dificultad: "dificil", limite: 32, premio: { oro: 100, objeto: "estandarte_dragon" },
        voz: "Harold, rey de Inglaterra",
        meta: "Aquí no tienes pueblo: solo tu ejército, que ha llegado en barco. Conquista el pueblo principal del rey Harold. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "Harold, rey de Inglaterra, y los sajones, que van juntos",
        consejo: "Es la última batalla. Harold es muy fuerte: no le ataques con un soldado solo.",
        avisos: { eystein: "Llega Eystein con los hombres que se quedaron guardando los barcos: dos espadachines, un arquero y un caballero.", maquinas: "Llegan los últimos barcos: un caballero y dos catapultas para romper la muralla de Harold." },
        jefe: { apodo: "Harold, rey de Inglaterra", reino: "El rey Harold", faccion: "inglaterra", nivel: 10, oro: 1.7, color: "#7a2230" },
        historia: "«Harald de Noruega. Has venido a por mi reino. Te daré un trozo de Inglaterra: dos metros de tierra, lo que ocupa un hombre tumbado.» Harold, el rey inglés, te habla desde el otro lado del puente. «Mi ejército ha corrido día y noche para llegar. Te estamos esperando.»" },
    ] },

  // ---------- Inglaterra: el príncipe Eduardo contra el conde rebelde (1264-1265) ----------
  inglaterra: {
    nombre: "El príncipe Eduardo", destino: "Evesham", paisaje: "verde",
    pista: "Un príncipe prisionero, un conde que se ha quedado con el reino y un año para darle la vuelta. Diez capítulos, uno detrás de otro.",
    capitulos: [
      { id: 1, nombre: "El príncipe preso", mapa: "costa", rivales: 1, batalla: "campo", ejercito: { yo: 5, rival: 4 }, enemigos: [{ bando: "inglaterra", reino: "Los guardias del conde" }], dificultad: "facil", limite: 12, premio: { oro: 15 },
        voz: "Tu amigo Tomás",
        meta: "Aquí no hay pueblos: solo tus amigos contra los guardias. Derrota a todos los guardias del conde. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los guardias del conde Simón",
        consejo: "Ataca a cada guardia con dos o tres soldados a la vez: así caen antes.",
        historia: "Tu padre, el rey de Inglaterra, perdió una batalla contra el conde Simón. Desde entonces el conde os tiene presos a los dos y manda él en el reino. Hoy los guardias te dejan salir a montar a caballo. Tus amigos te esperan fuera. Es ahora o nunca." },
      { id: 2, nombre: "La carrera de caballos", mapa: "sierra", rivales: 1, batalla: "campo", ejercito: { yo: 5, rival: 5 }, objetivo: { tipo: "escapar", equipo: 0, lado: "oeste" }, guion: [{ id: "persecucion", repetible: true, cuando: { cadaTurnos: 4, desde: 4 }, hacer: { refuerzos: { equipo: 1, tropas: ["caballero"], donde: "borde" }, aviso: "jinetes" } }], enemigos: [{ bando: "inglaterra", reino: "Los jinetes del conde" }], dificultad: "normal", limite: 14, premio: { oro: 20 },
        voz: "Roger Mortimer, un señor amigo",
        meta: "Lleva a tu héroe a una de las casillas con bandera 🚩, abajo a la izquierda: allí empiezan las tierras de Mortimer. Tienes {t} turnos. Si se acaban y no ha salido, pierdes. Y si matan a tu héroe, también.",
        contra: "Los jinetes del conde",
        consejo: "No hace falta ganar a nadie. Que tus soldados frenen a los jinetes mientras tu héroe avanza.",
        avisos: { jinetes: "¡Más jinetes del conde se unen a la persecución!" },
        historia: "¡Muy listo, príncipe! Hiciste carreras con los caballos de tus guardias hasta cansarlos, y te escapaste en el único que estaba fresco. Ahora te persiguen. Cruza las montañas hasta mis tierras y aquí estarás a salvo." },
      { id: 3, nombre: "Los señores de la frontera", mapa: "torres", rivales: 2, equipos: [0, 1, 1], guion: [{ id: "frontera", cuando: { turno: 4 }, hacer: { refuerzos: { jugador: 0, tropas: ["lancero", "arquero", "caballero", "caballero", "espadachin"], donde: "capital" }, aviso: "frontera" } }, { id: "frontera2", cuando: { turno: 8 }, hacer: { refuerzos: { jugador: 0, tropas: ["espadachin", "arquero", "caballero"], donde: "capital" }, aviso: "frontera2" } }], enemigos: [{ bando: "escocia", reino: "Los barones del valle" }, { bando: "escocia", reino: "Los barones del río" }], dificultad: "facil", limite: 18, premio: { oro: 25 },
        voz: "Roger Mortimer",
        meta: "Acaba con los barones: quítales sus pueblos y derrota a sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los barones del valle y los del río, que van juntos",
        consejo: "Aguanta los primeros turnos sin perder tus pueblos: si te ven fuerte, puede que alguien se anime a ayudarte.",
        avisos: { frontera: "Los señores de la frontera han visto cómo peleas y te mandan soldados: un lancero, un arquero, un espadachín y dos caballeros.", frontera2: "Llegan más señores de la frontera: un espadachín, un arquero y un caballero." },
        historia: "Estás a salvo en mis tierras, pero un príncipe sin ejército no asusta a nadie. Los señores de la frontera todavía no se fían de ti. Echa a los barones del conde que hay en el valle, y verán de qué eres capaz." },
      { id: 4, nombre: "Los puentes del Severn", mapa: "hoz", rivales: 2, batalla: "clave", objetivo: { tipo: "clave", n: 2, turnos: 3 }, enemigos: [{ bando: "escocia", reino: "Los galeses del conde" }, { bando: "inglaterra", reino: "Los barones rebeldes" }], dificultad: "normal", limite: 16, premio: { oro: 30 },
        voz: "Roger Mortimer",
        meta: "Los dos sitios para cruzar el río están marcados con una estrella. Pisa los dos con tus soldados y consigue que sigan siendo tuyos durante tres turnos seguidos. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los galeses del conde y los barones rebeldes. Cada uno va por su cuenta",
        consejo: "Necesitas los dos a la vez. Deja soldados fuertes encima de cada uno.",
        historia: "Ya tienes ejército. El conde Simón está al otro lado del Severn, un río muy grande, y los galeses le ayudan. Solo hay dos sitios para cruzar el río. Si los cerramos, el conde se quedará encerrado lejos de Londres y de sus amigos." },
      { id: 5, nombre: "Gloucester", mapa: "marca", rivales: 2, batalla: "asalto", ejercito: 12, guion: [{ id: "maquinas_gilbert", cuando: { turno: 5 }, hacer: { refuerzos: { jugador: 0, tropas: ["catapulta", "catapulta"], donde: "borde" }, aviso: "catapultas" } }], enemigos: [{ bando: "inglaterra", reino: "Los hombres del conde", capital: "Gloucester" }, { bando: "inglaterra", reino: "Los barones rebeldes" }], dificultad: "normal", limite: 16, premio: { oro: 35 },
        voz: "Gilbert de Clare, un conde",
        meta: "Aquí no tienes pueblo: solo tu ejército. Conquista Gloucester, la ciudad que tienen los hombres del conde. Tienes {t} turnos. Si se acaban y no la has conquistado, pierdes.",
        contra: "Los hombres del conde y los barones rebeldes. Cada uno va por su cuenta",
        consejo: "Aquí no puedes reclutar soldados, así que cuídalos. Sin catapultas cuesta mucho romper una muralla.",
        avisos: { catapultas: "Gilbert te manda dos catapultas desde sus tierras. Sirven para romper murallas." },
        historia: "Antes estaba con Simón, pero me he cansado de sus órdenes, y ahora estoy contigo, príncipe. Mi ciudad, Gloucester, la tienen todavía los hombres del conde. Tiene buenas murallas: habrá que romperlas." },
      { id: 6, nombre: "Kenilworth", mapa: "isla", rivales: 2, batalla: "campo", ejercito: { yo: 14, rival: 3 }, equipos: [0, 1, 1], objetivo: { tipo: "heroe" }, guion: [{ id: "despiertan", repetible: true, cuando: { cadaTurnos: 3, desde: 3 }, hacer: { refuerzos: { equipo: 1, tropas: ["caballero", "espadachin"], donde: "borde" }, aviso: "despiertan" } }], enemigos: [{ bando: "francia", reino: "El joven Simón" }, { bando: "francia", reino: "Los caballeros del joven Simón" }], dificultad: "dificil", limite: 12, premio: { oro: 40 },
        voz: "Gilbert de Clare",
        meta: "Mata a los héroes de los dos jefes enemigos y que el tuyo siga vivo. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "El joven Simón y sus caballeros, que van juntos",
        consejo: "Date prisa: cuanto más tardes, más enemigos se despiertan. Cuida a tu héroe: si lo matan, pierdes.",
        avisos: { despiertan: "¡Se despiertan más caballeros del joven Simón y vienen a pelear!" },
        historia: "El hijo del conde, que también se llama Simón, viene a ayudar a su padre con otro ejército. Han llegado cansados y duermen fuera del castillo de Kenilworth, junto al lago. Si atacamos de madrugada, antes de que se despierten todos, no llegarán a ayudar a su padre." },
      { id: 7, nombre: "Las colinas de Gales", mapa: "sierra", rivales: 3, equipos: [0, 1, 1, 1], objetivo: { tipo: "aguantar", equipo: 0, turnos: 16, capital: true }, guion: [{ id: "galeses", repetible: true, cuando: { cadaTurnos: 2, desde: 4 }, hacer: { refuerzos: { equipo: 1, tropas: ["arquero", "espadachin", "catapulta", "caballero"], donde: "borde" }, aviso: "galeses" } }], enemigos: [{ bando: "escocia", reino: "Los galeses de Llywelyn" }, { bando: "escocia", reino: "Los arqueros galeses" }, { bando: "escocia", reino: "Los galeses de las colinas" }], dificultad: "dificil", limite: 16, premio: { oro: 50 },
        voz: "Gilbert de Clare",
        meta: "Defiende tu pueblo principal (el de la estrella) durante {t} turnos, hasta que llegue tu ejército. Si te lo quitan, pierdes. Si al acabar el turno {t} sigue siendo tuyo, ganas.",
        contra: "Tres grupos de galeses de Llywelyn, que van juntos",
        consejo: "Llena tu pueblo principal de soldados y ponle murallas. Los demás pueblos no importan tanto.",
        avisos: { galeses: "¡Bajan más galeses de las colinas, con una catapulta para romper tus murallas!" },
        historia: "Llywelyn, el príncipe de Gales, manda a sus arqueros a ayudar al conde. Nacieron en estas colinas y conocen cada camino. Nos han rodeado. Nuestro ejército viene de camino: hay que aguantar hasta que llegue." },
      { id: 8, nombre: "Los arqueros del rey", mapa: "costa", rivales: 3, batalla: "campo", ejercito: { yo: 15, rival: 4 }, equipos: [0, 1, 1, 1], enemigos: [{ bando: "francia", reino: "Los caballeros del conde" }, { bando: "inglaterra", reino: "Los barones rebeldes" }, { bando: "inglaterra", reino: "Los barones del sur" }], dificultad: "dificil", limite: 15, premio: { oro: 50, objeto: "capa_arquero" },
        voz: "Gilbert de Clare",
        meta: "Aquí no hay pueblos: solo tu ejército contra el suyo. Derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los caballeros del conde y dos grupos de barones, que van juntos",
        consejo: "Pon lanceros delante y arqueros detrás: los caballos no quieren chocar contra las lanzas.",
        historia: "Has aprendido algo de los galeses, príncipe: sus arcos largos llegan más lejos que cualquier cosa. Ahora tú también tienes arqueros así. El conde manda a sus caballeros contra nosotros en campo abierto. Pon a los arqueros detrás de las lanzas." },
      { id: 9, nombre: "El paso del Avon", mapa: "marca", rivales: 2, equipos: [0, 1, 1], objetivo: { tipo: "tomar", jugador: 1 }, guion: [{ id: "mortimer_paso", cuando: { turno: 4 }, hacer: { refuerzos: { jugador: 0, tropas: ["lancero", "arquero", "catapulta", "catapulta", "catapulta"], donde: "objetivo" }, aviso: "mortimer" } }, { id: "mortimer2", cuando: { turno: 9 }, hacer: { refuerzos: { jugador: 0, tropas: ["caballero", "caballero", "catapulta"], donde: "objetivo" }, aviso: "mortimer2" } }], enemigos: [{ bando: "inglaterra", reino: "Los barones del paso" }, { bando: "inglaterra", reino: "Los barones rebeldes" }], dificultad: "normal", limite: 30, premio: { oro: 60 },
        voz: "Roger Mortimer",
        meta: "Conquista el pueblo de los barones del paso, que es su pueblo principal. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "Los barones del paso y los barones rebeldes, que van juntos",
        consejo: "No hace falta acabar con todos: solo con ese pueblo. Lleva catapultas si tiene muralla.",
        avisos: { mortimer: "Mortimer te manda soldados y tres catapultas. Llegan cerca del paso, listos para romper su muralla.", mortimer2: "Mortimer manda más ayuda cerca del paso: dos caballeros y otra catapulta." },
        historia: "El conde Simón escapa hacia el sur para juntarse con su hijo. No sabe que su hijo ya no tiene ejército. Solo le queda un camino, y pasa por el pueblo que guarda el paso del río Avon. Si lo tomamos antes que él, lo tendremos atrapado." },
      { id: 10, nombre: "Evesham", mapa: "marca", rivales: 2, batalla: "asalto", ejercito: 18, equipos: [0, 1, 1], guion: [{ id: "mortimer", cuando: { turno: 7 }, hacer: { refuerzos: { jugador: 0, tropas: ["caballero", "caballero", "arquero_largo"], donde: "borde" }, aviso: "mortimer" } }, { id: "maquinas_gilbert", cuando: { turno: 9 }, hacer: { refuerzos: { jugador: 0, tropas: ["caballero", "catapulta", "catapulta"], donde: "borde" }, aviso: "maquinas" } }], enemigos: [{ bando: "francia", capital: "Evesham" }, { bando: "inglaterra", reino: "Los barones rebeldes" }], dificultad: "dificil", limite: 30, premio: { oro: 100, objeto: "capa_leones" },
        voz: "Simón de Montfort, el conde",
        meta: "Aquí no tienes pueblo: solo tu ejército. Conquista Evesham, el pueblo principal del conde Simón. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "El conde Simón y los barones rebeldes, que van juntos",
        consejo: "Es la última batalla. El conde es muy fuerte: no le ataques con un soldado solo.",
        avisos: { mortimer: "Llega Roger Mortimer con sus hombres para ayudarte: dos caballeros y un arquero de arco largo.", maquinas: "Gilbert llega con un caballero y dos catapultas para romper la muralla de Evesham." },
        jefe: { apodo: "Simón de Montfort", reino: "El conde Simón", bando: "francia", clase: "espadachin", nivel: 10, oro: 1.7, color: "#3b4a6b" },
        historia: "«Príncipe Eduardo. Cuando eras un niño, yo mismo te enseñé a manejar la espada. Veo que aprendiste bien… pero no tanto como para ganarme.» El conde Simón te mira desde la villa de Evesham, con el río detrás. «Aquí, entre el agua y la colina, se decide quién manda en Inglaterra.»" },
    ] },

  // ---------- Malí: la epopeya de Sundiata, como la cantan los griots (siglo XIII) ----------
  mali: {
    nombre: "El León de Malí", destino: "Kirina", paisaje: "sabana",
    pista: "La historia que los griots cantan desde hace ochocientos años: el niño que no podía andar y el rey herrero de Sosso. Diez capítulos, uno detrás de otro.",
    capitulos: [
      { id: 1, nombre: "El niño de la barra de hierro", mapa: "sabana", rivales: 1, batalla: "campo", ejercito: { yo: 5, rival: 3 }, objetivo: { tipo: "escapar", equipo: 0, lado: "oeste" }, guion: [{ id: "guardias", repetible: true, cuando: { cadaTurnos: 4, desde: 4 }, hacer: { refuerzos: { tropas: ["caballero"], donde: "borde", equipo: 1 }, aviso: "guardias" } }], enemigos: [{ bando: "mali", reino: "La guardia de la reina" }], dificultad: "facil", limite: 15, premio: { oro: 15 },
        voz: "Balla Fasséké, tu griot",
        meta: "Lleva a tu héroe a una de las casillas con bandera 🚩, abajo a la izquierda: por ahí se sale del reino. Tienes {t} turnos. Si se acaban y no ha llegado, pierdes. Y si matan a tu héroe, también.",
        contra: "La guardia de la reina",
        consejo: "No hace falta ganar a nadie. Que tus soldados se pongan delante de tu héroe y le abran el camino.",
        avisos: { guardias: "¡La reina manda más guardias a caballo a buscarte!" },
        historia: "Escucha, que esta historia es verdad. Yo soy tu griot: el que canta las historias de tu familia. De niño no podías andar y todos se reían de ti. Hoy te has levantado apoyado en una barra de hierro y has andado delante de todo el pueblo. La reina que manda en el palacio ahora te tiene miedo, y ha mandado a sus guardias a por ti. Hay que irse lejos, con tu madre y tus hermanas." },
      { id: 2, nombre: "El reino de Mema", mapa: "costa", rivales: 1, batalla: "clave", objetivo: { tipo: "clave", n: 2, turnos: 2 }, enemigos: [{ bando: "abasi", reino: "Los ladrones de caballos" }], dificultad: "normal", limite: 10, premio: { oro: 20 },
        voz: "El rey de Mema",
        meta: "En el mapa hay casillas marcadas con una estrella: son los pastos. Pisa dos de ellas con tus soldados y consigue que sigan siendo tuyas durante dos turnos seguidos. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los ladrones de caballos",
        consejo: "Los ladrones intentarán recuperar los pastos. Deja un soldado encima de cada uno.",
        historia: "Has caminado muchos años lejos de tu casa, de reino en reino. Aquí, en Mema, os doy techo a ti y a tu familia. Pero antes quiero saber si sabes mandar hombres. Unos ladrones se han quedado con los mejores pastos de mis caballos. Quítaselos." },
      { id: 3, nombre: "Malas noticias", mapa: "torres", rivales: 2, batalla: "asalto", ejercito: 12, guion: [{ id: "catapultas_mema", cuando: { turno: 5 }, hacer: { refuerzos: { tropas: ["catapulta", "catapulta"], donde: "borde", jugador: 0 }, aviso: "catapultas" } }], enemigos: [{ bando: "sacro_imperio", reino: "Los soldados de Sosso" }, { bando: "sacro_imperio", reino: "Los herreros de Sosso" }], dificultad: "normal", limite: 20, premio: { oro: 25 },
        voz: "Un mensajero de tu tierra",
        meta: "Aquí no tienes pueblo: solo tu ejército. Conquista el fuerte de los soldados de Sosso, que es su pueblo principal. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "Los soldados de Sosso y los herreros de Sosso. Cada uno va por su cuenta",
        consejo: "Aquí no puedes reclutar soldados, así que cuídalos. Sin catapultas cuesta mucho romper una muralla.",
        avisos: { catapultas: "El rey de Mema te manda dos catapultas. Sirven para romper murallas." },
        historia: "Venimos desde muy lejos a buscarte. Sumaoro, el rey herrero de Sosso, ha conquistado nuestra tierra. Dicen que es un brujo y que las lanzas no le tocan. Todos se acuerdan del niño de la barra de hierro. El rey de Mema te presta un ejército. Vuelve, te lo pedimos." },
      { id: 4, nombre: "Los jefes del río", mapa: "hoz", rivales: 2, equipos: [0, 1, 1], guion: [{ id: "jefes1", cuando: { turno: 5 }, hacer: { refuerzos: { tropas: ["lancero", "arquero", "caballero"], donde: "capital", jugador: 0 }, aviso: "jefes1" } }, { id: "jefes2", cuando: { turno: 9 }, hacer: { refuerzos: { tropas: ["espadachin", "arquero", "caballero"], donde: "capital", jugador: 0 }, aviso: "jefes2" } }], enemigos: [{ bando: "sacro_imperio", reino: "Los soldados de Sosso" }, { bando: "mali", reino: "Los amigos de Sumaoro" }], dificultad: "normal", limite: 16, premio: { oro: 30 },
        voz: "Tu hermana Kolonkan",
        meta: "Acaba con los soldados de Sosso y los amigos de Sumaoro: quítales sus pueblos y derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los soldados de Sosso y los amigos de Sumaoro, que van juntos",
        consejo: "Aguanta los primeros turnos sin perder tus pueblos: si te ven fuerte, puede que alguien se anime a ayudarte.",
        avisos: { jefes1: "Los primeros jefes del río se unen a ti: un lancero, un arquero y un caballero.", jefes2: "Llegan más jefes del río con sus guerreros: un espadachín, un arquero y un caballero." },
        historia: "Has vuelto con el ejército del rey de Mema, pero solo no puedes con Sumaoro. Los jefes de los pueblos del río están mirando para ver quién es más fuerte. Si ven que ganas, te darán sus guerreros." },
      { id: 5, nombre: "La sabana abierta", mapa: "sabana", rivales: 2, batalla: "campo", ejercito: { yo: 12, rival: 6 }, equipos: [0, 1, 1], enemigos: [{ bando: "sacro_imperio", reino: "Los herreros de Sosso" }, { bando: "sacro_imperio", reino: "Los soldados de hierro" }], dificultad: "normal", limite: 15, premio: { oro: 35 },
        voz: "Tu hermana Kolonkan",
        meta: "Aquí no hay pueblos: solo tu ejército contra el suyo. Derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los herreros de Sosso y los soldados de hierro, que van juntos",
        consejo: "Sus soldados son lentos. Ataca con tus jinetes a los que se queden solos.",
        historia: "Sumaoro tiene los mejores herreros del mundo, y todos sus soldados llevan hierro. Pesan mucho y andan despacio. Nosotros tenemos caballos rápidos. No pelees donde él quiere: llévalo a la sabana abierta, donde no hay dónde esconderse." },
      { id: 6, nombre: "El griot secuestrado", mapa: "torres", rivales: 2, batalla: "campo", ejercito: { yo: 14, rival: 5 }, equipos: [0, 1, 1], objetivo: { tipo: "heroe" }, enemigos: [{ bando: "sacro_imperio", reino: "El capitán de la guardia" }, { bando: "sacro_imperio", reino: "La guardia de Sumaoro" }], dificultad: "dificil", limite: 12, premio: { oro: 40 },
        voz: "Tu hermana Kolonkan",
        meta: "Aquí no hay pueblos: solo los ejércitos. Mata a los héroes de los dos jefes de la guardia y que tu héroe siga vivo. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "El capitán de la guardia y la guardia de Sumaoro, que van juntos",
        consejo: "Cuida a tu héroe: si lo matan, pierdes. Ataca a sus héroes con varios soldados a la vez.",
        historia: "Hace meses, Sumaoro se llevó a Balla Fasséké, tu griot, la voz que canta tu historia. ¡Esta noche se ha escapado! Viene corriendo hacia nosotros, pero los guardias del brujo lo persiguen. Si caen sus jefes, los demás guardias huirán." },
      { id: 7, nombre: "El secreto del brujo", mapa: "sierra", rivales: 3, objetivo: { tipo: "escapar", equipo: 0, lado: "sur" }, guion: [{ id: "guardias_lago", repetible: true, cuando: { cadaTurnos: 4, desde: 4 }, hacer: { refuerzos: { tropas: ["caballero", "caballero"], donde: "borde", equipo: 1 }, aviso: "guardias" } }], enemigos: [{ bando: "sacro_imperio", reino: "La guardia del lago" }, { bando: "sacro_imperio", reino: "La guardia del puente" }, { bando: "sacro_imperio", reino: "La guardia del camino" }], dificultad: "dificil", limite: 16, premio: { oro: 50 },
        voz: "Tu hermana Kolonkan",
        meta: "Lleva a tu héroe hasta el borde de abajo del mapa: a una de las casillas con bandera 🚩. Tienes {t} turnos. Si se acaban y no ha llegado, pierdes. Y si matan a tu héroe, también.",
        contra: "Tres grupos de guardias de Sumaoro. Cada uno va por su cuenta",
        consejo: "No hace falta ganar a nadie. Que tus soldados se pongan delante de tu héroe y le abran el camino.",
        avisos: { guardias: "¡Llegan dos jinetes más de la guardia a buscaros!" },
        historia: "Hermano, vengo del palacio de Sumaoro y sé su secreto: su brujería no sirve contra una flecha con la punta de espolón de gallo blanco. Pero sus guardias me han seguido y vigilan todos los caminos. Nuestros amigos nos esperan abajo del todo. Hay que cruzar sin que nos atrapen." },
      { id: 8, nombre: "Los doce reyes", mapa: "sabana", rivales: 3, equipos: [0, 1, 1, 1], objetivo: { tipo: "aguantar", equipo: 0, turnos: 16, capital: true }, guion: [{ id: "ejercito_sosso", repetible: true, cuando: { cadaTurnos: 2, desde: 4 }, hacer: { refuerzos: { tropas: ["lancero", "espadachin", "catapulta", "caballero"], donde: "borde", equipo: 1 }, aviso: "sosso" } }, { id: "reyes1", cuando: { turno: 7 }, hacer: { refuerzos: { tropas: ["lancero", "arquero"], donde: "capital", jugador: 0 }, aviso: "reyes1" } }, { id: "reyes2", cuando: { turno: 11 }, hacer: { refuerzos: { tropas: ["espadachin", "caballero"], donde: "capital", jugador: 0 }, aviso: "reyes2" } }], enemigos: [{ bando: "sacro_imperio", reino: "El ejército de Sosso" }, { bando: "sacro_imperio", reino: "Los herreros de Sosso" }, { bando: "sacro_imperio", reino: "La guardia de Sumaoro" }], dificultad: "dificil", limite: 16, premio: { oro: 50, objeto: "capa_indigo" },
        voz: "Balla Fasséké, tu griot",
        meta: "Defiende tu pueblo principal (el de la estrella) durante {t} turnos, hasta que lleguen los doce reyes. Si te lo quitan, pierdes. Si al acabar el turno {t} sigue siendo tuyo, ganas.",
        contra: "Tres ejércitos de Sosso, que van juntos",
        consejo: "Llena tu pueblo principal de soldados y ponle murallas. Los demás pueblos no importan tanto.",
        avisos: { sosso: "¡Llegan más soldados de Sosso, con una catapulta para romper tus murallas!", reyes1: "Llegan guerreros del primero de los doce reyes: un lancero y un arquero.", reyes2: "Llegan más guerreros de los reyes: un espadachín y un caballero." },
        historia: "Con el secreto en la mano, doce reyes del río te han jurado que lucharán contigo. Sumaoro lo sabe, y ha mandado todo su ejército contra ti antes de que lleguen. Tienes que aguantar hasta que se junten todos." },
      { id: 9, nombre: "Las montañas de Sosso", mapa: "torres", rivales: 2, equipos: [0, 1, 1], objetivo: { tipo: "tomar", jugador: 1 }, guion: [{ id: "reyes_paso1", cuando: { turno: 4 }, hacer: { refuerzos: { tropas: ["lancero", "espadachin", "catapulta", "catapulta", "catapulta"], donde: "2,9", jugador: 0 }, aviso: "reyes1" } }, { id: "reyes_paso2", cuando: { turno: 9 }, hacer: { refuerzos: { tropas: ["caballero", "caballero", "catapulta"], donde: "3,9", jugador: 0 }, aviso: "reyes2" } }], enemigos: [{ bando: "sacro_imperio", reino: "La guardia del paso" }, { bando: "sacro_imperio", reino: "El ejército de Sosso" }], dificultad: "normal", limite: 34, premio: { oro: 60 },
        voz: "Tu hermana Kolonkan",
        meta: "Conquista el fuerte de la guardia del paso, que es su pueblo principal. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "La guardia del paso y el ejército de Sosso, que van juntos",
        consejo: "No hace falta acabar con todos: solo con ese fuerte. Lleva catapultas para romper su muralla.",
        avisos: { reyes1: "Los reyes del río te mandan ayuda, abajo del mapa, cerca del fuerte: un lancero, un espadachín y tres catapultas.", reyes2: "Llega más ayuda cerca del fuerte: dos caballeros y otra catapulta." },
        historia: "Sumaoro ha perdido y retrocede hacia sus montañas. El único camino pasa por el fuerte de la guardia del paso. Detrás está la llanura de Kirina, donde se decidirá todo. Pero llegan las lluvias, y pronto los caminos serán barro. Hay que pasar ya." },
      { id: 10, nombre: "Kirina", mapa: "torres", rivales: 2, batalla: "asalto", ejercito: 18, equipos: [0, 1, 1], guion: [{ id: "kirina1", cuando: { turno: 6 }, hacer: { refuerzos: { tropas: ["espadachin", "arquero", "lancero", "caballero"], donde: "borde", jugador: 0 }, aviso: "reyes" } }, { id: "kirina2", cuando: { turno: 9 }, hacer: { refuerzos: { tropas: ["caballero", "catapulta", "catapulta"], donde: "borde", jugador: 0 }, aviso: "maquinas" } }], enemigos: [{ bando: "sacro_imperio", capital: "Sosso" }, { bando: "sacro_imperio", reino: "El ejército de Sosso" }], dificultad: "dificil", limite: 31, premio: { oro: 100, objeto: "manto_dorado" },
        voz: "Sumaoro, el rey herrero",
        meta: "Aquí no tienes pueblo: solo tu ejército. Conquista el pueblo principal de Sumaoro. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "Sumaoro, el rey herrero, y el ejército de Sosso, que van juntos",
        consejo: "Es la última batalla. Sumaoro es muy fuerte: no le ataques con un soldado solo.",
        avisos: { reyes: "Llegan los guerreros de los doce reyes: un espadachín, un arquero, un lancero y un caballero.", maquinas: "Llega un caballero con dos catapultas para romper la muralla de Sumaoro." },
        jefe: { apodo: "Sumaoro, el rey herrero", reino: "Sumaoro", bando: "sacro_imperio", clase: "espadachin", nivel: 10, oro: 1.7, color: "#4a3b2f" },
        historia: "«Hijo de Sogolon. De niño te arrastrabas por el suelo y ahora vienes a por mí con doce reyes detrás.» Sumaoro te habla con voz de trueno. «Soy el rey herrero: el hierro me obedece. Ven a Kirina, y veremos a quién cantan mañana los griots.»" },
    ] },

  // ---------- Saladino: de soldado en Egipto a los cuernos de Hattin (1167-1187) ----------
  saladino: {
    nombre: "El sultán", destino: "Hattin", paisaje: "desierto",
    pista: "Un soldado joven que acaba mandando en Egipto y Siria, y un señor que rompe todas las treguas. Diez capítulos, uno detrás de otro.",
    capitulos: [
      { id: 1, nombre: "Alejandría", mapa: "costa", rivales: 1, objetivo: { tipo: "aguantar", equipo: 0, turnos: 12, capital: true }, guion: [{ id: "francos", repetible: true, cuando: { cadaTurnos: 3, desde: 3 }, hacer: { refuerzos: { tropas: ["lancero", "espadachin", "caballero"], donde: "borde", jugador: 1 }, aviso: "francos" } }], enemigos: [{ bando: "francia", reino: "Los francos" }], capital: "Alejandría", dificultad: "facil", limite: 12, premio: { oro: 15 },
        voz: "Tu tío Shirkuh",
        meta: "Defiende tu pueblo principal (el de la estrella) durante {t} turnos, hasta que vuelva tu tío. Si te lo quitan, pierdes. Si al acabar el turno {t} sigue siendo tuyo, ganas.",
        contra: "Los francos",
        consejo: "Llena tu pueblo principal de soldados y ponle murallas. Los demás pueblos no importan tanto.",
        avisos: { francos: "¡Llegan más francos por el camino!" },
        historia: "Sobrino, tengo que salir con el ejército a buscar comida. Te dejo al mando de Alejandría, una gran ciudad junto al mar. Tienes pocos soldados, y los francos, unos caballeros que vienen de muy lejos, la rodean por tierra. No te pido que ganes: te pido que no la pierdas." },
      { id: 2, nombre: "Visir de Egipto", mapa: "nilo", rivales: 1, guion: [{ id: "turan", cuando: { turno: 7 }, hacer: { refuerzos: { jugador: 0, tropas: ["lancero", "caballero"], donde: "capital" }, aviso: "turan" } }], enemigos: [{ bando: "abasi", reino: "Los emires del delta" }], dificultad: "normal", limite: 18, premio: { oro: 20 },
        voz: "Un consejero del califa",
        meta: "Acaba con los emires del delta: quítales sus pueblos y derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los emires del delta",
        consejo: "Aguanta los primeros turnos: puede que pronto llegue alguien a ayudarte.",
        avisos: { turan: "Tu hermano Turan llega de El Cairo con soldados: un lancero y un caballero." },
        historia: "Tu tío ha muerto, y el califa, el jefe de Egipto, te ha nombrado visir: el que manda en su nombre. Pero los emires del delta, los señores de las tierras junto al río Nilo, dicen que eres un soldado demasiado joven. Hay que enseñarles quién manda ahora." },
      { id: 3, nombre: "Damieta", mapa: "nilo", rivales: 2, equipos: [0, 1, 1], guion: [{ id: "desembarco", repetible: true, cuando: { cadaTurnos: 6, desde: 6 }, hacer: { refuerzos: { equipo: 1, tropas: ["espadachin"], donde: "borde" }, aviso: "desembarco" } }, { id: "egipto1", cuando: { turno: 5 }, hacer: { refuerzos: { tropas: ["lancero", "arquero", "caballero", "caballero"], donde: "capital", jugador: 0 }, aviso: "egipto1" } }, { id: "egipto2", cuando: { turno: 9 }, hacer: { refuerzos: { tropas: ["espadachin", "arquero", "caballero"], donde: "capital", jugador: 0 }, aviso: "egipto2" } }], enemigos: [{ bando: "bizancio", reino: "Los griegos de Bizancio" }, { bando: "francia", reino: "Los francos" }], capital: "Damieta", dificultad: "facil", limite: 18, premio: { oro: 25 },
        voz: "Tu hermano Turan",
        meta: "Acaba con los griegos y los francos: quítales sus pueblos y derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los griegos de Bizancio y los francos, que van juntos",
        consejo: "Van juntos: no dejes tus pueblos vacíos. Aguanta los primeros turnos: Egipto te mandará ayuda.",
        avisos: { egipto1: "Llega ayuda de El Cairo: un lancero, un arquero y dos caballeros.", egipto2: "Llega más ayuda de El Cairo: un espadachín, un arquero y un caballero.", desembarco: "¡Desembarcan más soldados de los barcos enemigos!" },
        historia: "¡Doscientos barcos, hermano! Los griegos de Bizancio y los francos han llegado juntos a Damieta, en la boca del río Nilo. Si ganan aquí, el río queda abierto hasta El Cairo, nuestra capital. Hay que echarlos antes de que desembarquen todos." },
      { id: 4, nombre: "Damasco", mapa: "torres", rivales: 2, batalla: "clave", objetivo: { tipo: "clave", n: 2, turnos: 2 }, enemigos: [{ bando: "abasi", reino: "Los emires del norte" }, { bando: "abasi", reino: "Los emires del sur" }], dificultad: "normal", limite: 14, premio: { oro: 30 },
        voz: "Un mercader de Damasco",
        meta: "En el mapa hay casillas marcadas con una estrella: son los barrios de la ciudad. Pisa dos de ellas con tus soldados y consigue que sigan siendo tuyas durante dos turnos seguidos. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los emires del norte y los del sur. Cada uno va por su cuenta",
        consejo: "Los emires se pelean entre ellos. Llega rápido y deja un soldado encima de cada estrella.",
        historia: "Ha muerto Nur al-Din, el señor de Siria, y ha dejado un hijo pequeño. Sus emires se pelean por la ciudad de Damasco como perros por un hueso. La gente de la ciudad os abrirá las puertas si llegáis los primeros a sus barrios." },
      { id: 5, nombre: "Alepo", mapa: "torres", rivales: 2, batalla: "asalto", ejercito: 12, guion: [{ id: "maquinas_alepo", cuando: { turno: 5 }, hacer: { refuerzos: { tropas: ["catapulta", "catapulta"], donde: "borde", jugador: 0 }, aviso: "catapultas" } }], enemigos: [{ bando: "abasi", reino: "La guardia de Alepo", capital: "Alepo" }, { bando: "abasi", reino: "Los emires de Alepo" }], dificultad: "normal", limite: 22, premio: { oro: 35 },
        voz: "Tu hermano Turan",
        meta: "Aquí no tienes pueblo: solo tu ejército. Conquista Alepo, el pueblo principal de su guardia. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "La guardia de Alepo y los emires de Alepo. Cada uno va por su cuenta",
        consejo: "Aquí no puedes reclutar soldados, así que cuídalos. Sin catapultas cuesta mucho romper una muralla.",
        avisos: { catapultas: "Llegan dos catapultas desde Damasco. Sirven para romper murallas." },
        historia: "Damasco ya es nuestra, pero Alepo, en el norte, no nos quiere. Tiene las murallas más altas de toda Siria y está detrás de las montañas. Mientras Alepo no esté con nosotros, Siria seguirá partida en dos." },
      { id: 6, nombre: "Montgisard", mapa: "estepa", rivales: 1, batalla: "campo", ejercito: { yo: 6, rival: 5 }, objetivo: { tipo: "escapar", equipo: 0, lado: "oeste" }, guion: [{ id: "persecucion", repetible: true, cuando: { cadaTurnos: 2, desde: 2 }, hacer: { refuerzos: { tropas: ["caballero"], donde: "borde", equipo: 1 }, aviso: "jinetes" } }], enemigos: [{ bando: "francia", reino: "El rey Balduino" }], dificultad: "dificil", limite: 10, premio: { oro: 40 },
        voz: "Tu hermano Turan",
        meta: "Lleva a tu héroe a una de las casillas con bandera 🚩, abajo a la izquierda: por ahí se vuelve a Egipto. Tienes {t} turnos. Si se acaban y no ha llegado, pierdes. Y si matan a tu héroe, también.",
        contra: "Los caballeros del rey Balduino",
        consejo: "No hace falta ganar a nadie. Que tus soldados se pongan delante de tu héroe y le abran el camino.",
        avisos: { jinetes: "¡Más caballeros del rey Balduino se unen a la persecución!" },
        historia: "Nos confiamos, hermano. Pensamos que el joven rey Balduino no se atrevería a salir de su ciudad, y nos sorprendió en Montgisard. Hemos perdido la mitad de los hombres. Ahora hay que volver a Egipto, y nos persiguen." },
      { id: 7, nombre: "Las caravanas", mapa: "costa", rivales: 3, batalla: "campo", ejercito: { yo: 17, rival: 5 }, equipos: [0, 1, 1, 1], guion: [{ id: "mas_jinetes", cuando: { turno: 8 }, hacer: { refuerzos: { equipo: 1, tropas: ["caballero", "caballero"], donde: "borde" }, aviso: "jinetes" } }], enemigos: [{ bando: "francia", reino: "Los jinetes de Kerak" }, { bando: "francia", reino: "Los saqueadores de Kerak" }, { bando: "francia", reino: "Los ladrones del camino" }], dificultad: "dificil", limite: 15, premio: { oro: 50 },
        voz: "Un mercader de la caravana",
        meta: "Aquí no hay pueblos: solo tu ejército contra el suyo. Derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los jinetes de Kerak, sus saqueadores y los ladrones del camino, que van juntos",
        consejo: "Mantén juntos a tus soldados y ataca a cada enemigo con varios a la vez.",
        avisos: { jinetes: "¡Llegan dos jinetes más de Kerak!" },
        historia: "¡Señor, ayudadnos! Reinaldo, el señor del castillo de Kerak, ha atacado nuestra caravana. Hay tregua, que es una promesa de no pelear, pero a él no le importa: roba, quema y se lleva presa a la gente. Sus jinetes siguen en el camino." },
      { id: 8, nombre: "El castillo de Kerak", mapa: "torres", rivales: 2, equipos: [0, 1, 1], objetivo: { tipo: "tomar", jugador: 1 }, guion: [{ id: "kerak1", cuando: { turno: 4 }, hacer: { refuerzos: { tropas: ["lancero", "espadachin", "catapulta", "catapulta", "catapulta"], donde: "2,9", jugador: 0 }, aviso: "kerak1" } }, { id: "kerak2", cuando: { turno: 9 }, hacer: { refuerzos: { tropas: ["caballero", "caballero", "catapulta"], donde: "3,9", jugador: 0 }, aviso: "kerak2" } }], enemigos: [{ bando: "francia", reino: "La guardia de Kerak", capital: "Kerak" }, { bando: "francia", reino: "Los caballeros de Reinaldo" }], dificultad: "normal", limite: 30, premio: { oro: 50, objeto: "capa_seda" },
        voz: "Tu hermano Turan",
        meta: "Conquista el castillo de Kerak, el pueblo principal de su guardia. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "La guardia de Kerak y los caballeros de Reinaldo, que van juntos",
        consejo: "No hace falta acabar con todos: solo con el castillo. Sus murallas son altas: lleva catapultas.",
        avisos: { kerak1: "Llegan tus máquinas de asedio, abajo del mapa, cerca del castillo: un lancero, un espadachín y tres catapultas.", kerak2: "Llega más ayuda cerca del castillo: dos caballeros y otra catapulta." },
        historia: "Hemos llegado a Kerak, el nido de Reinaldo. Dentro hay una boda, y la madre del novio nos ha mandado comida de la fiesta. Tú has ordenado no disparar a la torre donde duermen los novios. Al resto del castillo, sí." },
      { id: 9, nombre: "Los pozos de Séforis", mapa: "sierra", rivales: 2, batalla: "clave", equipos: [0, 1, 1], objetivo: { tipo: "clave", n: 2, turnos: 3 }, enemigos: [{ bando: "francia", reino: "El ejército del reino" }, { bando: "francia", reino: "Los caballeros del Temple" }], dificultad: "dificil", limite: 16, premio: { oro: 60 },
        voz: "Tu hermano Turan",
        meta: "En el mapa hay casillas marcadas con una estrella: son los pozos del camino. Pisa dos de ellas con tus soldados y consigue que sigan siendo tuyas durante tres turnos seguidos. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "El ejército del reino y los caballeros del Temple, que van juntos",
        consejo: "Llega a los pozos antes que ellos y deja soldados fuertes encima.",
        historia: "El ejército más grande que han juntado nunca los francos ha salido de Séforis, donde tenían agua de sobra, para venir a por nosotros. Hace un calor terrible. Si les quitamos los pozos del camino, llegarán a la batalla muertos de sed." },
      { id: 10, nombre: "Los cuernos de Hattin", mapa: "hattin", rivales: 3, batalla: "campo", ejercito: { yo: 18, rival: 5 }, equipos: [0, 1, 1, 1], enemigos: [{ bando: "francia" }, { bando: "francia", reino: "El ejército del reino" }, { bando: "francia", reino: "Los caballeros del Temple" }], dificultad: "dificil", limite: 16, premio: { oro: 100, objeto: "capa_aguila" },
        voz: "Reinaldo de Châtillon",
        meta: "Aquí no hay pueblos: solo tu ejército contra el suyo. Derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Reinaldo, el ejército del reino y los caballeros del Temple, que van juntos",
        consejo: "Es la última batalla. Reinaldo es muy fuerte: no le ataques con un soldado solo.",
        jefe: { apodo: "Reinaldo de Châtillon", reino: "Reinaldo", bando: "francia", clase: "nordico", nivel: 10, oro: 1.7, color: "#5a3a2a" },
        historia: "«Saladino. Rompí tu tregua y la volvería a romper.» Reinaldo grita desde lo alto de una de las dos colinas, con la boca seca. «Tengo el ejército más grande que ha visto nunca este reino. Aquí, entre estos dos cuernos de piedra, te voy a enseñar lo que es pelear.»" },
    ] },

  // ---------- Mongoles: Temujín, antes de ser Gengis Kan (1175-1204) ----------
  mongoles: {
    nombre: "Temujín", destino: "Chakirmaut", paisaje: "estepa",
    pista: "Un niño abandonado en la estepa, un hermano de sangre y la guerra por todas las tribus. Diez capítulos, uno detrás de otro.",
    capitulos: [
      { id: 1, nombre: "El yugo de madera", mapa: "estepa", rivales: 1, batalla: "campo", ejercito: { yo: 5, rival: 3 }, objetivo: { tipo: "escapar", equipo: 0, lado: "oeste" }, guion: [{ id: "taichiutos", repetible: true, cuando: { cadaTurnos: 4, desde: 4 }, hacer: { refuerzos: { tropas: ["caballero"], donde: "borde", equipo: 1 }, aviso: "jinetes" } }], enemigos: [{ bando: "hungria", reino: "Los taichiutos" }], dificultad: "facil", limite: 15, premio: { oro: 15 },
        voz: "Tu madre, Hoelun",
        meta: "Lleva a tu héroe a una de las casillas con bandera 🚩, abajo a la izquierda: allí te esperamos. Tienes {t} turnos. Si se acaban y no ha llegado, pierdes. Y si matan a tu héroe, también.",
        contra: "Los taichiutos",
        consejo: "No hace falta ganar a nadie. Que tus soldados se pongan delante de tu héroe y le abran el camino.",
        avisos: { jinetes: "¡Los taichiutos se han dado cuenta y mandan más jinetes a buscarte!" },
        historia: "Hijo, tu padre murió envenenado y la tribu nos dejó solos en la estepa, sin nada. Ahora los taichiutos, otra tribu, te han cogido y te han puesto un yugo de madera en el cuello. Esta noche celebran una fiesta y no vigilan bien. Escapa y vuelve con nosotros." },
      { id: 2, nombre: "Los ocho caballos", mapa: "gobi", rivales: 1, batalla: "campo", ejercito: { yo: 6, rival: 5 }, enemigos: [{ bando: "hungria", reino: "Los ladrones de la estepa" }], dificultad: "normal", limite: 12, premio: { oro: 20 },
        voz: "Bo'orchu, un chico de otra tribu",
        meta: "Aquí no hay pueblos: solo tu ejército contra el suyo. Derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los ladrones de la estepa",
        consejo: "Bo'orchu va contigo. Ataca a cada ladrón con dos o tres soldados a la vez.",
        historia: "No te conozco de nada, pero me has caído bien. Unos ladrones se han llevado los ocho caballos de tu familia, ¿verdad? Toma mi caballo, que está fresco, y vamos juntos a por ellos. Desde hoy, lo que sea tuyo es mío, y lo mío, tuyo." },
      { id: 3, nombre: "Börte", mapa: "torres", rivales: 3, equipos: [0, 0, 1, 1], objetivo: { tipo: "tomar", jugador: 2 }, guion: [{ id: "regalo_yamuja", cuando: { turno: 4 }, hacer: { refuerzos: { jugador: 0, tropas: ["lancero", "espadachin", "catapulta", "catapulta"], donde: "objetivo" }, aviso: "yamuja1" } }, { id: "regalo_yamuja2", cuando: { turno: 9 }, hacer: { refuerzos: { jugador: 0, tropas: ["caballero", "caballero", "catapulta"], donde: "objetivo" }, aviso: "yamuja2" } }], enemigos: [{ bando: "hungria", reino: "Yamuja, tu hermano de sangre" }, { bando: "hungria", reino: "Los merkitas" }, { bando: "hungria", reino: "Los guerreros merkitas" }], dificultad: "normal", limite: 26, premio: { oro: 25 },
        voz: "Yamuja, tu hermano de sangre",
        meta: "Conquista el campamento de los merkitas, su pueblo principal, y rescata a Börte. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "Los merkitas y sus guerreros, que van juntos. Yamuja pelea contigo",
        consejo: "Yamuja es tu aliado: no hace falta que lo hagas todo solo. Id juntos a por el campamento.",
        avisos: { yamuja1: "Los jinetes de Yamuja te traen dos catapultas cerca del campamento merkita. Sirven para romper murallas.", yamuja2: "Llega más ayuda cerca del campamento: dos caballeros y otra catapulta." },
        historia: "Hermano, me he enterado. Los merkitas, una tribu enemiga, entraron de noche en tu campamento y se llevaron a Börte, tu mujer. No vas a ir solo: cuando éramos niños juramos ser hermanos, y un hermano no se queda mirando. Mis jinetes vienen contigo." },
      { id: 4, nombre: "Los pastos del río", mapa: "estepa", rivales: 2, batalla: "clave", objetivo: { tipo: "clave", n: 2, turnos: 2 }, enemigos: [{ bando: "hungria", reino: "Los de Yamuja" }, { bando: "hungria", reino: "Los clanes que dudan" }], dificultad: "normal", limite: 12, premio: { oro: 30 },
        voz: "Börte, tu mujer",
        meta: "En el mapa hay casillas marcadas con una estrella: son los mejores pastos. Pisa dos de ellas con tus soldados y consigue que sigan siendo tuyas durante dos turnos seguidos. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los de Yamuja y los clanes que dudan. Cada uno va por su cuenta",
        consejo: "Llega rápido a los pastos y deja un soldado encima de cada uno.",
        historia: "Ya estoy en casa, gracias a ti y a Yamuja. Pero ¿no lo ves? Los clanes de la tribu empiezan a elegir: unos te siguen a ti y otros a él. Yamuja quiere a los ricos; tú, a los que valen. Quien tenga los mejores pastos se quedará con la tribu." },
      { id: 5, nombre: "Los tártaros", mapa: "gobi", rivales: 2, equipos: [0, 1, 1], guion: [{ id: "china", cuando: { turno: 7 }, hacer: { refuerzos: { tropas: ["caballero", "arquero"], donde: "capital", jugador: 0 }, oro: { jugador: 0, cantidad: 40 }, aviso: "china" } }, { id: "clanes", cuando: { turno: 11 }, hacer: { refuerzos: { tropas: ["lancero", "caballero", "caballero"], donde: "capital", jugador: 0 }, aviso: "clanes" } }], enemigos: [{ bando: "hungria", reino: "Los tártaros" }, { bando: "hungria", reino: "Los tártaros del desierto" }], dificultad: "normal", limite: 18, premio: { oro: 35 },
        voz: "Börte, tu mujer",
        meta: "Acaba con los tártaros: quítales sus pueblos y derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Dos grupos de tártaros, que van juntos",
        consejo: "Van juntos: no dejes tus pueblos vacíos. Aguanta los primeros turnos: puede que llegue ayuda.",
        avisos: { china: "El emperador de China te manda 40 monedas de oro y dos soldados: un caballero y un arquero.", clanes: "Más clanes se unen a ti al ver que ganas: un lancero y dos caballeros." },
        historia: "Los tártaros, los que envenenaron a tu padre, han atacado la frontera del imperio de China. Su emperador pagará a quien los castigue. Es la ocasión de vengar a tu padre, y encima te pagan por ello. Cruzaremos el desierto." },
      { id: 6, nombre: "Los trece campamentos", mapa: "sierra", rivales: 2, equipos: [0, 1, 1], objetivo: { tipo: "aguantar", equipo: 0, turnos: 14, capital: true }, guion: [{ id: "yamuja_ataca", repetible: true, cuando: { cadaTurnos: 2, desde: 3 }, hacer: { refuerzos: { tropas: ["lancero", "espadachin", "catapulta"], donde: "borde", equipo: 1 }, aviso: "yamuja" } }], enemigos: [{ bando: "hungria", reino: "Los de Yamuja" }, { bando: "hungria", reino: "Los trece campamentos" }], dificultad: "dificil", limite: 14, hucha: 1, premio: { oro: 40 },
        voz: "Börte, tu mujer",
        meta: "Defiende tu pueblo principal (el de la estrella) durante {t} turnos. Si te lo quitan, pierdes. Si al acabar el turno {t} sigue siendo tuyo, ganas.",
        contra: "Los de Yamuja y los trece campamentos, que van juntos",
        consejo: "Empiezas con la mitad del oro de siempre. Gástalo en llenar tu pueblo principal de soldados.",
        avisos: { yamuja: "¡Llegan más guerreros de Yamuja, con una catapulta para romper tus murallas!" },
        historia: "Yamuja te ha atacado por sorpresa con trece campamentos de guerreros, y has perdido. Ya no es tu hermano: ahora es tu rival. Nos quedan la mitad de los hombres y la mitad del oro. Nos hemos refugiado en las montañas. Aquí hay que aguantar." },
      { id: 7, nombre: "La trampa de Togril", mapa: "torres", rivales: 3, objetivo: { tipo: "escapar", equipo: 0, lado: "sur" }, guion: [{ id: "keraitas", repetible: true, cuando: { cadaTurnos: 3, desde: 3 }, hacer: { refuerzos: { tropas: ["caballero", "caballero"], donde: "borde", equipo: 1 }, aviso: "keraitas" } }], enemigos: [{ bando: "polonia", reino: "Los keraítas" }, { bando: "polonia", reino: "Los guerreros de Togril" }, { bando: "hungria", reino: "Los de Yamuja" }], dificultad: "dificil", limite: 16, premio: { oro: 50 },
        voz: "Bo'orchu, tu amigo",
        meta: "Lleva a tu héroe hasta el borde de abajo del mapa: a una de las casillas con bandera 🚩. Tienes {t} turnos. Si se acaban y no ha llegado, pierdes. Y si matan a tu héroe, también.",
        contra: "Los keraítas, los guerreros de Togril y los de Yamuja. Cada uno va por su cuenta",
        consejo: "No hace falta ganar a nadie. Que tus soldados se pongan delante de tu héroe y le abran el camino.",
        avisos: { keraitas: "¡Llegan dos jinetes keraítas más a cortarte el paso!" },
        historia: "¡Es una trampa, Temujín! Togril, el jefe de los keraítas, que era como un padre para ti, te invitó a una boda. Pero Yamuja lo ha convencido de que eres un peligro. Sus campamentos nos rodean. Hay que salir de aquí antes de que nos cierren el paso." },
      { id: 8, nombre: "El agua de barro", mapa: "estepa", rivales: 2, batalla: "campo", ejercito: { yo: 15, rival: 6 }, equipos: [0, 1, 1], objetivo: { tipo: "heroe" }, enemigos: [{ bando: "polonia", reino: "Togril, el jefe keraíta" }, { bando: "polonia", reino: "Los keraítas" }], dificultad: "dificil", limite: 12, premio: { oro: 50, objeto: "capa_fieltro" },
        voz: "Bo'orchu, tu amigo",
        meta: "Aquí no hay pueblos: solo los ejércitos. Mata a los héroes de Togril y de sus keraítas y que tu héroe siga vivo. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Togril y los keraítas, que van juntos",
        consejo: "Cuida a tu héroe: si lo matan, pierdes. Ataca a sus héroes con varios soldados a la vez.",
        historia: "Solo te quedan unos pocos hombres. Habéis bebido juntos agua de barro, jurando no separaros nunca. Son pocos, pero valen por cien. Togril cree que estás acabado y lo está celebrando. Esta noche no nos esperan." },
      { id: 9, nombre: "Las hogueras", mapa: "costa", rivales: 3, batalla: "campo", ejercito: { yo: 18, rival: 4 }, equipos: [0, 1, 1, 1], guion: [{ id: "mas_naimanos", cuando: { turno: 8 }, hacer: { refuerzos: { equipo: 1, tropas: ["caballero", "caballero"], donde: "borde" }, aviso: "naimanos" } }], enemigos: [{ bando: "sacro_imperio", reino: "Los naimanos" }, { bando: "sacro_imperio", reino: "Los jinetes naimanos" }, { bando: "hungria", reino: "Los de Yamuja" }], dificultad: "dificil", limite: 15, premio: { oro: 60 },
        voz: "Bo'orchu, tu amigo",
        meta: "Aquí no hay pueblos: solo tu ejército contra el suyo. Derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los naimanos, sus jinetes y los de Yamuja, que van juntos",
        consejo: "Mantén juntos a tus soldados y ataca a cada enemigo con varios a la vez.",
        avisos: { naimanos: "¡Llegan más jinetes naimanos! Ya no se creen lo de las hogueras." },
        historia: "El último gran pueblo de la estepa, los naimanos, se ha unido a Yamuja. Son muchos. Esta noche cada soldado ha encendido cinco hogueras, y al verlas han creído que somos muchísimos. Ahora tienen miedo. Es el momento de atacar." },
      { id: 10, nombre: "Chakirmaut", mapa: "torres", rivales: 2, batalla: "asalto", ejercito: 18, equipos: [0, 1, 1], guion: [{ id: "clanes_final", cuando: { turno: 6 }, hacer: { refuerzos: { tropas: ["espadachin", "arquero", "lancero", "caballero"], donde: "borde", jugador: 0 }, aviso: "clanes" } }, { id: "maquinas_final", cuando: { turno: 9 }, hacer: { refuerzos: { tropas: ["caballero", "catapulta", "catapulta"], donde: "borde", jugador: 0 }, aviso: "maquinas" } }], enemigos: [{ bando: "hungria" }, { bando: "sacro_imperio", reino: "Los naimanos" }], dificultad: "dificil", limite: 31, premio: { oro: 100, objeto: "capa_estepa" },
        voz: "Yamuja",
        meta: "Aquí no tienes pueblo: solo tu ejército. Conquista el pueblo principal de Yamuja. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "Yamuja y los naimanos, que van juntos",
        consejo: "Es la última batalla. Yamuja es muy fuerte: no le ataques con un soldado solo.",
        avisos: { clanes: "Llegan los clanes que te siguen: un espadachín, un arquero, un lancero y un caballero.", maquinas: "Llega un caballero con dos catapultas para romper la muralla de Yamuja." },
        jefe: { apodo: "Yamuja", reino: "Yamuja", bando: "hungria", clase: "nordico", nivel: 10, oro: 1.7, color: "#3f4a2a" },
        historia: "«Temujín, hermano. Cuando éramos niños jugábamos en el río helado y te regalé una punta de flecha de hueso.» Yamuja habla desde la montaña, con los naimanos detrás. «Ahora uno de los dos tiene que quedarse con la estepa entera. Ven a buscarme.»" },
    ] },
  // Tribus eslavas (15 sep 2026): una historia inventada a propósito, antes de los reinos, para que no sea de
  // ningún país. Los malos son los ávaros, un pueblo de jinetes que cobró tributo a todos los eslavos y ya no existe.
  eslavos: {
    nombre: "Vesna", destino: "La primavera", paisaje: "bosque",
    pista: "Una aldea quemada, una muchacha a la que escuchan las tormentas y todas las tribus del bosque contra el kagan. Diez capítulos, uno detrás de otro.",
    capitulos: [
      { id: 1, nombre: "La aldea en llamas", mapa: "bosque_viejo", rivales: 1, batalla: "campo", ejercito: { yo: 6, rival: 5 }, enemigos: [{ bando: "avaros", reino: "Los jinetes ávaros" }], dificultad: "facil", limite: 12, premio: { oro: 15 },
        voz: "La abuela Mokosha",
        meta: "Aquí no hay pueblos: solo tu ejército contra el suyo. Derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los jinetes ávaros",
        consejo: "Ataca a cada jinete con dos o tres soldados a la vez: así caen antes.",
        historia: "Vesna, niña, los ávaros, unos jinetes que vienen de la llanura, han quemado la aldea. Tú tienes un don: las tormentas te escuchan. Todavía quedan algunos jinetes por aquí. Échalos, y luego llevaremos a la gente que queda al bosque viejo, por sendas que ellos no conocen." },
      { id: 2, nombre: "El tributo del río", mapa: "costa", rivales: 1, batalla: "clave", objetivo: { tipo: "clave", n: 3, turnos: 2 }, enemigos: [{ bando: "avaros", reino: "Los cobradores del kagan" }], dificultad: "normal", limite: 12, premio: { oro: 20 },
        voz: "Radim, el herrero",
        meta: "En el mapa hay casillas marcadas con una estrella: son los vados, los sitios por donde se cruza el río. Pisa tres de ellas con tus soldados y consigue que sigan siendo tuyas durante dos turnos seguidos. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los cobradores del kagan",
        consejo: "Necesitas tres vados a la vez. Deja un soldado fuerte encima de cada uno.",
        historia: "Los ávaros cobran por cruzar el río: grano, pieles y chicos para su ejército. Eso es un tributo, y lo manda cobrar el kagan, su jefe. Yo forjo las lanzas y tú haces caer los rayos. Si les quitamos los vados del río, se acabó el tributo." },
      { id: 3, nombre: "La tribu del lago", mapa: "isla", rivales: 1, batalla: "campo", ejercito: { yo: 7, rival: 7 }, objetivo: { tipo: "heroe" }, enemigos: [{ bando: "eslavos", reino: "La tribu del lago" }], dificultad: "normal", limite: 12, premio: { oro: 25 },
        voz: "Radim, el herrero",
        meta: "Aquí no hay pueblos: solo los ejércitos. Vence al campeón de Borislav (su héroe) y que tu héroe siga vivo. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "El campeón de Borislav y la tribu del lago",
        consejo: "Cuida a tu héroe: si cae, pierdes. Ataca a su campeón con varios soldados a la vez.",
        historia: "La tribu del lago no quiere unirse a nosotros. Su jefe, Borislav, dice que una muchacha no manda a nadie. Ha propuesto una pelea: si vences a su campeón, el mejor guerrero de la tribu, todos te seguirán. Demuéstrale que se equivoca." },
      { id: 4, nombre: "Las colinas del trueno", mapa: "torres", rivales: 3, equipos: [0, 0, 1, 1], objetivo: { tipo: "tomar", jugador: 2 }, guion: [{ id: "radim1", cuando: { turno: 4 }, hacer: { refuerzos: { jugador: 0, tropas: ["lancero", "espadachin", "catapulta", "catapulta"], donde: "objetivo" }, aviso: "radim1" } }, { id: "radim2", cuando: { turno: 9 }, hacer: { refuerzos: { jugador: 0, tropas: ["caballero", "catapulta"], donde: "objetivo" }, aviso: "radim2" } }], enemigos: [{ bando: "eslavos", reino: "Borislav, tu aliado" }, { bando: "avaros", reino: "Los vigías ávaros" }, { bando: "avaros", reino: "Los jinetes del kagan" }], dificultad: "normal", limite: 26, premio: { oro: 30 },
        voz: "Borislav, el jefe del lago",
        meta: "Conquista la torre de los vigías ávaros, que es su pueblo principal. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "Los vigías ávaros y los jinetes del kagan, que van juntos. Borislav pelea contigo",
        consejo: "Borislav es tu aliado: id juntos a por la torre.",
        avisos: { radim1: "Radim te trae dos catapultas cerca de la torre de los vigías. Sirven para romper murallas.", radim2: "Llega más ayuda cerca de la torre: un caballero y otra catapulta." },
        historia: "Me ganaste limpio, hechicera, y mi palabra se cumple: mis hombres pelearán a tu lado. Desde las colinas del trueno, los vigías ávaros ven todos los caminos. Si tomamos su torre, sabremos por dónde vienen antes de que lleguen." },
      { id: 5, nombre: "El invierno largo", mapa: "bosque_viejo", rivales: 2, equipos: [0, 1, 1], objetivo: { tipo: "aguantar", equipo: 0, turnos: 14, capital: true }, guion: [{ id: "avaros_invierno", repetible: true, cuando: { cadaTurnos: 2, desde: 4 }, hacer: { refuerzos: { tropas: ["lancero", "espadachin", "catapulta"], donde: "borde", equipo: 1 }, aviso: "avaros" } }], enemigos: [{ bando: "avaros", reino: "Los jinetes ávaros" }, { bando: "avaros", reino: "Los jinetes del kagan" }], dificultad: "normal", limite: 14, hucha: 1, premio: { oro: 35 },
        voz: "La abuela Mokosha",
        meta: "Defiende tu pueblo principal (el de la estrella) durante {t} turnos, hasta que llegue la primavera. Si te lo quitan, pierdes. Si al acabar el turno {t} sigue siendo tuyo, ganas.",
        contra: "Los jinetes ávaros y los del kagan, que van juntos",
        consejo: "Empiezas con la mitad del oro de siempre. Gástalo en llenar tu pueblo principal de soldados.",
        avisos: { avaros: "¡Llegan más ávaros, con una catapulta para romper tus murallas!" },
        historia: "No recuerdo un invierno tan duro. Los graneros están casi vacíos y los ávaros lo saben: vienen ahora que estamos débiles. Pero el bosque y el frío también están de nuestro lado. Hay que aguantar hasta la primavera." },
      { id: 6, nombre: "Los tratantes de la costa", mapa: "torres", rivales: 2, batalla: "asalto", ejercito: 12, guion: [{ id: "maquinas_costa", cuando: { turno: 3 }, hacer: { refuerzos: { tropas: ["catapulta", "catapulta", "catapulta"], donde: "borde", jugador: 0 }, aviso: "catapultas" } }, { id: "maquinas_costa2", cuando: { turno: 8 }, hacer: { refuerzos: { jugador: 0, tropas: ["espadachin", "caballero", "catapulta"], donde: "borde" }, aviso: "refuerzo2" } }], enemigos: [{ bando: "sacro_imperio", reino: "Los tratantes del oeste" }, { bando: "avaros", reino: "La escolta ávara" }], dificultad: "dificil", limite: 30, premio: { oro: 40 },
        voz: "Radim, el herrero",
        meta: "Aquí no tienes pueblo: solo tu ejército. Conquista el puerto de los tratantes, que es su pueblo principal. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "Los tratantes del oeste y su escolta ávara. Cada uno va por su cuenta",
        consejo: "Aquí no puedes reclutar soldados, así que cuídalos. Sin catapultas cuesta mucho romper una muralla.",
        avisos: { catapultas: "Radim ha construido tres catapultas y te las trae. Sirven para romper murallas.", refuerzo2: "Llegan más hombres de la aldea: un espadachín, un caballero y otra catapulta." },
        historia: "¿Sabes adónde se llevan a los que capturan los ávaros? Los venden a unos tratantes, gente que compra y vende personas, que vienen del oeste por la costa. Mi hermano está entre ellos, encerrado en su puerto. Si lo tomamos, volverá a casa, y con él muchos otros." },
      { id: 7, nombre: "Las siete tribus", mapa: "torres", rivales: 3, equipos: [0, 1, 1, 1], guion: [{ id: "tribu_se_une", cuando: { turno: 9 }, hacer: { equipo: { jugador: 2, nuevo: 0 }, aviso: "tribu" } }], enemigos: [{ bando: "avaros", reino: "Los emisarios del kagan" }, { bando: "eslavos", reino: "La tribu del río" }, { bando: "eslavos", reino: "La tribu del monte" }], dificultad: "dificil", limite: 18, premio: { oro: 50 },
        voz: "Borislav",
        meta: "Acaba con los emisarios del kagan y las tribus que están con ellos: quítales sus pueblos y derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Los emisarios del kagan y dos tribus, que de momento van juntos",
        consejo: "No todas las tribus quieren pelear contigo. Aguanta sin perder tus pueblos y verás.",
        avisos: { tribu: "La tribu del río ha visto cómo peleas y decide unirse a ti. Ahora está de tu lado." },
        historia: "Siete tribus se reúnen entre las cuatro torres para decidir si van contigo o con el oro de los ávaros. Los emisarios del kagan, sus mensajeros, ya están allí repartiendo regalos, y algunas tribus se han puesto de su lado. Que vean de qué lado está la fuerza." },
      { id: 8, nombre: "Fuera del bosque", mapa: "llanura_avara", rivales: 3, batalla: "campo", ejercito: { yo: 18, rival: 4 }, equipos: [0, 1, 1, 1], guion: [{ id: "mas_avaros", cuando: { turno: 10 }, hacer: { refuerzos: { equipo: 1, tropas: ["caballero"], donde: "borde" }, aviso: "avaros" } }], enemigos: [{ bando: "avaros", reino: "Los jinetes del kagan" }, { bando: "avaros", reino: "Los arqueros del kagan" }, { bando: "avaros", reino: "Los jinetes de la llanura" }], dificultad: "dificil", limite: 15, premio: { oro: 50, objeto: "capa_abedul" },
        voz: "Borislav",
        meta: "Aquí no hay pueblos: solo tu ejército contra el suyo. Derrota a todos sus soldados. Tienes {t} turnos. Si se acaban antes, gana quien tenga más puntos.",
        contra: "Tres grupos de soldados del kagan, que van juntos",
        consejo: "Pon lanceros delante: los caballos no quieren chocar contra las lanzas.",
        avisos: { avaros: "¡Llega otro jinete del kagan desde la llanura!" },
        historia: "Ya somos muchos, Vesna, de todas las tribus. Pero mientras sigamos escondidos entre los árboles, el kagan seguirá mandando en la llanura. Hay que salir. Sus caballos son rápidos, pero nuestras lanzas son largas." },
      { id: 9, nombre: "El Anillo", mapa: "estepa", rivales: 2, batalla: "asalto", ejercito: 18, equipos: [0, 1, 1], guion: [{ id: "maquinas_anillo", cuando: { turno: 4 }, hacer: { refuerzos: { jugador: 0, tropas: ["catapulta", "catapulta"], donde: "borde" }, aviso: "catapultas" } }, { id: "vuelve_kagan", cuando: { turno: 20 }, hacer: { refuerzos: { equipo: 1, tropas: ["caballero", "caballero", "caballero"], donde: "borde" }, aviso: "kagan" } }], enemigos: [{ bando: "avaros", reino: "La guardia del Anillo", capital: "El Anillo" }, { bando: "avaros", reino: "Los jinetes que quedan" }], dificultad: "dificil", limite: 26, premio: { oro: 60 },
        voz: "La abuela Mokosha",
        meta: "Aquí no tienes pueblo: solo tu ejército. Conquista el Anillo, el pueblo principal de su guardia. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "La guardia del Anillo y los jinetes que quedan, que van juntos",
        consejo: "Date prisa: cuanto más tardes, más fácil es que vuelva el kagan con su ejército.",
        avisos: { kagan: "¡El kagan vuelve antes de tiempo con sus jinetes!", catapultas: "Radim llega con dos catapultas para romper las vallas del Anillo." },
        historia: "Los ávaros guardan todo lo que han robado en su gran campamento redondo, el Anillo, rodeado de vallas de madera. El kagan ha salido con su ejército y lo ha dejado con pocos guardias. No volverá a haber una ocasión así, niña. Pero date prisa: el kagan no tardará en volver." },
      { id: 10, nombre: "La primavera", mapa: "llanura_avara", rivales: 2, batalla: "asalto", ejercito: 18, equipos: [0, 1, 1], guion: [{ id: "tribus_final", cuando: { turno: 6 }, hacer: { refuerzos: { tropas: ["espadachin", "arquero", "lancero", "caballero"], donde: "borde", jugador: 0 }, aviso: "tribus" } }, { id: "maquinas_final", cuando: { turno: 9 }, hacer: { refuerzos: { tropas: ["caballero", "catapulta", "catapulta"], donde: "borde", jugador: 0 }, aviso: "maquinas" } }], enemigos: [{ bando: "avaros", capital: "El Gran Campamento" }, { bando: "avaros", reino: "Los jinetes del kagan" }], dificultad: "dificil", limite: 27, premio: { oro: 100, objeto: "manto_primavera" },
        voz: "Bayan, el kagan de los ávaros",
        meta: "Aquí no tienes pueblo: solo tu ejército. Conquista el pueblo principal del kagan Bayan. Tienes {t} turnos. Si se acaban y no lo has conquistado, pierdes.",
        contra: "El kagan Bayan y sus jinetes, que van juntos",
        consejo: "Es la última batalla. El kagan es muy fuerte: no le ataques con un soldado solo.",
        avisos: { tribus: "Llegan guerreros de todas las tribus: un espadachín, un arquero, un lancero y un caballero.", maquinas: "Radim llega con un caballero y dos catapultas para romper la muralla del kagan." },
        jefe: { apodo: "Bayan", reino: "El kagan Bayan", bando: "avaros", clase: "kan", nivel: 10, oro: 1.7, color: "#5a3a2a" },
        historia: "«Así que tú eres la bruja del bosque.» El kagan Bayan te mira desde su caballo, con todo su ejército detrás. «Mis abuelos cobraron tributo a los tuyos, y mis nietos se lo cobrarán a tus nietos. Aquí se acaba tu primavera.»" },
    ] },
};
// La campaña de siempre, con su nombre de siempre (la usan las pruebas y las partidas guardadas de antes).
FWM.datosBase.campana = FWM.datosBase.campanas.castilla.capitulos;

// Batallas de la semana: una batalla histórica por semana, rotando en este orden (lunes a domingo).
// `facciones` (13 sep 2026): con qué facciones se puede jugar esa semana; siempre va una gratis.
// `historia` son las dos frases que se leen antes de jugar; `regla` explica en una línea por qué esta batalla se juega así.
// No son simulaciones históricas: son el mapa hecho a mano que mejor cuenta esa batalla, con las reglas ajustadas.
FWM.datosBase.batallas = [
  { id: "navas", nombre: "Las Navas de Tolosa", anio: 1212, facciones: ["castilla", "saladino"], mapa: "sierra", rivales: 2, dificultad: "dificil", limite: 15,
    historia: "El ejército cristiano llevaba días detenido ante una sierra que nadie sabía cruzar. Un pastor les enseñó un paso escondido y aparecieron al otro lado, a la espalda del campamento almohade.",
    regla: "Dos rivales implacables. Quien controle los puertos de la sierra, gana." },
  { id: "hastings", nombre: "Hastings", anio: 1066, facciones: ["vikingos", "inglaterra"], mapa: "costa", rivales: 1, dificultad: "dificil", limite: 12, hucha: 3,
    historia: "Guillermo cruzó el canal con su ejército mientras Harold luchaba contra los vikingos en la otra punta del reino. Harold volvió agotado, a marchas forzadas, y aun así aguantó todo el día en la colina.",
    regla: "Un solo rival, implacable. Triple oro inicial y 12 turnos: todo se decide de golpe." },
  { id: "granada", nombre: "El cerco de Granada", anio: 1491, facciones: ["castilla", "mali"], mapa: "torres", rivales: 3, dificultad: "dificil", limite: 15,
    historia: "La última ciudad del reino nazarí resistía tras sus torres, con la vega entera para abastecerse. Los sitiadores levantaron un campamento de piedra para demostrar que no pensaban marcharse.",
    regla: "Tres rivales implacables. El centro rico lo decide todo." },
  { id: "stirling", nombre: "El puente de Stirling", anio: 1297, facciones: ["vikingos", "inglaterra"], mapa: "hoz", rivales: 1, dificultad: "dificil", limite: 15,
    historia: "El río solo se cruzaba por un puente de madera por el que pasaban dos jinetes a la vez. Wallace esperó a que la mitad del ejército inglés estuviera al otro lado y entonces bajó de la colina.",
    regla: "Un rival implacable y un río con dos pasos. Elige bien dónde esperas." },
  { id: "paris", nombre: "El sitio de París", anio: 885, facciones: ["vikingos", "mongoles"], mapa: "isla", rivales: 3, dificultad: "normal", limite: 20, hucha: 1,
    historia: "París cabía entera en una isla del Sena, unida a tierra por dos puentes fortificados. Cientos de barcos vikingos remontaron el río en otoño y se quedaron allí casi un año.",
    regla: "Tres rivales, la mitad de oro y 20 turnos: una guerra de aguante." },
];
