// Fichas de reglas para el glosario (las tropas, asentamientos y terrenos se generan solos a partir de sus datos).
// Actualizado el 5 sep 2026 al juego actual: un solo modo (Rápida), solo oro, sin tecnologías ni carreteras,
// reclamar al pisar, el héroe, insignias en el mapa.
window.FWM = window.FWM || {};
FWM.datosBase = FWM.datosBase || {};

FWM.datosBase.glosario = [
  { id: "partida", titulo: "La partida", palabras: "partida rapida turnos puntos ganar",
    texto: "Una partida son 15 turnos (20 en los duelos; la campaña y la batalla de la semana marcan los suyos). Gana quien más puntos tenga al final, o quien elimine a los demás antes. Todo cuesta oro: no hay más recursos. Los puntos se ven arriba, junto al turno." },
  { id: "puntos", titulo: "Los puntos", palabras: "puntos pueblo ciudad castillo hexagono baja heroe oro",
    texto: "Pueblo 10, ciudad 20, castillo 15. Cada hexágono tuyo 1. Cada mina de oro tuya 2. Cada punto clave (estrella) 10. Cada tropa enemiga que matas 2, y el héroe rival 10. Cada tropa tuya viva vale su mantenimiento. 1 punto por cada 10 de oro que tengas al acabar." },
  { id: "turno", titulo: "El turno", palabras: "turno orden fin ingresos",
    texto: "Al empezar tu turno cobras el oro de tus asentamientos y minas, pagas el mantenimiento de las tropas, se curan las que descansaron y se reparan las murallas que nadie atacó. Luego mueves y actúas con cada tropa y pulsas Fin de turno. Deshacer devuelve un movimiento; los ataques no se deshacen." },
  { id: "mover", titulo: "Mover y actuar", palabras: "mover movimiento accion paso reclamar",
    texto: "Toca una tropa tuya: los hexágonos claros son adonde puede ir, los rojos a quién puede atacar, los naranjas qué puede asediar. Cada tropa tiene puntos de movimiento (2 la mayoría, 4 la caballería) y una acción por turno. Llanura cuesta 2, bosque y colina 4; mientras quede algún punto se puede dar un paso más. Pisar un hexágono lo hace tuyo, también los puntos clave: mover ya conquista territorio." },
  { id: "insignias", titulo: "Las insignias del mapa", palabras: "insignia escudo martillos x info flecha reclutar",
    texto: "Al seleccionar una tropa tuya salen sus insignias a la derecha: el escudo la atrinchera (+10 de defensa hasta que se mueva), los martillos (solo campesinos) abren Pueblo y Castillo, la X roja la licencia y la i abre su ficha completa. En tus asentamientos: los martillos abajo a la izquierda abren la lista de tropas para reclutar, el círculo abajo a la derecha es la guarnición (tócalo para elegir una tropa de dentro) y la flecha azul arriba a la derecha mejora el pueblo a ciudad si tienes oro. Tocar el asentamiento en cualquier otro sitio abre su ficha." },
  { id: "heroe", titulo: "Tu héroe", palabras: "heroe aura nivel mejora punto morir",
    texto: "Tu héroe va a cada partida como una tropa más, empieza en tu capital y no cuesta mantenimiento. Es de una de cuatro clases (espadachín, arquero, nórdico, alquimista), cada una con su rasgo, y su aura mejora a las tropas pegadas a él cuando está en campo abierto. Si muere, no vuelve en esa partida (salvo que lleve una pócima) y el rival gana 10 puntos. Fuera de la partida sube de nivel con los puntos que acumulas: cada peldaño da un punto de mejora que gastas en su ficha; cada nivel abre una unidad nueva. Los objetos que consigues se equipan en su ficha." },
  { id: "terreno", titulo: "Terreno", palabras: "terreno colina bosque montaña llanura defensa",
    texto: "Bosques y colinas cuestan el doble y dan +10 de defensa a quien está encima. Desde una colina, los arqueros disparan un hexágono más lejos. Las montañas no se cruzan. Las tropas acuarteladas no reciben el bono del terreno: ya tienen el de las murallas." },
  { id: "solo_oro", titulo: "Minas y puntos clave", palabras: "oro mina puntos clave estrella",
    texto: "Las minas de oro (moneda) dan 1 oro por turno si están unidas por hexágonos tuyos a un asentamiento tuyo; una tropa enemiga encima las para. Los puntos clave (estrella) no producen nada pero valen 10 puntos al final para quien los tenga en ese momento: lo mismo que un pueblo entero. Pisarlos basta para hacerlos tuyos." },
  { id: "dano", titulo: "Cómo se calcula el daño", palabras: "daño ataque defensa combate golpe contraataque",
    texto: "Daño = ataque − defensa, mínimo 10. Antes de atacar ves lo que harás y lo que recibirás. Si el defensor sobrevive y el atacante era cuerpo a cuerpo, contraataca con la misma regla. Arqueros, ballesteros y catapultas atacan a distancia sin recibir contraataque. Las máquinas (catapulta, trabuco) no contraatacan nunca." },
  { id: "dado", titulo: "El dado", palabras: "dado azar suerte certero flojo",
    texto: "Cada golpe tira un dado escondido: dos de cada tres golpes son exactos; uno de cada seis hace 10 más (certero) y uno de cada seis 10 menos (flojo)." },
  { id: "heridas", titulo: "Heridas y curación", palabras: "herida vida ataque curar descansar",
    texto: "Una tropa herida pega más flojo: su ataque real es el ataque por la vida que le queda. Una tropa que no hace nada en el turno recupera 10 de vida si está en territorio propio y 20 dentro de un asentamiento. El monje cura 10 a las tropas pegadas a él al acabar tu turno." },
  { id: "triangulo", titulo: "Espada, lanza y caballo", palabras: "espadachin lancero caballero bonus contra triangulo",
    texto: "El espadachín gana al lancero (+15: se cuela dentro de las picas). El lancero gana al caballero (+15: muro de lanzas). El caballero gana al espadachín (+15: la carga). El espadachín para flechas con la rodela (+10 de defensa contra tropas a distancia). El alabardero lleva lanza pero el espadachín no tiene bono contra él. Los arqueros desgastan a todos y mueren si les alcanza cualquiera." },
  { id: "avanzar", titulo: "Avanzar al matar", palabras: "matar avanzar ocupar hexagono salida",
    texto: "Cuando una tropa cuerpo a cuerpo mata a otra, avanza al hexágono del muerto y lo hace tuyo, también si atacaba desde dentro de un asentamiento (salida). Los tiradores no avanzan. Si el muerto era el último de una guarnición y las murallas están a cero, el atacante entra y conquista el asentamiento; si siguen en pie, se queda fuera." },
  { id: "guarnicion", titulo: "Guarnición", palabras: "guarnicion acuartelar hueco asentamiento defender",
    texto: "Un asentamiento no se defiende solo: tiene huecos de guarnición (1 el pueblo, más la ciudad y el castillo). Mueve una tropa dentro para acuartelarla: gana el plus de defensa de las murallas y paga la mitad de mantenimiento. Los tiradores disparan desde dentro sin exponerse; los cuerpo a cuerpo pueden hacer una salida (sin el plus en ese golpe). Sin guarnición y con brecha, el enemigo entra andando. Una tropa reclutada entra en un hueco libre o nace al lado." },
  { id: "murallas", titulo: "Murallas y asedio", palabras: "muralla asedio brecha integridad catapulta",
    texto: "Las murallas son la integridad del asentamiento (arriba a la izquierda de su hexágono). Mientras estén en pie, la guarnición tiene el plus de defensa. Asediar las golpea: la catapulta desde lejos y sin exponerse (y de paso hiere a la guarnición); la infantería con escaleras, despacio y recibiendo contraataque. A 0 hay brecha." },
  { id: "conquista", titulo: "Conquistar", palabras: "conquistar tomar asentamiento ciudad castillo",
    texto: "Para tomar un asentamiento: mata a toda su guarnición, deja las murallas a cero y entra. Si un cuerpo a cuerpo mata al último defensor con brecha abierta, entra en el mismo golpe. Una ciudad tomada baja a pueblo; un castillo sigue siendo castillo. Los castillos los construye un campesino en un hexágono tuyo (martillos de su insignia), nunca a menos de 2 hexágonos de un asentamiento enemigo." },
  { id: "fundar", titulo: "Fundar un pueblo", palabras: "fundar pueblo campesino expandir ciudad mejorar",
    texto: "Un campesino en un hexágono tuyo, a tres o más hexágonos de cualquier asentamiento, funda un pueblo por 20 oro (martillos de su insignia); el campesino desaparece. Un pueblo se mejora a ciudad por 40 oro con la flecha azul: más guarnición, más murallas y recluta de todo. Los pueblos solo reclutan campesinos." },
  { id: "experiencia", titulo: "Experiencia", palabras: "experiencia veterano elite nivel galones",
    texto: "Cada combate sobrevivido da un punto de experiencia; matar da dos más. Con 3 puntos la tropa es Veterana (+5 ataque, +5 defensa); con 8, Élite (+10 y +10). Se ve como galones. El héroe no gana galones: su progreso es el de fuera de la partida." },
  { id: "mantenimiento", titulo: "Mantenimiento y bancarrota", palabras: "mantenimiento bancarrota oro pagar desertar licenciar",
    texto: "Cada tropa cuesta oro por turno (la mitad si está acuartelada). Al dar Fin de turno el juego avisa si el turno siguiente no vas a poder pagar. Si no puedes, desertan tropas empezando por las más baratas. Puedes licenciar tropas con la X roja de su insignia, sin reembolso." },
  { id: "victoria", titulo: "Victoria y eliminación", palabras: "victoria ganar eliminar perder abandono",
    texto: "Al último turno gana quien más puntos tenga; antes, gana quien elimine a los demás. Un reino está eliminado cuando no tiene asentamientos ni tropas. En los duelos online hay 60 segundos por turno; tres turnos sin tocar nada o 30 segundos desconectado es abandono." },
  { id: "dificultad", titulo: "Fácil, normal y difícil", palabras: "dificultad facil normal dificil implacable rivales",
    texto: "Fácil: rivales torpes, para aprender. Normal: rivales con criterio, cada uno con su carácter (guardián, expansionista, belicoso…). Difícil: rivales implacables que van a por ti, cazan a tu héroe si lo ven herido, pisan cada mina y punto clave y empiezan con un 25 % más de oro." },
  { id: "fuera", titulo: "Fuera de la partida", palabras: "misiones medallas objetos tienda ranking duelo liga campana batalla racha",
    texto: "Al acabar sumas puntos (ranking y nivel del héroe) y oro del héroe (para la tienda de objetos). Hay tres misiones al día y dos a la semana, racha de días jugados, medallas con premio, mapa del día (el mismo para todos), campaña de diez mapas hechos a mano con premio, batalla de la semana (un mapa con reglas propias que cambia el lunes, con su ranking), duelos online con Elo y liga semanal, y retos a amigos por código." },
];
