// English interface texts (6 sep 2026). Same keys as textos.es.js; anything missing falls back to Spanish.
window.FWM = window.FWM || {};
FWM.textos = FWM.textos || {};

FWM.textos.en = {
  titulo: "Final War: Medieval",
  turno: "Turn",
  finTurno: "End turn",
  deshacer: "Undo",
  tecnologia: "Technology",
  nuevaPartida: "New game",
  menu: "Menu",
  inicioPartida: "Game start",
  jugar: "Play",
  ranking: "Leaderboard",
  misiones: { titulo: "Quests", deHoy: "Today's quests", hechas: "{n} of 3 done", mision: "Quest", premio: "Reward (gold)", de: "of", semanal: "week", cumplida: "Quest complete", cumplidaUna: "quest complete", cumplidas: "quests complete" },
  globos: ["This is you: your hero. He starts in your capital.", "Tap a highlighted hex to move a troop; red ones are for attacking.", "When you're done, press End turn."],
  medallaMas: "and {n} more medal(s): see them in Hero → Awards",
  bienvenida: {
    elige: "Choose your hero", eligePista: "He goes with you into every game and grows with everything you win. You can only have one.",
    lemas: { espadachin: "Holds the line", arquero: "Strikes from afar", nordico: "Hits hardest", alquimista: "Burns and heals" },
    esteEsElMio: "This one's mine", nombre: "What's your name?", nombreEjemplo: "Your name", seguir: "Continue",
    primerPunto: "You have 1 upgrade point", primerPuntoPista: "Pick an upgrade. Every game you play will earn you more.",
    cuenta: "Shall we save your hero?", cuentaPista: "Without an account your hero lives only on this device. With one, you appear on the leaderboard and never lose him.",
    listo: "All set, {nombre}.",
    alMenu: "Go to the menu",
  },
  heroeUI: {
    boton: "Hero", titulo: "Your hero", nivel: "Level", unidadPronto: "new unit (soon)", unidadFutura: { infanteria_pesada: "Heavy infantry (soon)", caballeria_pesada: "Heavy cavalry (soon)", trabuco: "Trebuchet (soon)" }, puntosMejora: "Upgrade points", sinGastar: "{n} unspent", gastar: "Upgrade", tope: "Maxed out", requiere: "Requires {que}",
    siguienteNivel: "Next level: {nombre} at {n} points", siguientePunto: "Next upgrade point at {n} points", cima: "At the top",
    elegirClase: "Choose hero", clase: "Class", cambiarClase: "Change hero", familia: { heroe: "The hero", aura: "Aura (troops next to the hero)", reino: "Realm", aspecto: "Looks" },
    explicacion: "Your hero joins every game as one more troop. He grows with the points you pile up: each step gives an upgrade point, and each level unlocks a new unit.",
    mejoras: "Upgrades", elegir: "Choose", niveles: "Levels", logros: "Awards", masAdelante: "Later on", disponibles: "to choose", nadaDeEsteTipo: "You don't have any of this kind yet.", tiendaPista: "Paid with hero gold: you earn it by finishing games, and from medals and quests.", noSeVenden: "Not for sale: here's how they drop",
    desbloquea: "Unlocks", nada: "—", sinCuenta: "Your hero lives only on this device. Create an account so you don't lose him.", muerto: "Your hero has fallen. He won't return this game.",
    puntoMejora: "upgrade point", puntoNuevo: "Upgrade point!", puntosNuevos: "{n} upgrade points!", nivelNuevo: "New level!", desbloqueado: "Unlocked", mejorarAhora: "Upgrade now", luego: "Later", adelante: "Let's go!",
    leyenda: "The Legend: the Emperor with the most points of all. There can only be one.",
    oroHeroe: "hero gold", oroCorto: "gold", botin: "Loot!", botinRepetido: "you already had every drop: {n} gold instead",
    objetos: "Items", tienda: "Shop", inventario: "Bag", equipado: "Equipped", equipar: "Equip", quitar: "Remove", comprar: "Buy", oro: "Hero gold", precio: "{n} gold",
    tipos: { arma: "Weapon", escudo: "Shield", montura: "Mount", cabeza: "Head", consumible: "Consumable", aspecto: "Looks" }, vacio: "Empty", nadaInventario: "No items yet. They drop when you finish games, come with medals, and are sold in the shop.",
    comoSale: { tienda: "Shop: {n} gold", botin: "Loot at the end of a game", medalla: "{nombre} medal ({nivel})", campana: "Campaign, map {n}", liga: "Weekly league, {n}" },
  },
  duelo: {
    boton: "Online duel", titulo: "Online duel",
    explicacion: "One against one, live. A quick game of 20 turns with 60 seconds per turn.",
    buscarRival: "Find an opponent", retar: "Challenge a friend", tengoCodigo: "I have a code", entrar: "Join",
    buscando: "Looking for an opponent… {s} s", esperandoAmigo: "Give this code to your friend. When they type it in, you start.", entrando: "Joining the challenge…",
    codigo: "Code", rivalEncontrado: "Opponent found! {nombre}", necesitaCuenta: "Duels need an account (it's your name on the leaderboard).",
    rivalDesconectado: "Your opponent dropped out. They have {s} s to come back.", desincronizada: "The two games don't match: duel void, it doesn't count.",
    anulada: "Duel void", abandono: "opponent forfeited", rendicion: "you resigned", rendirse: "Resign", confirmarRendirse: "Resign? Your opponent wins the duel.",
    conAmigo: "Play with a friend", igualar: "Even out heroes", comoEstan: "As they are", igualarPista: "Even out: both play at the lower hero level, with no items. Worth it if one of you is far ahead.",
    rankingDuelos: "Duels", elo: "Elo", liga: "League of the week", ligaPista: "Elo gained since Monday. When the week closes: 1st Greatsword, 2nd Aegis, 3rd 150 hero gold.", historial: "Your latest duels", revancha: "Rematch", sinDuelos: "No duels yet.",
    teReta: "{nombre} challenges you to a duel", aceptarReto: "Accept", retoEnviado: "Challenge sent to {nombre}. If they're online they'll join now; if not, they'll see it when they open the game.", eloCambio: "Elo {antes} → {despues}",
    ligaPremio: "Last week's league! You finished {pos}: {premio}", ganaste: "won", perdiste: "lost", marca: "Record against {nombre}: {g}-{p}",
    chat: { boton: "Chat", invitar: "{nombre} wants to chat with you.", aceptar: "Accept", no: "No", pedido: "Invitation sent. If {nombre} accepts, the chat opens.", rechazado: "{nombre} doesn't want to chat.", aceptado: "{nombre} accepted the chat.", escribe: "Type…", enviar: "Send", cerrar: "Close", frases: ["Good game!", "Take that!", "Ouch…", "Well played", "GG", "👍", "😅", "⚔️"] },
    otraVersion: "Your opponent is on a different version of the game. Both of you should close it and open it again to update.",
    otraVersionCola: "Someone is searching, but on a different version of the game. Ask them to close it and open it again.",
    tuTurno: "Your turn! Turn {n}", marcador: "Score", yo: "You", vas: "you're", primero: "1st", segundo: "2nd", empate: "tied",
    turnoDe: "{nombre}'s turn", preparado: "Ready!", esperandoRival: "Waiting for {nombre}…", empiezaEn: "Starts in {s} s", listo: "Ready", enCurso: "You're in a live duel. If you leave, your opponent wins.", volverPartida: "Back to the game", abandonoPropio: "you forfeited (three turns without playing)", ultimoAviso: "One more turn doing nothing and you lose by forfeit.", reglasLinea: "{turnos} turns · {s} s per turn · gold only · most points wins", tiempoAgotado: "Time's up: turn ended.", sinRed: "No connection to the cloud.",
  },
  comoSeJuega: "Glossary",
  ajustes: "Settings",
  volverInicio: "Home",
  volver: "Back",
  hola: "Hello, {nombre}",
  nombreJugador: "Your name",
  nombrePista: "For the leaderboard. You can change it whenever you like.",
  bandoFavorito: "Favourite realm",
  marcador: "Your score",
  historial: "Latest games",
  sinPartidas: "You haven't played a game yet.",
  rankingOnlinePronto: "The leaderboard with other players is coming with the online version.",
  ganada: "won",
  perdida: "lost",
  subtitulo: "War on hexagons. A game fits in a coffee break.",
  cuenta: "Account",
  instalar: "Install on your phone",
  instalarIos: "To install it: press Share and then \"Add to Home Screen\".",
  instalado: "Installed. Open it from your home screen.",
  crearCuenta: "Create account",
  crearCuentaOEntrar: "Create account or sign in",
  cuentaReclamo: "Want to be on the leaderboard?",
  entrar: "Sign in",
  salir: "Sign out",
  correo: "Email",
  clave: "Password",
  olvideClave: "I forgot my password",
  claveEnviada: "We've sent you an email to change it.",
  seguirSinCuenta: "Continue without an account",
  paraRanking: "To appear on the leaderboard with other players, create an account or sign in. Playing doesn't need one.",
  yaTengoCuenta: "I already have an account",
  noTengoCuenta: "I don't have an account",
  conectadoComo: "Signed in as",
  rankingSemana: "Week",
  rankingTotal: "All time",
  rankingHoy: "Today",
  rankingMejor: "Best game",
  rankingDia: "Daily map",
  dueloEnCurso: "Duel in progress", dueloVolver: "Back to the duel", dueloRelojSigue: "The clock is still running: your opponent is waiting.",
  rankingDiaPista: "Best game on today's map. Same map for everyone; it changes at midnight.",
  mapaDelDia: "Daily map",
  mapaDelDiaPista: "The same map for everyone today. Your best game goes on the daily leaderboard.",
  diasSeguidos: "{n} days in a row",
  rachaDias: { dias: "Streak: {n} days in a row", uno: "Streak: 1 day", hoy: "play today to keep it", hecha: "today already counts", empieza: "Play a game today and start your streak", nuevoDia: "New day: new quests and a new daily map." },
  dificil: "Hard",
  dificultadPista: { facil: "Clumsy opponents: for learning.", normal: "Opponents with a plan, each with its own character.", dificil: "Relentless opponents: they come for you, hunt your hero, grab every key point and start with 25% more gold." },
  escenarios: { boton: "Grand battles", titulo: "Grand battles", pista: "Large historical maps: every realm starts in its own land. Same rules, far more room and many more turns.", jugar: "Play the scenario", reinos: "{n} realms", turnos: "{n} turns", tuBando: "Your realm", bandoPista: "Your realm decides where you start.", aviso: "Geography inspired by the real thing: sea channels are closed with land bridges because there are no ships here." },
  barbaros: { boton: "Barbarians", titulo: "Barbarian mode", pista: "You start alone in the middle of the valley. From the third round, hordes come in from the edges, more of them and from more sides each time. Hold out as long as you can.", jugar: "Hold out", ronda: "Round", llegaOleada: "Wave of {n} barbarians! Round {ronda}", aguantaste: "You held out {n} rounds", record: "Your record: {n} rounds", nuevoRecord: "New record: {n} rounds!", sinRecord: "You haven't held out yet.", ranking: "Barbarians", rankingPista: "Rounds survived in Barbarian mode. Next to each player, their hero's level.", proxima: "Next wave: round {ronda}, from {lados} side(s)", consejo: "Tip: keep troops in the garrison and don't wander into the open without a reason." },
  campana: { boton: "Campaign", titulo: "Campaign", pista: "Ten hand-made maps, each harder than the last. Every map you beat pays its reward once.", progreso: "{n} of {t} maps beaten", mapa: "Map {n}", jugar: "Play", repetir: "Replay", bloqueado: "Beat the previous map", superado: "Beaten", premio: "Reward", superadoCer: "Campaign: map {n} beaten", completa: "Campaign complete. Well done!", rivales: "{n} opponent(s) · {d} · {t} turns" },
  batalla: { boton: "Weekly battle", titulo: "Battle of the week", noEsSimulacion: "A map inspired by the battle, not an exact recreation.", pista: "A hand-made map with its own rules. It changes every Monday; your best game goes on the week's leaderboard.", ranking: "Battle", rankingPista: "Best game in this week's battle. It changes on Monday.", cambia: "Changes in {n} days", cambiaManana: "Changes tomorrow", tuSemana: "This week: {n} game(s) · best {m} points", sinJugar: "You haven't played it this week.", jugar: "Play the battle", verRanking: "See leaderboard", mejorSemana: "Battle of the week: best {n}", reglas: "Rules" },
  medallas: "Medals",
  conectado: "Online",
  cambiarFigura: "Change figure",
  tuFigura: "Your figure",
  escalonAspirante: "Recruit",
  medallaNueva: "New medal",
  posiciones: ["First", "Second", "Third", "Fourth", "Fifth", "Sixth", "Seventh", "Eighth"],
  tuTotal: "Your total",
  verResumen: "See summary",
  repeticion: { boton: "Watch replay", titulo: "Replay", turnos: "{n} turns saved", reproducir: "▶ Play", pausa: "❚❚ Pause" },
  compartir: { boton: "Share", titulo: "Your game", texto: "{puntos} points on {mapa}. Final War: Medieval.", guardar: "Press and hold the image to save or copy it.", descargar: "Download" },
  medallasPista: "{n} of {total}",
  nivelesMedalla: ["Bronze", "Silver", "Gold"],
  siguienteObjetivo: "Next",
  nivelMaximo: "Top level",
  rankingSumaPista: "The points from all your games added up.",
  rankingMejorPista: "Your best score in a single game.",
  tuPosicion: "Your position",
  sinRanking: "No games on the leaderboard yet. Be the first!",
  nubeCargando: "Connecting to the cloud…",
  sinConexion: "No connection to the leaderboard. Your points are kept on the device and will be sent when you're online.",
  guardarEnRanking: "Save to the leaderboard",
  enviadoRanking: "Sent to the leaderboard",
  pendienteRanking: "It will be sent to the leaderboard when you sign in",
  errCorreoUsado: "That email already has an account. Try signing in.",
  errCredenciales: "Wrong email or password.",
  errClaveCorta: "The password needs at least 6 characters.",
  errCorreo: "That email doesn't look valid.",
  errDemasiado: "Too many attempts. Wait a minute.",
  errRed: "No connection. Try again later.",
  errNombre: "Use a name of 2 to 20 letters.",
  iaEtiqueta: "AI",
  iaUltimaPartida: "Players marked AI are your opponents from the last game.",
  escalon: "Step",
  escalones: [[100, "Recruit"], [250, "Veteran"], [400, "Elite"], [600, "Legend"]],
  teFaltan: "{n} points to go until {nombre}.",
  tutorial: "Tutorial",
  saltarTutorial: "Skip", minimizar: "Minimise", maximizar: "Show again",
  entendido: "Got it!",
  primeraVez: "First time? The tutorial is three minutes of playing.",
  jugarDirecto: "Play straight away",
  tutorialPasos: {
    seleccionar: "This is your village: the star marks it as your capital. Your hero is inside. Tap the little circle the arrow points at (the garrison, 1/1) to bring him out.",
    mover: "The highlighted hexes are where he can go. Tap the one the arrow points at: stepping on a hex makes it yours, and coins (mines) and stars (key points) are worth points.",
    finTurno: "Every turn your realm collects gold (top left). Press End turn, where the arrow points, to watch your opponent play.",
    reclutar: "Tap the hammers the arrow points at and pick a peasant: 10 gold. Soldiers are only recruited in cities and castles.",
    explorar: "Send troops to the mines and stars the arrow points at: they're worth points at the end. With 40 gold, the blue arrow on the village turns it into a city. Play a few turns.",
    atacar: "Attack: select a troop and tap the enemy the arrow points at (enemies you can attack are marked in red). You'll see the damage before confirming. Melee gets a counterattack; archers shoot without taking one. Look after your hero: if he dies, he's gone.",
    final: "To take an enemy village: kill the garrison, bring the walls to zero (siege) and walk in. Whoever has the most points on turn 15 wins, or whoever wipes out the rest. Good luck!",
  },
  jugador: "Player",
  tu: "Your realm",
  ia: "AI",
  hexagono: "Hex",
  hexagonos: "Hexes",
  heroesMatados: "Heroes slain",
  verDetalle: "See details", sano: "unhurt", detalleCorto: "more", fundarCorto: "Village", atrincherarCorto: "Dig in", licenciarCorto: "Disband", reclutarCorto: "Recruit", lineaVacia: "Tap a troop or a village to see what it can do.", sinDueno: "Unclaimed", iasJugando: "Your opponents are playing…",
  oroDisponible: "You have {n} gold.",
  confirmarCiudad: "Upgrade to a city for {n} gold? More garrison, stronger walls and it recruits everything.",
  rapidaResumen: "Quick game: {n} turns, gold only. Most points wins.",
  heroe: "Hero",
  nadie: "Unclaimed",
  de: "of",
  vida: "Health",
  ataque: "Attack",
  defensa: "Defence",
  asedio: "Siege",
  alcance: "Range",
  movimiento: "Movement",
  mantenimiento: "Upkeep",
  coste: "Cost",
  produce: "Produces",
  murallas: "Walls",
  capital: "Capital",
  aislado: "Cut off",
  almacen: "Store",
  guarnicion: "Garrison",
  construcciones: "Buildings",
  vacio: "empty",
  reclutar: "Recruit",
  mejorarTropa: "Upgrade troop",
  mejorarACiudad: "Upgrade to city",
  construirCastillo: "Build castle",
  reclamar: "Claim",
  fundar: "Found",
  castillo: "Castle",
  fundarPueblo: "Found village",
  salir: "Sign out",
  atrincherar: "Dig in",
  atrincherada: "Dug in",
  irA: "Go to…",
  irAPista: "Tap the destination hex. The troop will head there on its own each turn.",
  destino: "Destination",
  cancelarDestino: "Cancel destination",
  enemigoCerca: "stops: enemy nearby",
  siguienteTropa: "Next troop",
  tropasPendientes: "You have {n} troop(s) that can still act.",
  verTropa: "See troop",
  terminarIgual: "End anyway",
  reino: "Realm",
  tesoro: "Treasury",
  hucha: "You have",
  entraPorTurno: "Income",
  salePorTurno: "Spending",
  balance: "Balance",
  recurso: "Resource",
  enCurso: "in progress",
  hechas: "done",
  cadaUno: "at {n} each",
  neto: "Net",
  porQue: "why",
  sinIngresos: "None",
  yacimientosParados: "Resources not producing",
  zonasAisladas: "Cut-off areas",
  asentamientos: "Settlements",
  tropas: "Troops",
  tecnologias: "Technologies",
  tuReinoEs: "You are {reino}, the {color} realm. Your capital: {capital}.",
  idioma: "Language", idiomaAviso: "The game will reload to change the language.",
  fichas: {
    mantenimientoCorto: "upkeep",
    sinGuarnicion: "No garrison: if they breach the walls, the enemy walks straight in.", sinGuarnicionBrecha: "No garrison and a breach: the enemy walks straight in.",
    sinInvestigarNada: "You're not researching anything.", esTecnologia: "{nombre} (technology)", delHeroe: " hero",
    nombresAsent: "Settlement names", cuerpoACuerpo: "melee", seReclutaEn: "Recruited in", mejoraA: "Upgrades to", especial: "Special",
    puedeFundar: "Can found villages", noMoverDisparar: "Can't move and shoot in the same turn", comoSeConsigue: "How you get it",
    loFunda: "Founded by a peasant", mejorando: "By upgrading a {que}", seConstruye: "Built on an empty hex of yours",
    huecosGuarnicion: "Garrison slots", plusDefensa: "Defence bonus", reclutaFicha: "Recruits", todasLasTropas: "Every troop",
    mejoraTropas: "Upgrades troops", si: "Yes", no: "No", alConquistarlo: "When captured", pasaA: "Becomes a {que}", tarda: "Takes", desbloquea: "Unlocks",
    mover: "Movement", noSePuede: "impassable", puntosPasos: "{p} points ({n} {pasos})", sePuedeConstruir: "Can be built on",
    carreteraDesc: "Built by a peasant on a hex of yours. Entering costs {n} point. Settlements count as roads.",
    aLaGuarnicion: "to the garrison", brechaSinPlus: "breached: no bonus", pistaMover: "Tap a highlighted hex to move, a red one to attack, an orange one to besiege.",
    noProduce: "Not producing: it isn't connected to a settlement.", tuMayus: "You" },
  legal: "Legal", verPrivacidad: "Privacy policy", verCondiciones: "Terms of use", version: "Version",
  borrarCuenta: "Delete my account", borrarCuentaAviso: "This deletes your account, your hero, your scores and your duels. It can't be undone and it can't be recovered.", borrarCuentaConfirmar: "Are you sure you want to delete your account and all your progress?", borrarCuentaHecho: "Account deleted. Your progress on this device is still here.", borrarCuentaError: "It couldn't be deleted. Write to {contacto} and we'll delete it by hand.",
  aceptasAlCrear: "By creating an account you accept the {condiciones} and the {privacidad}.",
  paleta: "Colours", paletaNormal: "Normal", paletaDaltonicos: "Colour-blind friendly", paletaPista: "Swaps the realm colours for ones that can be told apart without seeing red and green well.",
  colorAzul: "blue",
  colorRojo: "red",
  tuSufijo: "(you)",
  tuCapital: "Your capital",
  mapaNumero: "Map no.",
  mapa: "Map",
  mapaAleatorio: "Random",
  avanzado: "Advanced",
  puedeMoverse: "Can move ({n})",
  contraGuarnicion: "Against the garrison",
  contraMurallas: "Against the walls",
  sinContraataque: "no counterattack",
  quitas: "You take off",
  explicaAtaque: "Attacking the garrison hits the troop inside (protected by the walls while they stand). Besieging hits the walls.",
  glosario: "Glossary",
  carretera: "Road",
  construirCarretera: "Build road",
  terreno: "Terrain",
  pasos: "steps",
  conCarretera: "with a road",
  experiencia: "Experience",
  salida: "Sally: attacks from inside without the wall bonus in this exchange. If it kills, it moves out onto the hex.",
  personalidades: { equilibrada: "balanced", guardiana: "guardian", expansionista: "expansionist", belicosa: "warlike", implacable: "relentless" },
  sobre: "About",
  sinInvestigar: "You're not researching anything. You could start {tec} ({coste}).",
  verTecnologias: "See technologies",
  buscar: "Search…",
  pestanas: { bandos: "Realms", tropas: "Troops", asentamientos: "Settlements", tecnologias: "Technologies", recursos: "Resources", terrenos: "Terrain", reglas: "Rules" },
  verEnGlosario: "See in the glossary",
  licenciar: "Disband",
  deserta: "deserts",
  bancarrotaAviso: "Bankrupt! {n} troops desert for lack of gold.",
  bancarrotaAvisoUna: "Bankrupt! {tropa} deserts for lack of gold.",
  bancarrotaFin: "Bankruptcy ahead: next turn you'll be {oro} gold short and {n} troops will desert (the cheapest first). Disband troops or get gold.",
  verReino: "See realm",
  licenciarConfirmar: "Disband this troop? You get nothing back.",
  ingresos: "Income",
  gastos: "Spending",
  porTurno: "per turn",
  atacar: "Attack",
  asediar: "Besiege",
  atacarGuarnicion: "Attack garrison",
  cancelar: "Cancel",
  confirmar: "Confirm",
  haces: "You deal",
  recibes: "You take",
  hiciste: "You dealt",
  recibiste: "You took",
  a: "to",
  yaActuo: "Already acted",
  sinMovimiento: "No movement left",
  puedeActuar: "Can act",
  investigando: "Researching",
  investigar: "Research",
  investigado: "Researched",
  turnos: "turns",
  requiere: "Requires",
  disponible: "Available",
  bloqueado: "Locked",
  nada: "None",
  cerrar: "Close",
  ganaste: "You won!",
  perdiste: "You've been wiped out.",
  gano: "won the game.",
  eliminado: "wiped out",
  jugadores: "Opponents",
  empezar: "Start game",
  continuar: "Continue game",
  tamanoMapa: "Map size",
  dificultad: "Difficulty",
  tipoPartida: "Game type",
  tuBando: "Your realm",
  bando: "Realm",
  bandoAleatorio: "Random",
  bandoAleatorioPista: "You get a random realm. Each one has its own trait; see them in the glossary.",
  limiteTurnos: "Turns", finPartida: "End of the game", finPuntos: "On points", finEliminacion: "Last one standing",
  finPuntosPista: "When turn {n} ends, whoever has the most points wins. Before that, whoever wipes out the rest.",
  finEliminacionPista: "No turn limit: you play until only one realm is left. It can take a long time.",
  sinLimite: "No limit",
  puntos: "Points",
  victoriaPorPuntos: "on points when the turn limit was reached",
  rasgo: "Trait",
  bonoContra: "+{n}: {atacante} against {etiqueta}",
  defensaContraTxt: "+{n} defence for {defensor} against {etiqueta}",
  defensaContra: "Defence against",
  bonusContra: "Bonus against",
  etiquetasNombre: { lanza: "spears", espada: "swords", montada: "cavalry", armadura: "armour", a_pie: "infantry", a_distancia: "ranged troops", ligera: "light troops", maquina: "war machines" },
  tipos: { rapida: "Quick", normal: "Slow", personalizada: "Custom", dia: "Daily map", duelo: "Duel", campana: "Campaign", batalla: "Weekly battle", escenario: "Grand battle", barbaros: "Barbarians" },
  conquistas: "Conquests",
  matadas: "Kills",
  perdidas: "Losses",
  oroGanado: "Gold earned",
  lineaTiempo: "Settlements per turn",
  records: "Records",
  partidas: "games",
  ganadas: "won",
  racha: "streak",
  mejorRacha: "best",
  mejorVictoria: "fastest win",
  puntosHoy: "today",
  puntosSemana: "this week",
  puntosTotal: "all time",
  mejorPartida: "best game",
  revancha: "Rematch (same map)",
  otraPartida: "Another game",
  rapida: "Quick",
  normalPartida: "Slow",
  personalizada: "Custom",
  opcionesPersonalizadas: "size, technology, treasury, resources, map",
  huchaInicial: "Starting treasury",
  huchaNormal: "Normal",
  huchaDoble: "Double",
  huchaTriple: "Triple",
  arbolCompleto: "Full tree (researched)",
  todoDesbloqueado: "Everything unlocked (quick game)",
  recursosMapa: "Resources",
  equilibrados: "Balanced (the same near every capital)",
  aleatorios: "Random",
  facil: "Easy",
  normal: "Normal",
  pequeno: "Small",
  mediano: "Medium",
  grande: "Large",
  semilla: "Seed",
  registro: "Log",
  ayuda: "Help",
  ayudaTexto: [
    "Tap one of your troops to see where it can go and who it can attack.",
    "Stepping on a hex makes it yours.",
    "Mines produce if they're connected to a settlement of yours.",
    "A peasant can found a village on an empty hex of yours.",
    "Put troops inside your settlements: with no garrison and the walls at zero, the enemy just walks in.",
    "Catapults break walls. Infantry can too, but very slowly.",
    "If you can't pay the upkeep, troops desert until you can.",
  ],
  errores: {
    sin_accion: "That troop has already acted this turn. Pick another one or end the turn.",
    sin_movimiento: "It can't move any further this turn. End the turn and it will move again.",
    no_es_tuya: "It isn't yours.",
    hex_ocupado: "That hex is occupied.",
    fuera_de_alcance: "Too far: get one hex closer.",
    sin_recursos: "You're short of gold. End the turn to collect, or disband a troop.",
    sin_tecnologia: "You're missing a technology.",
    nivel_heroe: "Your hero isn't high enough level for this unit yet.",
    sin_oro: "You don't have enough hero gold.", ya_tienes: "You already have it.", no_se_vende: "Not for sale.", no_tienes: "You don't have it.", sin_puntos: "You have no upgrade points.", tope: "Already maxed out.", requiere: "Another upgrade comes first.",
    sin_hueco: "No room: the garrison is full and the hexes around it are taken. Move a troop out.",
    ya_reclutado: "It already recruited this turn. It can again next turn.",
    demasiado_cerca: "Too close to another settlement.",
    no_puede_fundar: "This troop can't found settlements.",
    ya_es_tuyo: "It's already yours.",
    no_desde_dentro: "Melee troops have to step out to attack.",
    catapulta_movida: "A catapult can't move and shoot in the same turn.",
    no_hay_objetivo: "No target.",
    ya_investigando: "You're already researching something.",
    ya_atrincherada: "It's already dug in.",
    ya_hay_carretera: "There's already a road.",
    no_aqui: "Only in {donde}.",
    no_se_puede: "Can't be done.",
    hex_no_tuyo: "The hex isn't yours: step on it first.",
    terreno_no_construible: "You can't build on this terrain.",
    solo_acuartelada: "Only inside a city: put it in the garrison.",
    solo_en_ciudad: "Only in a city, not in {tipo}.",
    no_se_atrinchera: "Cavalry doesn't dig in.",
    falta_campesino: "You need a peasant on the hex: he builds it and stays as the garrison.",
    murallas_en_pie: "No breach, no entry: the walls have to be at zero.",
    cerca_de_enemigo: "Too close to an enemy settlement (2 or more hexes needed).",
    ya_dormida: "It's already resting.",
    no_dormida: "It isn't resting.",
  },
  faltan: "You're short of {que}.",
  requiereTec: "Requires {tec}.",
  cercaDe: "{nombre} is {d} away; {min} is needed.",
  sinHuecoDetalle: "Garrison full and no free hex around it.",
  porQueNo: "Why not",
  sonido: "Sound",
  musica: "Music",
  creditos: "Credits",
  creditoMusica: "Music by Alexander Nakarada (creatorchords.com), via free-stock-music.com, licensed CC BY 4.0: \"Lively Tavern\" in the menu; \"Village Ambiance\", \"Might & Magic\" and \"Medieval Chateau\" in game.",
  tocaParaEntrar: "Tap to enter",
  mejorarA: "Upgrade to",
  dormir: "Rest",
  despertar: "Wake",
  dormida: "Resting",
  dormirPista: "A resting troop isn't counted as pending at the end of the turn and doesn't show up in Next troop. It wakes on its own if an enemy comes next to it or, if it was resting hurt, once fully healed.",
  evolucionPuntos: "Points over time",
  puntosAlMarcador: "points to your score",
  soloOro: "Gold only",
  puntoClaveVale: "worth {n} points at the end to whoever holds it",
  siguienteTropaCorto: "Next troop",
  sinCarreteras: "No roads",
  sonidoOn: "On",
  sonidoOff: "Off",
  desgloseVeterania: "veterancy",
  desgloseTerreno: "terrain",
  desgloseAtrincherada: "dug in",
  desgloseMurallas: "walls",
  desgloseOtros: "technology and realm",
  eventos: {
    mover: "{tropa} moves.",
    reclamar: "{jugador} claims a hex.",
    ataque: "{atacante} attacks {defensor}: {dano} damage{extra}.",
    contraataque: "{defensor} counterattacks: {dano} damage{extra}.",
    muere: "{tropa} dies.",
    asciende: "{jugador}: {tropa} is promoted to {nivel}.",
    despierta: "{tropa} wakes in {asentamiento}: enemy nearby.",
    despiertaCurada: "{tropa} wakes in {asentamiento}: fully healed.",
    asedio: "{atacante} besieges {asentamiento}: −{dano} walls{extra}.",
    brecha: "Breach in {asentamiento}!",
    conquista: "{jugador} conquers {asentamiento}.",
    funda: "{jugador} founds {asentamiento}.",
    recluta: "{jugador} recruits {tropa} in {asentamiento}.",
    mejoraTropa: "{tropa} upgrades to {nuevo}.",
    castillo: "{jugador} builds a castle: {asentamiento}.",
    ciudad: "{asentamiento} is now a city.",
    investiga: "{jugador} researches {tec}.",
    investigado: "{jugador} has discovered {tec}.",
    bancarrota: "{jugador} can't pay: {tropa} deserts.",
    licencia: "{jugador} disbands {tropa}.",
    atrinchera: "{tropa} digs in.",
    carretera: "{jugador} builds a road.",
    eliminado: "{jugador} has been wiped out.",
    victoria: "{jugador} wins the game.",
    turno: "— Turn {turno} —",
  },
};
