// Todos los textos de la interfaz. Para traducir: copiar este fichero
// como textos.en.js y cambiar las cadenas.
window.FWM = window.FWM || {};
FWM.datosBase = FWM.datosBase || {};

FWM.datosBase.textos = {
  titulo: "Final War: Medieval",
  turno: "Turno",
  finTurno: "Fin de turno",
  deshacer: "Deshacer",
  tecnologia: "Tecnología",
  nuevaPartida: "Nueva partida",
  menu: "Menú",
  inicioPartida: "Inicio de partida",
  jugar: "Jugar",
  ranking: "Ranking",
  misiones: { titulo: "Misiones", deHoy: "Misiones de hoy", hechas: "{n} de 3 hechas", mision: "Misión", premio: "Premio (oro)", de: "de", semanal: "semana", cumplida: "Misión cumplida", cumplidaUna: "misión cumplida", cumplidas: "misiones cumplidas" },
  globos: ["Este eres tú: tu héroe. Está en tu capital.", "Toca un hexágono claro para mover una tropa; los rojos son para atacar.", "Cuando acabes, pulsa Fin de turno."],
  medallaMas: "y {n} medalla(s) más: míralas en Héroe → Logros",
  bienvenida: {
    elige: "Elige tu héroe", eligePista: "Irá contigo a todas las partidas y crecerá con lo que ganes. Solo puedes tener uno.",
    lemas: { espadachin: "Aguanta y protege", arquero: "Dispara de lejos", nordico: "Pega fuerte", alquimista: "Quema y cura" },
    esteEsElMio: "Este es el mío", nombre: "¿Cómo te llamas?", nombreEjemplo: "Tu nombre", seguir: "Seguir",
    primerPunto: "Tienes 1 punto de mejora", primerPuntoPista: "Elige una mejora. Cada partida que juegues te dará más.",
    cuenta: "¿Guardamos tu héroe?", cuentaPista: "Sin cuenta, tu héroe vive solo en este dispositivo. Con cuenta, sales en el ranking y no lo pierdes nunca.",
    listo: "Listo, {nombre}.",
    alMenu: "Ver el menú",
  },
  heroeUI: {
    boton: "Héroe", titulo: "Tu héroe", nivel: "Nivel", unidadPronto: "unidad nueva (pronto)", unidadFutura: { infanteria_pesada: "Infantería pesada (pronto)", caballeria_pesada: "Caballería pesada (pronto)", trabuco: "Trabuco (pronto)" }, puntosMejora: "Puntos de mejora", sinGastar: "{n} sin gastar", gastar: "Mejorar", tope: "Al máximo", requiere: "Requiere {que}",
    siguienteNivel: "Siguiente nivel: {nombre} a {n} puntos", siguientePunto: "Siguiente punto de mejora a {n} puntos", cima: "En la cima",
    elegirClase: "Elegir héroe", clase: "Clase", cambiarClase: "Cambiar de héroe", familia: { heroe: "El héroe", aura: "Aura (tropas pegadas al héroe)", reino: "Reino", aspecto: "Aspecto" },
    explicacion: "Tu héroe va a cada partida como una tropa más. Sube con los puntos que acumulas: cada peldaño da un punto de mejora; cada nivel abre una unidad nueva.",
    mejoras: "Mejoras", elegir: "Elegir", niveles: "Niveles", logros: "Logros", masAdelante: "Más adelante", disponibles: "para elegir", nadaDeEsteTipo: "Aún no tienes ninguno de este tipo.", tiendaPista: "Se paga con oro del héroe: se gana al acabar partidas, con medallas y misiones.", noSeVenden: "No se venden: así salen",
    desbloquea: "Abre", nada: "—", sinCuenta: "Tu héroe vive solo en este dispositivo. Crea una cuenta para no perderlo.", muerto: "Tu héroe ha caído. No vuelve en esta partida.",
    puntoMejora: "punto de mejora", puntoNuevo: "¡Punto de mejora!", puntosNuevos: "¡{n} puntos de mejora!", nivelNuevo: "¡Nivel nuevo!", desbloqueado: "Desbloqueado", mejorarAhora: "Mejorar ahora", luego: "Luego", adelante: "¡Adelante!",
    leyenda: "La Leyenda: el Emperador con más puntos de todos. Solo puede haber uno.",
    oroHeroe: "de oro del héroe", oroCorto: "oro", botin: "¡Botín!", botinRepetido: "ya tenías todo el botín: {n} de oro",
    objetos: "Objetos", tienda: "Tienda", inventario: "Inventario", equipado: "Equipado", equipar: "Equipar", quitar: "Quitar", comprar: "Comprar", oro: "Oro del héroe", precio: "{n} oro",
    tipos: { arma: "Arma", escudo: "Escudo", montura: "Montura", cabeza: "Cabeza", consumible: "Consumible", aspecto: "Aspecto" }, vacio: "Vacío", nadaInventario: "Aún no tienes objetos. Salen al acabar partidas, con las medallas y en la tienda.",
    comoSale: { tienda: "Tienda: {n} oro", botin: "Botín al acabar una partida", medalla: "Medalla {nombre} ({nivel})", campana: "Campaña, mapa {n}", liga: "Liga semanal, {n}.º" },
  },
  duelo: {
    boton: "Duelo online", titulo: "Duelo online",
    explicacion: "Uno contra uno, en directo. Partida rápida a 20 turnos y 60 segundos por turno.",
    buscarRival: "Buscar rival", retar: "Retar a un amigo", tengoCodigo: "Tengo un código", entrar: "Entrar",
    buscando: "Buscando rival… {s} s", esperandoAmigo: "Dile este código a tu amigo. Cuando lo escriba, empezáis.", entrando: "Entrando en el reto…",
    codigo: "Código", rivalEncontrado: "¡Rival encontrado! {nombre}", necesitaCuenta: "Para jugar duelos hace falta una cuenta (es tu nombre en el ranking).",
    rivalDesconectado: "Tu rival se ha desconectado. Tiene {s} s para volver.", desincronizada: "Las dos partidas no coinciden: duelo anulado, no cuenta.",
    anulada: "Duelo anulado", abandono: "por abandono del rival", rendicion: "te has rendido", rendirse: "Rendirse", confirmarRendirse: "¿Te rindes? El rival gana el duelo.",
    conAmigo: "Jugar con un amigo", igualar: "Igualar héroes", comoEstan: "Como están", igualarPista: "Igualar: los dos juegan al nivel del héroe más bajo, sin objetos. Recomendado si uno tiene más nivel.",
    rankingDuelos: "Duelos", elo: "Elo", liga: "Liga de la semana", ligaPista: "Elo ganado desde el lunes. Al cerrar la semana: 1.º Mandoble, 2.º Égida, 3.º 150 de oro del héroe.", historial: "Tus últimos duelos", revancha: "Revancha", sinDuelos: "Aún no hay duelos.",
    teReta: "{nombre} te reta a un duelo", aceptarReto: "Aceptar", retoEnviado: "Reto enviado a {nombre}. Si está conectado, entra ya; si no, lo verá al abrir el juego.", eloCambio: "Elo {antes} → {despues}",
    ligaPremio: "¡Liga de la semana pasada! Quedaste {pos}.º: {premio}", ganaste: "ganaste", perdiste: "perdiste", marca: "Marca contra {nombre}: {g}-{p}",
    chat: { boton: "Chat", invitar: "{nombre} quiere chatear contigo.", aceptar: "Aceptar", no: "No", pedido: "Invitación enviada. Si {nombre} acepta, se abre el chat.", rechazado: "{nombre} no quiere chatear.", aceptado: "{nombre} ha aceptado el chat.", escribe: "Escribe…", enviar: "Enviar", cerrar: "Cerrar", frases: ["¡Buena partida!", "¡Toma!", "Uy…", "Bien jugado", "GG", "👍", "😅", "⚔️"] },
    otraVersion: "Tu rival tiene otra versión del juego. Cerrad y volved a abrir el juego los dos para actualizarlo.",
    otraVersionCola: "Hay alguien buscando, pero con otra versión del juego. Pídele que cierre y vuelva a abrir el juego.",
    tuTurno: "¡Te toca! Turno {n}", marcador: "Marcador", yo: "Tú", vas: "vas", primero: "1.º", segundo: "2.º", empate: "empate",
    turnoDe: "Turno de {nombre}", preparado: "¡Preparado!", esperandoRival: "Esperando a {nombre}…", empiezaEn: "Empieza en {s} s", listo: "Listo", enCurso: "Estás en un duelo en directo. Si te vas, tu rival gana.", volverPartida: "Volver a la partida", abandonoPropio: "has abandonado (tres turnos sin jugar)", ultimoAviso: "Otro turno sin hacer nada y pierdes por abandono.", reglasLinea: "{turnos} turnos · {s} s por turno · solo oro · gana quien más puntos tenga", tiempoAgotado: "Se acabó el tiempo: turno terminado.", sinRed: "Sin conexión con la nube.",
  },
  comoSeJuega: "Glosario",
  ajustes: "Ajustes",
  volverInicio: "Inicio",
  volver: "Volver",
  hola: "Hola, {nombre}",
  nombreJugador: "Tu nombre",
  nombrePista: "Para el ranking. Puedes cambiarlo cuando quieras.",
  bandoFavorito: "Bando favorito",
  marcador: "Tu marcador",
  historial: "Últimas partidas",
  sinPartidas: "Todavía no has jugado ninguna partida.",
  rankingOnlinePronto: "El ranking con otros jugadores llegará con la versión online.",
  ganada: "ganada",
  perdida: "perdida",
  subtitulo: "Guerra por hexágonos. Una partida cabe en un café.",
  cuenta: "Cuenta",
  instalar: "Instalar en el móvil",
  instalarIos: "Para instalarlo: pulsa Compartir y luego \"Añadir a pantalla de inicio\".",
  instalado: "Instalado. Ábrelo desde tu pantalla de inicio.",
  crearCuenta: "Crear cuenta",
  crearCuentaOEntrar: "Crear cuenta o entrar",
  cuentaReclamo: "¿Quieres salir en el ranking?",
  entrar: "Entrar",
  salir: "Salir",
  correo: "Correo",
  clave: "Contraseña",
  olvideClave: "He olvidado la contraseña",
  claveEnviada: "Te hemos enviado un correo para cambiarla.",
  seguirSinCuenta: "Seguir sin cuenta",
  paraRanking: "Para aparecer en el ranking con otros jugadores, crea una cuenta o entra. Jugar no la necesita.",
  yaTengoCuenta: "Ya tengo cuenta",
  noTengoCuenta: "No tengo cuenta",
  conectadoComo: "Conectado como",
  rankingSemana: "Semana",
  rankingTotal: "Total",
  rankingHoy: "Hoy",
  rankingMejor: "Mejor partida",
  rankingDia: "Mapa del día",
  dueloEnCurso: "Duelo en curso", dueloVolver: "Volver al duelo", dueloRelojSigue: "El reloj sigue corriendo: tu rival te espera.",
  rankingDiaPista: "Mejor partida de hoy en el mapa del día. Mismo mapa para todos; cambia a medianoche.",
  mapaDelDia: "Mapa del día",
  mapaDelDiaPista: "El mismo mapa para todos hoy. Tu mejor partida entra en el ranking del día.",
  diasSeguidos: "{n} días seguidos",
  rachaDias: { dias: "Racha: {n} días seguidos", uno: "Racha: 1 día", hoy: "juega hoy para mantenerla", hecha: "hoy ya cuenta", empieza: "Juega una partida hoy y empieza tu racha", nuevoDia: "Nuevo día: misiones y mapa del día nuevos." },
  dificil: "Difícil",
  dificultadPista: { facil: "Rivales torpes: para aprender.", normal: "Rivales con criterio, cada uno con su carácter.", dificil: "Rivales implacables: van a por ti, cazan a tu héroe, pisan cada punto clave y empiezan con un 25 % más de oro." },
  escenarios: { boton: "Grandes batallas", titulo: "Grandes batallas", pista: "Mapas históricos grandes: cada reino empieza en su tierra. Mismas reglas, mucho más sitio y muchos más turnos.", jugar: "Jugar el escenario", reinos: "{n} reinos", turnos: "{n} turnos", tuBando: "Tu reino", bandoPista: "Tu bando decide dónde empiezas.", aviso: "Geografía inspirada en la real: los brazos de mar se cierran con pasos de tierra porque aquí no hay barcos." },
  barbaros: { boton: "Bárbaros", titulo: "Modo Bárbaros", pista: "Empiezas solo en el centro del valle. Desde la tercera ronda entran hordas por los bordes, cada vez más y por más lados. Aguanta lo que puedas.", jugar: "Resistir", ronda: "Ronda", llegaOleada: "¡Oleada {n} bárbaros! Ronda {ronda}", aguantaste: "Aguantaste {n} rondas", record: "Tu récord: {n} rondas", nuevoRecord: "¡Récord nuevo: {n} rondas!", sinRecord: "Aún no has resistido ninguna.", ranking: "Bárbaros", rankingPista: "Rondas aguantadas en el modo Bárbaros. Al lado de cada jugador, el nivel de su héroe.", proxima: "Siguiente oleada: ronda {ronda}, por {lados} lado(s)", consejo: "Consejo: mete tropas en la guarnición y no salgas a campo abierto sin necesidad." },
  campana: { boton: "Campaña", titulo: "Campaña", pista: "Diez mapas hechos a mano, cada uno más difícil que el anterior. Cada mapa superado da su premio una sola vez.", progreso: "{n} de {t} mapas superados", mapa: "Mapa {n}", jugar: "Jugar", repetir: "Repetir", bloqueado: "Supera el mapa anterior", superado: "Superado", premio: "Premio", superadoCer: "Campaña: mapa {n} superado", completa: "Campaña completa. ¡Enhorabuena!", rivales: "{n} rival(es) · {d} · {t} turnos" },
  batalla: { boton: "Batalla semanal", titulo: "Batalla de la semana", noEsSimulacion: "Mapa inspirado en la batalla, no una recreación exacta.", pista: "Un mapa hecho a mano con reglas propias. Cambia cada lunes; tu mejor partida entra en el ranking de la semana.", ranking: "Batalla", rankingPista: "Mejor partida de esta semana en la batalla semanal. Cambia el lunes.", cambia: "Cambia en {n} días", cambiaManana: "Cambia mañana", tuSemana: "Esta semana: {n} partida(s) · mejor {m} puntos", sinJugar: "Aún no la has jugado esta semana.", jugar: "Jugar la batalla", verRanking: "Ver ranking", mejorSemana: "Batalla de la semana: mejor {n}", reglas: "Reglas" },
  medallas: "Medallas",
  conectado: "Conectado",
  cambiarFigura: "Cambiar figura",
  tuFigura: "Tu figura",
  escalonAspirante: "Recluta",
  medallaNueva: "Medalla nueva",
  posiciones: ["Primero", "Segundo", "Tercero", "Cuarto", "Quinto", "Sexto", "Séptimo", "Octavo"],
  tuTotal: "Tu total",
  verResumen: "Ver resumen",
  repeticion: { boton: "Ver repetición", titulo: "Repetición", turnos: "{n} turnos guardados", reproducir: "▶ Reproducir", pausa: "❚❚ Pausa" },
  compartir: { boton: "Compartir", titulo: "Tu partida", texto: "{puntos} puntos en {mapa}. Final War: Medieval.", guardar: "Mantén pulsada la imagen para guardarla o copiarla.", descargar: "Descargar" },
  medallasPista: "{n} de {total}",
  nivelesMedalla: ["Bronce", "Plata", "Oro"],
  siguienteObjetivo: "Siguiente",
  nivelMaximo: "Nivel máximo",
  rankingSumaPista: "Suma de los puntos de todas tus partidas.",
  rankingMejorPista: "Tu mejor puntuación en una sola partida.",
  tuPosicion: "Tu posición",
  sinRanking: "Todavía no hay partidas en el ranking. ¡Sé el primero!",
  nubeCargando: "Conectando con la nube…",
  sinConexion: "Sin conexión con el ranking. Tus puntos se guardan en el aparato y se enviarán cuando haya red.",
  guardarEnRanking: "Guardar en el ranking",
  enviadoRanking: "Enviado al ranking",
  pendienteRanking: "Se enviará al ranking cuando entres con tu cuenta",
  errCorreoUsado: "Ese correo ya tiene cuenta. Prueba a entrar.",
  errCredenciales: "Correo o contraseña incorrectos.",
  errClaveCorta: "La contraseña necesita al menos 6 caracteres.",
  errCorreo: "Ese correo no parece válido.",
  errDemasiado: "Demasiados intentos. Espera un minuto.",
  errRed: "No hay conexión. Inténtalo más tarde.",
  errNombre: "Pon un nombre de 2 a 20 letras.",
  iaEtiqueta: "IA",
  iaUltimaPartida: "Los jugadores marcados IA son tus rivales de la última partida.",
  escalon: "Escalón",
  escalones: [[100, "Recluta"], [250, "Veterano"], [400, "Élite"], [600, "Leyenda"]],
  teFaltan: "Te faltan {n} puntos para {nombre}.",
  tutorial: "Tutorial",
  saltarTutorial: "Saltar", minimizar: "Minimizar", maximizar: "Ver de nuevo",
  entendido: "¡Entendido!",
  primeraVez: "¿Primera vez? El tutorial son tres minutos jugando.",
  jugarDirecto: "Jugar directamente",
  tutorialPasos: {
    seleccionar: "Este es tu pueblo: la estrella lo marca como capital. Tu héroe está dentro. Toca el circulito que señala la flecha (la guarnición, 1/1) para sacarlo.",
    mover: "Los hexágonos claros son adonde puede ir. Toca el que señala la flecha: pisar un hexágono lo hace tuyo, y las monedas (minas) y estrellas (puntos clave) valen puntos.",
    finTurno: "Cada turno tu reino ingresa oro (arriba a la izquierda). Pulsa Fin de turno, donde apunta la flecha, para ver jugar al rival.",
    reclutar: "Toca los martillos que señala la flecha y elige un campesino: 10 oro. Los soldados solo se reclutan en ciudades y castillos.",
    explorar: "Manda tropas a las minas y estrellas que señala la flecha: valen puntos al final. Con 40 oro, la flecha azul del pueblo lo hace ciudad. Juega unos turnos.",
    atacar: "Ataca: selecciona una tropa y toca al enemigo que señala la flecha (los enemigos atacables salen en rojo). Verás el daño antes de confirmar. Cuerpo a cuerpo hay contraataque; los arqueros disparan sin recibirlo. Cuida a tu héroe: si muere, no vuelve.",
    final: "Para tomar un pueblo enemigo: mata a la guarnición, deja las murallas a cero (asedio) y entra. Gana quien más puntos tenga al turno 15 o quien elimine a los demás. ¡Suerte!",
  },
  jugador: "Jugador",
  tu: "Tu reino",
  ia: "IA",
  hexagono: "Hexágono",
  hexagonos: "Hexágonos",
  heroesMatados: "Héroes abatidos",
  verDetalle: "Ver el detalle", sano: "sano", detalleCorto: "más", fundarCorto: "Pueblo", atrincherarCorto: "Atrinch.", licenciarCorto: "Licenciar", reclutarCorto: "Reclutar", lineaVacia: "Toca una tropa o un pueblo para ver qué puede hacer.", sinDueno: "Sin dueño", iasJugando: "Los rivales están jugando…",
  oroDisponible: "Tienes {n} de oro.",
  confirmarCiudad: "¿Mejorar a ciudad por {n} de oro? Más guarnición, más murallas y recluta de todo.",
  rapidaResumen: "Partida rápida: {n} turnos, solo oro. Gana quien más puntos tenga.",
  heroe: "Héroe",
  nadie: "Sin dueño",
  de: "de",
  vida: "Vida",
  ataque: "Ataque",
  defensa: "Defensa",
  asedio: "Asedio",
  alcance: "Alcance",
  movimiento: "Movimiento",
  mantenimiento: "Mantenimiento",
  coste: "Coste",
  produce: "Produce",
  murallas: "Murallas",
  capital: "Capital",
  aislado: "Aislado",
  almacen: "Almacén",
  guarnicion: "Guarnición",
  construcciones: "Construcciones",
  vacio: "vacío",
  reclutar: "Reclutar",
  mejorarTropa: "Mejorar tropa",
  mejorarACiudad: "Mejorar a ciudad",
  construirCastillo: "Construir castillo",
  reclamar: "Reclamar",
  fundar: "Fundar",
  castillo: "Castillo",
  fundarPueblo: "Fundar pueblo",
  salir: "Salir",
  atrincherar: "Atrincherarse",
  atrincherada: "Atrincherada",
  irA: "Ir a…",
  irAPista: "Toca el hexágono de destino. La tropa irá sola cada turno.",
  destino: "Destino",
  cancelarDestino: "Cancelar destino",
  enemigoCerca: "se detiene: enemigo cerca",
  siguienteTropa: "Siguiente tropa",
  tropasPendientes: "Tienes {n} tropa(s) que aún pueden actuar.",
  verTropa: "Ver tropa",
  terminarIgual: "Terminar igualmente",
  reino: "Reino",
  tesoro: "Tesoro",
  hucha: "Tienes",
  entraPorTurno: "Ingresos",
  salePorTurno: "Gastos",
  balance: "Balance",
  recurso: "Recurso",
  enCurso: "en curso",
  hechas: "hechas",
  cadaUno: "a {n} cada uno",
  neto: "Neto",
  porQue: "por qué",
  sinIngresos: "Nada",
  yacimientosParados: "Yacimientos que no producen",
  zonasAisladas: "Zonas aisladas",
  asentamientos: "Asentamientos",
  tropas: "Tropas",
  tecnologias: "Tecnologías",
  tuReinoEs: "Eres {reino}, el reino {color}. Tu capital: {capital}.",
  idioma: "Idioma", idiomaAviso: "El juego se recargará para cambiar el idioma.",
  fichas: {
    mantenimientoCorto: "mant.",
    sinGuarnicion: "Sin guarnición: si abren brecha, el enemigo entra andando.", sinGuarnicionBrecha: "Sin guarnición y con brecha: el enemigo entra andando.",
    sinInvestigarNada: "No estás investigando nada.", esTecnologia: "{nombre} (tecnología)", delHeroe: " del héroe",
    nombresAsent: "Nombres de asentamiento", cuerpoACuerpo: "cuerpo a cuerpo", seReclutaEn: "Se recluta en", mejoraA: "Mejora a", especial: "Especial",
    puedeFundar: "Puede fundar pueblos", noMoverDisparar: "No puede moverse y disparar en el mismo turno", comoSeConsigue: "Cómo se consigue",
    loFunda: "Lo funda un campesino", mejorando: "Mejorando un {que}", seConstruye: "Se construye en un hexágono tuyo vacío",
    huecosGuarnicion: "Huecos de guarnición", plusDefensa: "Plus de defensa", reclutaFicha: "Recluta", todasLasTropas: "Todas las tropas",
    mejoraTropas: "Mejora tropas", si: "Sí", no: "No", alConquistarlo: "Al conquistarlo", pasaA: "Pasa a {que}", tarda: "Tarda", desbloquea: "Desbloquea",
    mover: "Mover", noSePuede: "no se puede", puntosPasos: "{p} puntos ({n} {pasos})", sePuedeConstruir: "Se puede construir",
    carreteraDesc: "La construye un campesino en un hexágono tuyo. Entrar cuesta {n} punto. Los asentamientos cuentan como carretera.",
    aLaGuarnicion: "a la guarnición", brechaSinPlus: "brecha: sin plus", pistaMover: "Toca un hexágono claro para mover, rojo para atacar, naranja para asediar.",
    noProduce: "No produce: no está conectado a un asentamiento.", tuMayus: "Tú" },
  legal: "Legal", verPrivacidad: "Política de privacidad", verCondiciones: "Condiciones de uso", version: "Versión",
  borrarCuenta: "Borrar mi cuenta", borrarCuentaAviso: "Se borra tu cuenta, tu héroe, tus puntuaciones y tus duelos. No se puede deshacer y no se puede recuperar.", borrarCuentaConfirmar: "¿Seguro que quieres borrar tu cuenta y todo tu progreso?", borrarCuentaHecho: "Cuenta borrada. Tu progreso en este dispositivo sigue aquí.", borrarCuentaError: "No se ha podido borrar. Escribe a {contacto} y la borramos a mano.",
  aceptasAlCrear: "Al crear la cuenta aceptas las {condiciones} y la {privacidad}.",
  paleta: "Colores", paletaNormal: "Normales", paletaDaltonicos: "Para daltonismo", paletaPista: "Cambia los colores de los reinos por otros que se distinguen sin ver bien el rojo y el verde.",
  colorAzul: "azul",
  colorRojo: "rojo",
  tuSufijo: "(tú)",
  tuCapital: "Tu capital",
  mapaNumero: "Mapa nº",
  mapa: "Mapa",
  mapaAleatorio: "Aleatorio",
  avanzado: "Avanzado",
  puedeMoverse: "Puede moverse ({n})",
  contraGuarnicion: "Contra la guarnición",
  contraMurallas: "Contra las murallas",
  sinContraataque: "sin contraataque",
  quitas: "Quitas",
  explicaAtaque: "Atacar guarnición golpea a la tropa de dentro (protegida por las murallas mientras estén en pie). Asediar golpea a las murallas.",
  glosario: "Glosario",
  carretera: "Carretera",
  construirCarretera: "Construir carretera",
  terreno: "Terreno",
  pasos: "pasos",
  conCarretera: "con carretera",
  experiencia: "Experiencia",
  salida: "Salida: ataca desde dentro sin el plus de las murallas en este intercambio. Si mata, sale al hexágono.",
  personalidades: { equilibrada: "equilibrada", guardiana: "guardiana", expansionista: "expansionista", belicosa: "belicosa", implacable: "implacable" },
  sobre: "Sobre",
  sinInvestigar: "No estás investigando nada. Puedes empezar {tec} ({coste}).",
  verTecnologias: "Ver tecnologías",
  buscar: "Buscar…",
  pestanas: { bandos: "Bandos", tropas: "Tropas", asentamientos: "Asentamientos", tecnologias: "Tecnologías", recursos: "Recursos", terrenos: "Terrenos", reglas: "Reglas" },
  verEnGlosario: "Ver en el glosario",
  licenciar: "Licenciar",
  deserta: "deserta",
  bancarrotaAviso: "¡Bancarrota! {n} tropas desertan por falta de oro.",
  bancarrotaAvisoUna: "¡Bancarrota! {tropa} deserta por falta de oro.",
  bancarrotaFin: "Bancarrota a la vista: el próximo turno te faltarán {oro} de oro y desertarán {n} tropas (las más baratas primero). Licencia tropas o consigue oro.",
  verReino: "Ver reino",
  licenciarConfirmar: "¿Disolver esta tropa? No se devuelve nada.",
  ingresos: "Ingresos",
  gastos: "Gastos",
  porTurno: "por turno",
  atacar: "Atacar",
  asediar: "Asediar",
  atacarGuarnicion: "Atacar guarnición",
  cancelar: "Cancelar",
  confirmar: "Confirmar",
  haces: "Haces",
  recibes: "Recibes",
  hiciste: "Hiciste",
  recibiste: "Recibiste",
  a: "a",
  yaActuo: "Ya ha actuado",
  sinMovimiento: "Sin movimiento",
  puedeActuar: "Puede actuar",
  investigando: "Investigando",
  investigar: "Investigar",
  investigado: "Investigado",
  turnos: "turnos",
  requiere: "Requiere",
  disponible: "Disponible",
  bloqueado: "Bloqueado",
  nada: "Nada",
  cerrar: "Cerrar",
  ganaste: "¡Has ganado!",
  perdiste: "Has sido eliminado.",
  gano: "ha ganado la partida.",
  eliminado: "eliminado",
  jugadores: "Rivales",
  empezar: "Empezar partida",
  continuar: "Continuar partida",
  tamanoMapa: "Tamaño del mapa",
  dificultad: "Dificultad",
  tipoPartida: "Tipo de partida",
  tuBando: "Tu bando",
  bando: "Bando",
  bandoAleatorio: "Aleatorio",
  bandoAleatorioPista: "Te toca un bando al azar. Cada bando tiene un rasgo propio; míralos en el glosario.",
  limiteTurnos: "Turnos", finPartida: "Fin de la partida", finPuntos: "Por puntos", finEliminacion: "Por eliminación",
  finPuntosPista: "Al acabar el turno {n} gana quien más puntos tenga. Antes gana quien elimine a los demás.",
  finEliminacionPista: "Sin límite de turnos: se juega hasta que solo quede un reino en pie. Puede durar mucho.",
  sinLimite: "Sin límite",
  puntos: "Puntos",
  victoriaPorPuntos: "por puntos al llegar al límite de turnos",
  rasgo: "Rasgo",
  bonoContra: "+{n}: {atacante} contra {etiqueta}",
  defensaContraTxt: "+{n} defensa de {defensor} contra {etiqueta}",
  defensaContra: "Defensa contra",
  bonusContra: "Bonus contra",
  etiquetasNombre: { lanza: "lanza", espada: "espada", montada: "caballería", armadura: "armadura", a_pie: "infantería", a_distancia: "tropas a distancia", ligera: "tropas ligeras", maquina: "máquinas" },
  tipos: { rapida: "Rápida", normal: "Lenta", personalizada: "Personalizada", dia: "Mapa del día", duelo: "Duelo", campana: "Campaña", batalla: "Batalla semanal", escenario: "Gran batalla", barbaros: "Bárbaros" },
  conquistas: "Conquistas",
  matadas: "Bajas causadas",
  perdidas: "Bajas sufridas",
  oroGanado: "Oro ganado",
  lineaTiempo: "Asentamientos por turno",
  records: "Récords",
  partidas: "partidas",
  ganadas: "ganadas",
  racha: "racha",
  mejorRacha: "mejor",
  mejorVictoria: "mejor victoria",
  puntosHoy: "hoy",
  puntosSemana: "esta semana",
  puntosTotal: "en total",
  mejorPartida: "mejor partida",
  revancha: "Revancha (mismo mapa)",
  otraPartida: "Otra partida",
  rapida: "Rápida",
  normalPartida: "Lenta",
  personalizada: "Personalizada",
  opcionesPersonalizadas: "tamaño, tecnología, hucha, recursos, mapa",
  huchaInicial: "Hucha inicial",
  huchaNormal: "Normal",
  huchaDoble: "Doble",
  huchaTriple: "Triple",
  arbolCompleto: "Árbol completo (se investiga)",
  todoDesbloqueado: "Todo desbloqueado (partida rápida)",
  recursosMapa: "Recursos",
  equilibrados: "Equilibrados (lo mismo cerca de cada capital)",
  aleatorios: "Aleatorios",
  facil: "Fácil",
  normal: "Normal",
  pequeno: "Pequeño",
  mediano: "Mediano",
  grande: "Grande",
  semilla: "Semilla",
  registro: "Registro",
  ayuda: "Ayuda",
  ayudaTexto: [
    "Toca una tropa tuya para ver adónde puede ir y a quién puede atacar.",
    "Mover no conquista: para hacer tuyo un hexágono, pulsa Reclamar.",
    "Los yacimientos producen si están conectados a un asentamiento tuyo.",
    "Un campesino puede fundar un pueblo en un hexágono tuyo vacío.",
    "Mete tropas en tus asentamientos: sin guarnición y con las murallas a cero, el enemigo entra andando.",
    "Las catapultas rompen murallas. La infantería también, pero muy despacio.",
    "Si no puedes pagar el mantenimiento, mueren tropas hasta que puedas.",
  ],
  errores: {
    sin_accion: "Esa tropa ya ha actuado este turno. Elige otra o termina el turno.",
    sin_movimiento: "Ya no puede moverse más este turno. Termina el turno y volverá a moverse.",
    no_es_tuya: "No es tuya.",
    hex_ocupado: "Ese hexágono está ocupado.",
    fuera_de_alcance: "Está lejos: acércate un hexágono más.",
    sin_recursos: "Te falta oro. Termina el turno para cobrar, o licencia una tropa.",
    sin_tecnologia: "Te falta una tecnología.",
    nivel_heroe: "Tu héroe aún no tiene nivel para esta unidad.",
    sin_oro: "No tienes oro del héroe suficiente.", ya_tienes: "Ya lo tienes.", no_se_vende: "No se vende.", no_tienes: "No lo tienes.", sin_puntos: "No tienes puntos de mejora.", tope: "Ya está al máximo.", requiere: "Falta otra mejora antes.",
    sin_hueco: "No hay sitio: la guarnición está llena y los hexágonos de alrededor, ocupados. Saca una tropa fuera.",
    ya_reclutado: "Ya ha reclutado este turno. Podrá otra vez el turno que viene.",
    demasiado_cerca: "Demasiado cerca de otro asentamiento.",
    no_puede_fundar: "Esta tropa no puede fundar.",
    ya_es_tuyo: "Ya es tuyo.",
    no_desde_dentro: "Las tropas cuerpo a cuerpo tienen que salir para atacar.",
    catapulta_movida: "La catapulta no puede moverse y disparar en el mismo turno.",
    no_hay_objetivo: "No hay objetivo.",
    ya_investigando: "Ya estás investigando algo.",
    ya_atrincherada: "Ya está atrincherada.",
    ya_hay_carretera: "Ya hay carretera.",
    no_aqui: "Solo en {donde}.",
    no_se_puede: "No se puede.",
    hex_no_tuyo: "El hexágono no es tuyo: pulsa Reclamar primero.",
    terreno_no_construible: "No se construye en este terreno.",
    solo_acuartelada: "Solo dentro de una ciudad: métela en la guarnición.",
    solo_en_ciudad: "Solo en una ciudad, no en {tipo}.",
    no_se_atrinchera: "La caballería no se atrinchera.",
    falta_campesino: "Hace falta un campesino encima: él lo construye y se queda de guarnición.",
    murallas_en_pie: "Sin brecha no se entra: hay que dejar las murallas a cero.",
    cerca_de_enemigo: "Demasiado cerca de un asentamiento enemigo (hace falta 2 o más).",
    ya_dormida: "Ya está dormida.",
    no_dormida: "No está dormida.",
  },
  faltan: "Te faltan {que}.",
  requiereTec: "Requiere {tec}.",
  cercaDe: "{nombre} está a {d}; hace falta {min}.",
  sinHuecoDetalle: "Guarnición llena y sin hexágono libre alrededor.",
  porQueNo: "Por qué no",
  sonido: "Sonido",
  musica: "Música",
  creditos: "Créditos",
  creditoMusica: "Música de Alexander Nakarada (creatorchords.com), vía free-stock-music.com, licencia CC BY 4.0: \"Lively Tavern\" en el menú; \"Village Ambiance\", \"Might & Magic\" y \"Medieval Chateau\" en la partida.",
  tocaParaEntrar: "Toca para entrar",
  mejorarA: "Mejorar a",
  dormir: "Dormir",
  despertar: "Despertar",
  dormida: "Dormida",
  dormirPista: "Dormida no cuenta como pendiente al acabar el turno ni sale en Siguiente tropa. Despierta sola si un enemigo se pone al lado o, si dormía herida, al curarse del todo.",
  evolucionPuntos: "Evolución de los puntos",
  puntosAlMarcador: "puntos a tu marcador",
  soloOro: "Solo oro",
  puntoClaveVale: "vale {n} puntos al final para quien lo posea",
  siguienteTropaCorto: "Sig. tropa",
  sinCarreteras: "Sin carreteras",
  sonidoOn: "Activado",
  sonidoOff: "Silencio",
  desgloseVeterania: "veteranía",
  desgloseTerreno: "terreno",
  desgloseAtrincherada: "atrincherada",
  desgloseMurallas: "murallas",
  desgloseOtros: "tecnología y bando",
  eventos: {
    mover: "{tropa} se mueve.",
    reclamar: "{jugador} reclama un hexágono.",
    ataque: "{atacante} ataca a {defensor}: {dano} de daño{extra}.",
    contraataque: "{defensor} contraataca: {dano} de daño{extra}.",
    muere: "{tropa} muere.",
    asciende: "{jugador}: {tropa} asciende a {nivel}.",
    despierta: "{tropa} despierta en {asentamiento}: enemigo cerca.",
    despiertaCurada: "{tropa} despierta en {asentamiento}: ya está curada.",
    asedio: "{atacante} asedia {asentamiento}: −{dano} murallas{extra}.",
    brecha: "¡Brecha en {asentamiento}!",
    conquista: "{jugador} conquista {asentamiento}.",
    funda: "{jugador} funda {asentamiento}.",
    recluta: "{jugador} recluta {tropa} en {asentamiento}.",
    mejoraTropa: "{tropa} mejora a {nuevo}.",
    castillo: "{jugador} construye un castillo: {asentamiento}.",
    ciudad: "{asentamiento} es ahora ciudad.",
    investiga: "{jugador} investiga {tec}.",
    investigado: "{jugador} ha descubierto {tec}.",
    bancarrota: "{jugador} no puede pagar: {tropa} deserta.",
    licencia: "{jugador} licencia a {tropa}.",
    atrinchera: "{tropa} se atrinchera.",
    carretera: "{jugador} construye una carretera.",
    eliminado: "{jugador} ha sido eliminado.",
    victoria: "{jugador} gana la partida.",
    turno: "— Turno {turno} —",
  },
};
