// Todos los textos de la interfaz. Para traducir: copiar este fichero
// como textos.en.js y cambiar las cadenas.
window.FWM = window.FWM || {};
FWM.datosBase = FWM.datosBase || {};

FWM.datosBase.textos = {
  titulo: "Final War: Medieval",
  turno: "Turno",
  finTurno: "Fin de turno",
  deshacer: "Deshacer",
  tecnologia: "Tecnología",
  nuevaPartida: "Nueva partida",
  menu: "Menú",
  inicioPartida: "Inicio de partida",
  jugar: "Jugar",
  partidaRapida: "Partida rápida",
  ranking: "Ranking",
  misiones: { titulo: "Misiones", deHoy: "Misiones de hoy", hechas: "{n} de 3 hechas", mision: "Misión", premio: "Premio (oro)", de: "de", semanal: "semana", cumplida: "Misión cumplida", cumplidaUna: "misión cumplida", cumplidas: "misiones cumplidas" },
  globoSinPueblo: "Este eres tú: tu héroe. Aquí no hay pueblos: solo tu ejército.",
  globos: ["Este eres tú: tu héroe. Está en tu capital.", "Toca un hexágono claro para mover una tropa; los rojos son para atacar.", "Cuando acabes, pulsa Fin de turno."],
  medallaMas: "y {n} medalla(s) más: míralas en Héroe → Logros",
  bienvenida: {
    elige: "Elige tu héroe", eligePista: "Irá contigo a todas las partidas y crecerá con lo que ganes. Solo puedes tener uno.",
    lemas: { espadachin: "Aguanta y protege", arquero: "Dispara de lejos", nordico: "Pega fuerte", alquimista: "Quema y cura" },
    esteEsElMio: "Este es el mío", nombre: "¿Cómo te llamas?", nombreEjemplo: "Tu nombre", seguir: "Seguir",
    primerPunto: "Tienes 1 punto de mejora", primerPuntoPista: "Elige una mejora. Cada partida que juegues te dará más.",
    cuenta: "¿Guardamos tu héroe?", cuentaPista: "Sin cuenta, tu héroe vive solo en este dispositivo. Con cuenta, sales en el ranking y no lo pierdes nunca.",
    listo: "Listo, {nombre}.",
    alMenu: "Ver el menú",
  },
  heroeUI: { sinMontar: "Sin Monta: vas a pie y lo llevas de la brida",
    boton: "Héroe", titulo: "Tu héroe", nivel: "Nivel", puntosMejora: "Puntos de mejora", sinGastar: "{n} sin gastar", gastar: "Mejorar", tope: "Al máximo", requiere: "Requiere {que}",
    siguienteNivel: "Siguiente nivel: {nombre} a {n} puntos", siguientePunto: "Siguiente punto de mejora a {n} puntos", cima: "En la cima",
    elegirClase: "Elegir héroe", clase: "Clase", cambiarClase: "Cambiar de héroe", familia: { heroe: "El héroe", aura: "Aura (tropas pegadas al héroe)", reino: "Reino", aspecto: "Aspecto" },
    mejoras: "Mejoras", elegir: "Elegir", niveles: "Niveles", logros: "Logros", masAdelante: "Más adelante", disponibles: "para elegir", nadaDeEsteTipo: "Aún no tienes ninguno de este tipo.", tiendaPista: "Se paga con oro del héroe: se gana al acabar partidas, con medallas y misiones.", noSeVenden: "No se venden: así salen",
    desbloquea: "Abre", nada: "—", sinCuenta: "Tu héroe vive solo en este dispositivo. Crea una cuenta para no perderlo.", muerto: "Tu héroe ha caído. No vuelve en esta partida.",
    puntoMejora: "punto de mejora", puntoNuevo: "¡Punto de mejora!", puntosNuevos: "¡{n} puntos de mejora!", nivelNuevo: "¡Nivel nuevo!", subesNivel: "¡Has subido al nivel {n} con {faccion}!", tuRango: "Tu nuevo rango", nuevaTropa: "Nueva tropa", nuevo: "Nuevo", desbloqueado: "Desbloqueado", mejorarAhora: "Mejorar ahora", luego: "Luego", adelante: "¡Adelante!",
    oroHeroe: "de oro del héroe", oroCorto: "oro", botin: "¡Botín!", botinRepetido: "ya tenías todo el botín: {n} de oro",
    objetos: "Objetos", tienda: "Tienda", inventario: "Inventario", equipado: "Equipado", equipar: "Equipar", quitar: "Quitar", comprar: "Comprar", oro: "Oro del héroe", precio: "{n} oro",
    tipos: { arma: "Arma", escudo: "Escudo", montura: "Montura", cabeza: "Cabeza", consumible: "Consumible", aspecto: "Aspecto" }, vacio: "Vacío", nadaInventario: "Aún no tienes objetos. Salen al acabar partidas, con las medallas y en la tienda.",
    comoSale: { tienda: "Tienda: {n} oro", botin: "Botín al acabar una partida", medalla: "Medalla {nombre} ({nivel})", campana: "Campaña, mapa {n}", liga: "Liga semanal, {n}.º", cuenta: "Nivel de cuenta {n}" },
  },
  duelo: {
    boton: "Duelo online", titulo: "Duelo online",
    explicacion: "Uno contra uno, en directo. Partida rápida a 20 turnos y 60 segundos por turno.",
    buscarRival: "Buscar rival", retar: "Retar a un amigo", tengoCodigo: "Tengo un código", entrar: "Entrar",
    buscando: "Buscando rival… {s} s", esperandoAmigo: "Dile este código a tu amigo. Cuando lo escriba, empezáis.", entrando: "Entrando en el reto…", codigoSinNadie: "No encuentro a nadie con ese código. Revisa que esté bien y que tu amigo siga con la pantalla del código abierta.",
    porWhatsApp: "Mandarlo por WhatsApp", copiar: "Copiar", copiado: "Copiado. Pégalo donde quieras.",
    mensajeReto: "Te reto a un duelo en Final War: Medieval. Entra en {url} y pon el código {codigo} en Duelo online → Jugar con un amigo.",
    codigo: "Código", rivalEncontrado: "¡Rival encontrado! {nombre}", necesitaCuenta: "Para jugar duelos hace falta una cuenta (es tu nombre en el ranking).",
    rivalDesconectado: "Tu rival se ha desconectado. Tiene {s} s para volver.", noCuadra: "La partida no ha salido igual en los dos teléfonos. Mejor empezad otra.", desincronizada: "Las dos partidas no coinciden: duelo anulado, no cuenta.",
    anulada: "Duelo anulado", abandono: "por abandono del rival", rendicion: "te has rendido", rendirse: "Rendirse", confirmarRendirse: "¿Te rindes? El rival gana el duelo.",
    conAmigo: "Jugar con un amigo", igualar: "Igualar héroes", comoEstan: "Como están", igualarPista: "Si lo marcas, los dos jugáis al nivel del héroe más bajo, sin objetos. Si no, cada uno con el nivel que tiene.",
    rankingDuelos: "Duelos", elo: "Elo", liga: "Liga de la semana", ligaPista: "Elo ganado desde el lunes. Al cerrar la semana: 1.º Mandoble, 2.º Égida, 3.º 150 de oro del héroe.", historial: "Tus últimos duelos", revancha: "Revancha", sinDuelos: "Aún no hay duelos.",
    teReta: "{nombre} te reta a un duelo", aceptarReto: "Aceptar", retoEnviado: "Reto enviado a {nombre}. Si está conectado, entra ya; si no, lo verá al abrir el juego.", eloCambio: "Elo {antes} → {despues}",
    ligaPremio: "¡Liga de la semana pasada! Quedaste {pos}.º: {premio}", ganaste: "ganaste", perdiste: "perdiste", marca: "Marca contra {nombre}: {g}-{p}",
    chat: { boton: "Chat", invitar: "{nombre} quiere chatear contigo.", aceptar: "Aceptar", no: "No", pedido: "Invitación enviada. Si {nombre} acepta, se abre el chat.", rechazado: "{nombre} no quiere chatear.", aceptado: "{nombre} ha aceptado el chat.", escribe: "Escribe…", enviar: "Enviar", audioNota: "Nota de voz", audioCorta: "Muy corta: toca el micro, habla y vuelve a tocar para parar.", audioPreparando: "Abriendo micro…", audioGrabandoCorto: "Grabando", audioParar: "Parar", audioBorrar: "Borrar la nota", audioEscuchar: "Escuchar antes de enviar", audioTocar: "Toca para grabar una nota de voz", audioMantener: "Mantén pulsado el micro para grabar", audioGrabando: "Grabando… suelta para enviar (15 s como mucho)", audioSinPermiso: "Sin permiso para usar el micrófono.", audioNoVa: "Este aparato no puede grabar audio aquí.", audioLargo: "La nota de voz es demasiado larga.", audioNoSuena: "No se ha podido reproducir la nota de voz.", audioSilenciada: "Nota de voz (tienes los audios silenciados)", audioSilenciar: "Silenciar los audios", audioActivar: "Activar los audios", audioSilenciados: "Audios silenciados.", audioActivados: "Audios activados.", cerrar: "Cerrar", frases: ["¡Buena partida!", "¡Toma!", "Uy…", "Bien jugado", "GG", "👍", "😅", "⚔️"] },
    otraVersion: "Tu rival tiene otra versión del juego. Cerrad y volved a abrir el juego los dos para actualizarlo.",
    otraVersionCola: "Hay alguien buscando, pero con otra versión del juego. Pídele que cierre y vuelva a abrir el juego.",
    teToca: "¡Te toca!", vamos: "¡Vamos!",
    tuTurno: "¡Te toca! Turno {n}", marcador: "Marcador", yo: "Tú", vas: "vas", primero: "1.º", segundo: "2.º", empate: "empate",
    turnoDe: "Turno de {nombre}", preparado: "¡Preparado!", esperandoRival: "Esperando a {nombre}…", empiezaEn: "Empieza en {s} s", listo: "Listo", enCurso: "Estás en un duelo en directo. Si te vas, tu rival gana.", volverPartida: "Volver a la partida", abandonoPropio: "has abandonado (tres turnos sin jugar)", ultimoAviso: "Otro turno sin hacer nada y pierdes por abandono.", reglasLinea: "{turnos} turnos · {s} s por turno · solo oro · gana quien más puntos tenga", tiempoAgotado: "Se acabó el tiempo: turno terminado.", sinRed: "Sin conexión con la nube.",
  },
  comoSeJuega: "Glosario",
  ajustes: "Ajustes",
  volverInicio: "Inicio",
  volver: "Volver",
  hola: "Hola, {nombre}",
  nombreJugador: "Tu nombre",
  nombrePista: "Para el ranking. Puedes cambiarlo cuando quieras.",
  bandoFavorito: "Bando favorito",
  marcador: "Tu marcador",
  historial: "Últimas partidas",
  sinPartidas: "Todavía no has jugado ninguna partida.",
  rankingOnlinePronto: "El ranking con otros jugadores llegará con la versión online.",
  ganada: "ganada",
  perdida: "perdida",
  subtitulo: "Guerra por hexágonos. Una partida cabe en un café.",
  cuenta: "Cuenta",
  instalar: "Instalar en el móvil",
  instalarIos: "Para instalarlo: pulsa Compartir y luego \"Añadir a pantalla de inicio\".",
  instalado: "Instalado. Ábrelo desde tu pantalla de inicio.",
  crearCuenta: "Crear cuenta",
  crearCuentaOEntrar: "Crear cuenta o entrar",
  cuentaReclamo: "¿Quieres salir en el ranking?",
  entrar: "Entrar",
  salir: "Salir",
  correo: "Correo",
  clave: "Contraseña",
  olvideClave: "He olvidado la contraseña",
  claveEnviada: "Te hemos enviado un correo para cambiarla.",
  seguirSinCuenta: "Seguir sin cuenta",
  paraRanking: "Para aparecer en el ranking con otros jugadores, crea una cuenta o entra. Jugar no la necesita.",
  yaTengoCuenta: "Ya tengo cuenta",
  noTengoCuenta: "No tengo cuenta",
  conectadoComo: "Conectado como",
  rankingSemana: "Semana",
  rankingTotal: "Total",
  rankingHoy: "Hoy",
  rankingMejor: "Mejor partida",
  rankingDia: "Mapa del día",
  dueloEnCurso: "Duelo en curso", dueloVolver: "Volver al duelo", dueloRelojSigue: "El reloj sigue corriendo: tu rival te espera.",
  rankingDiaPista: "Mejor partida de hoy en el mapa del día. Mismo mapa para todos; cambia a medianoche.",
  mapaDelDia: "Mapa del día",
  mapaDelDiaPista: "El mismo mapa para todos hoy. Tu mejor partida entra en el ranking del día.",
  diasSeguidos: "{n} días seguidos",
  rachaDias: { dias: "Racha: {n} días seguidos", uno: "Racha: 1 día", hoy: "juega hoy para mantenerla", hecha: "hoy ya cuenta", empieza: "Juega una partida hoy y empieza tu racha", nuevoDia: "Nuevo día: misiones y mapa del día nuevos." },
  dificil: "Difícil",
  dificultadPista: { facil: "Rivales torpes: para aprender.", normal: "Rivales con criterio, cada uno con su carácter.", dificil: "Rivales implacables: van a por ti, cazan a tu héroe, pisan cada punto clave y empiezan con un 25 % más de oro." },
  escenarios: { boton: "Grandes batallas", titulo: "Grandes batallas", pista: "Mapas históricos grandes: cada reino empieza en su tierra. Mismas reglas, mucho más sitio y muchos más turnos.", jugar: "Jugar el escenario", reinos: "{n} reinos", turnos: "{n} turnos", tuBando: "Tu reino", bandoPista: "Tu bando decide dónde empiezas.", tuTierra: "Dónde empiezas", tierraPista: "Juegas con tu facción en la tierra de ese reino; los demás reinos del mapa los lleva la máquina.", aviso: "Geografía inspirada en la real: los brazos de mar se cierran con pasos de tierra porque aquí no hay barcos." },
  resistir: { boton: "Resistir", titulo: "Modo Resistir", pista: "Empiezas en el centro del valle. Desde la segunda ronda entran hordas por los bordes, cada vez más y por más lados. Aguanta lo que puedas, solo o con un amigo.", jugar: "Resistir solo", ronda: "Ronda", llegaOleada: "¡Llega la oleada {n}! Ronda {ronda}", aguantaste: "Aguantaste {n} rondas", record: "Tu récord: {n} rondas", nuevoRecord: "¡Récord nuevo: {n} rondas!", sinRecord: "Aún no has resistido ninguna.", ranking: "Resistir", rankingPista: "Rondas aguantadas en el modo Resistir. Al lado de cada jugador, el nivel de su héroe.", proxima: "Siguiente oleada: ronda {ronda}, por {lados} lado(s)", consejo: "Pierdes cuando cae tu capital. Puedes fundar más pueblos para ganar oro, pero defiende la capital: es lo único que te mantiene en pie." },
  // ---- Batalla: montarte tú la partida (21 sep 2026). "Resistir" es un tipo de batalla más ----
  guion: { refuerzosEnemigos: "¡Le llegan refuerzos al enemigo!", refuerzosTuyos: "¡Te llegan refuerzos!", traicion: "¡Te han traicionado!", vuelveContigo: "¡Vuelve a tu bando!", seRetira: "Uno de ellos se retira de la pelea", objetivoNuevo: "El objetivo ha cambiado" },
  objetivos: {
    aguantar: "Aguanta {n} turnos más", romper: "Acaba con ellos antes de que pasen {n} turnos", aguantarCapital: "Aguanta {n} turnos más sin perder {sitio}", romperCapital: "Toma {sitio} antes de que pasen {n} turnos",
    tomar: "Conquista {sitio}, el pueblo de {dueno}", tomarSolo: "Conquista {sitio}", defender: "No pierdas {sitio}", heroe: "Mata al héroe rival y cuida el tuyo", heroeN: "Mata a los héroes rivales (quedan {n}) y cuida el tuyo",
    clave: "Consigue {n} casillas con estrella (tienes {tengo}) y que sigan siendo tuyas {turnos} turnos", escapar: "Lleva a tu héroe a una casilla con bandera 🚩", escaparLejos: "Lleva a tu héroe a una casilla con bandera 🚩", escaparLado: { norte: "Lleva a tu héroe a una casilla con bandera 🚩 (arriba)", sur: "Lleva a tu héroe a una casilla con bandera 🚩 (abajo)", este: "Lleva a tu héroe a una casilla con bandera 🚩 (a la derecha)", oeste: "Lleva a tu héroe a una casilla con bandera 🚩 (abajo a la izquierda)" },
    cazar: "No dejes escapar a su héroe", conquista: "Acaba con todos, o ten más puntos al acabar el turno {n}", conquistaSinLimite: "Acaba con todos los demás reinos",
  },
  batallas: {
    boton: "Batalla", titulo: "Monta tu batalla", pista: "Elige cómo se pelea, cuántos juegan y quién va con quién.",
    tipo: "Tipo de batalla", equipos: "Equipos", equipo: "Equipo {n}", tu: "Tú", maquina: "Máquina", maquinas: "{n} máquinas", turnosN: "{n} turnos",
    tipos: {
      conquista: { nombre: "Conquista", pista: "La de siempre: cada uno con su pueblo. Gana quien queda en pie, o quien más puntos tenga al acabar los turnos." },
      campo: { nombre: "Campo de batalla", pista: "Sin pueblos: cada uno con su ejército. Gana quien barra al otro. No se recluta: lo que tienes es lo que hay." },
      asalto: { nombre: "Asalto", pista: "Entras con un ejército y el otro tiene pueblos. Ganas si le tomas la capital; si quieres más tropas, tendrás que conquistar." },
      resistir: { nombre: "Resistir", pista: "Tu pueblo en el centro y hordas que entran por los bordes, cada ronda más fuertes. Aguanta lo que puedas." },
      heroes: { nombre: "Duelo de héroes", pista: "Ejércitos pequeños. Gana quien mate al héroe del otro: cuida el tuyo." },
      clave: { nombre: "Puntos clave", pista: "Como la conquista, pero se gana controlando dos puntos clave del mapa dos turnos seguidos." },
    },
  },
  campana: { queHacer: "Qué tienes que hacer", contra: "Contra quién", consejo: "Consejo", seguir: "Siguiente capítulo", repetirCap: "Repetir el capítulo", volver: "Volver a la campaña", conSuFaccion: "Esta campaña se juega con {nombre}.", comoGanar: "Ganas si acabas con todos los rivales o si, al terminar los {t} turnos, eres quien más puntos tiene.", comoGanarPor: { aguantar: "Ganas si sigues en pie al acabar el turno {n}.", escapar: "Ganas si tu héroe sale del mapa por donde se indica. Si se acaban los {t} turnos sin salir, pierdes.", tomar: "Ganas si tomas su pueblo principal. Si se acaban los {t} turnos sin tomarlo, pierdes.", clave: "Ganas si tienes {n} puntos clave durante {x} turnos seguidos. Si se acaban los {t} turnos, gana quien más puntos tenga.", heroe: "Ganas si matas a su héroe y conservas el tuyo. Si se acaban los {t} turnos, gana quien más puntos tenga.", campo: "Ganas si acabas con su ejército. Si se acaban los {t} turnos, gana quien más puntos tenga." }, torre: "La Torre del Cuervo", boton: "Campaña", titulo: "Campaña", pista: "Diez mapas hechos a mano, cada uno más difícil que el anterior. Cada mapa superado da su premio una sola vez.", progreso: "{n} de {t} mapas superados", mapa: "Mapa {n}", jugar: "Jugar", repetir: "Repetir", bloqueado: "Supera el mapa anterior", superado: "Superado", premio: "Premio", superadoCer: "Campaña: mapa {n} superado", completa: "Campaña completa. ¡Enhorabuena!", rivales: "{n} rival(es) · {d} · {t} turnos" },
  batalla: { boton: "Batalla semanal", titulo: "Batalla de la semana", noEsSimulacion: "Mapa inspirado en la batalla, no una recreación exacta.", pista: "Un mapa hecho a mano con reglas propias. Cambia cada lunes; tu mejor partida entra en el ranking de la semana.", ranking: "Batalla", rankingPista: "Mejor partida de esta semana en la batalla semanal. Cambia el lunes.", cambia: "Cambia en {n} días", cambiaManana: "Cambia mañana", tuSemana: "Esta semana: {n} partida(s) · mejor {m} puntos", sinJugar: "Aún no la has jugado esta semana.", jugar: "Jugar la batalla", verRanking: "Ver ranking", mejorSemana: "Batalla de la semana: mejor {n}", reglas: "Reglas", oroTriple: "oro ×3", mitadOro: "mitad de oro" },
  musicaEstado: { linea: "Música: {estado} · {escena} · {fichero} · segundo {segundo} (toca para actualizar)", sonando: "sonando", pausada: "parada", dormida: "en pausa porque la ventana no está delante", silenciada: "silenciada", respaldo: "sonando la de respaldo", nada: "sin pista", enMenu: "menú", enPartida: "partida" },
  secciones: { modos: "Modos de juego", estaSemana: "Esta semana", tuProgreso: "Lo tuyo",
    queCampana: "Siete historias, diez mapas cada una", queBatallas: "Móntala tú: tipo, jugadores y equipos", queResistir: "Aguanta las oleadas", queEscenarios: "Europa, la Península, Britannia", queDuelo: "Uno contra uno, en directo",
    queDia: "El mismo mapa para todo el mundo, hoy", queBatalla: "Una batalla histórica, hasta el lunes",
    deMapas: "{n} de {t} mapas", 
    sinRecord: "Sin récord todavía", tresMapas: "Tres mapas grandes", enDirecto: "En directo", mismoParaTodos: "Cambia cada día" },
  sala: { boton: "Jugar con un amigo", esperando: "Esperando a tu amigo…",
    puestoAmigo: "Tu amigo entra en el puesto 1. Si quieres que juegue contigo, ponle tu mismo equipo antes de invitarle.",
    mensaje: "¿Jugamos una batalla en Final War: Medieval? Entra en {url}, ve a Batalla y pon el código {codigo}." },
  coop: { boton: "Jugar a dobles", titulo: "Resistir a dobles", pista: "Dos jugadores contra las hordas, cada uno con su pueblo en el centro del valle. Se aguanta o se cae juntos.",
    tengoCodigo: "¿Te han mandado un código? Entra aquí:",
    mensajeCoop: "¿Aguantamos juntos las hordas en Final War: Medieval? Entra en {url}, ve a Resistir y pon el código {codigo}.",
    reglasLinea: "{s} s por turno · se aguanta o se cae juntos", poniendoAlDia: "Poniendo la partida al día con tu compañero…", puestaAlDia: "Partida puesta al día: los dos veis lo mismo.", companeroSeFue: "{nombre} se ha ido. Su reino lo lleva la máquina hasta que vuelva.", turnoDe: "Turno de {nombre}", aguantasteis: "Aguantasteis {n} rondas", record: "Vuestro récord a dobles: {n} rondas", juntos: "Juntos", bajas: "bajas" },
  // ---- facciones, tienda, Leyenda y cuenta (13 sep 2026) ----
  facciones: {
    titulo: "Facciones", boton: "Facciones", elegir: "Elige tu facción",
    elegirPista: "Tu facción decide cómo juegas: su líder es tu héroe, tiene su propia unidad y su propia escalera de once niveles. Empieza con una de las dos gratis; las otras cinco las verás en la tienda.",
    gratis: "Gratis", tuya: "Tuya", deLaTienda: "De la tienda", jugarCon: "Jugar con {nombre}", esteEsLaMia: "Esta es la mía", juegasCon: "Juegas con", cambiarCorto: "Cambiar", verOtras: "Ver otras facciones", cuentaLinea: "Cuenta nivel {n} · {oro} oro", puntosPorGastar: "{lider}: {n} punto(s) por gastar", puntosCorto: "{n} punto(s) por gastar", cambiarCampana: "Esta campaña se juega con {faccion} ({lider}, nivel {n}). ¿Cambiar a {faccion}?", cambiarYJugar: "Cambiar y jugar", diaCon: "El mapa de hoy se juega con {a} o {b}. Juegas con {nombre} ({lider}, nivel {n}).", cambiar: "Cambiar de facción", ver: "Ver", verTodas: "Ver las seis",
    lider: "Líder", estilo: "Estilo", pais: "Hoy", rasgo: "Rasgo", poder: "Poder del líder", poderDesde: "desde el nivel 5 · una vez por partida", unidad: "Unidad propia", unidadDesde: "desde el nivel 1",
    comparada: "Comparada con {tropa}", mejor: "Hace mejor", peor: "Hace peor", curtida: "Nivel 3 · curtida", maestra: "Nivel 7 · maestra", noTiene: "No tiene", noTienePista: "Cuando le toca un nivel con una tropa que no tiene, gana un punto de mejora extra.",
    masDetalles: "Más detalles", menosDetalles: "Ocultar detalles",
    heroe: "Su héroe", escalera: "Su escalera", campana: "Su campaña: diez capítulos, incluida", nivel: "Nivel {n}", tuNivel: "Tu nivel con {nombre}: {n}",
    doble: "×2: sube el doble de rápido hasta alcanzar a tu mejor facción", 
    hito: { unidad: "{unidad} y el rasgo «{rasgo}»", curtida: "{unidad}, curtida: {que}", poder: "Poder del líder: {poder}", maestra: "{unidad}, maestra: {que}", techo: "El poder, dos veces por partida, y {unidad} de oro" },
    abre: "Abre: {tropas}", sinTropa: "sin {tropa}: +1 punto de mejora", gala: "Armadura de gala y estandarte (aspecto)", nada: "Puntos de mejora",
    habilidades: { firme: "+{n} de defensa pegado a un pueblo tuyo", sanaEnCasa: "cura {n} cada turno en tu tierra", auraDefensa: "+{n} de defensa a las tropas pegadas", curaAlMatar: "cura {n} al matar", estacas: "la caballería que le ataca recibe {n} de daño", oroPorHexEnemigo: "+{n} de oro por cada hexágono enemigo que pisa", trasAtaque: "puede moverse después de atacar", contraHeridos: "+{n} de ataque contra tropas heridas", furia: "+{n} de ataque por cada {v} de vida perdida (hasta +{t})", movimiento: "+{n} casilla de movimiento", bonos: "+{n} contra {etiqueta}", defensaContra: "+{n} de defensa contra {etiqueta}" },
    tienda: "Tienda de facciones", tiendaPista: "Cada facción de pago trae su líder, su unidad, su escalera y su campaña. Aquí no se paga por ganar: las facciones de pago son distintas, no más fuertes.",
    comprar: "Comprar · {precio}", pack: "Las cinco de pago · {precio}", packPista: "Inglaterra, Malí, Saladino, los mongoles y las tribus eslavas juntos.", conOro: "Con oro del héroe · {n}", conOroPista: "Tienes {n} de oro del héroe.",
    enLaApp: "Consíguela en la app", enLaAppPista: "En la web se juega con las dos facciones gratis. Las de pago están en la app de Google Play y de la App Store.",
    restaurar: "Recuperar compras", restaurado: "Compras recuperadas.", restaurarFallo: "No se han podido recuperar: {error}",
    modoPrueba: "Modo prueba: la tienda de verdad aún no está conectada, así que comprar no cobra nada.",
    comprada: "¡Ya tienes {nombre}!", compraFallo: "No se ha podido comprar: {error}", cancelada: "Compra cancelada.", comprando: "Comprando…",
    regalo: "Te regalamos {nombre}: tu héroe {clase} ahora es su líder, con todo tu progreso.",
    reto: "Esta semana se juega con:", hoyCon: "Hoy: {a} o {b}",
    nuevaVersion: "Novedad: facciones", nuevaVersionTexto: "Ahora eliges facción, y su líder es tu héroe. Tu progreso sigue en {nombre}.",
  },
  leyenda: { titulo: "La Leyenda de Final War", eres: "Eres la Leyenda de Final War", nueva: "{nombre} es la nueva Leyenda de Final War", perdida: "Te han quitado la Leyenda: {nombre} tiene ahora más puntos que tú.",
    requisito: "El nivel 11, y solo lo tiene una persona en todo el juego: quien ha llegado al nivel 10 con cualquier facción y tiene más puntos que nadie en los últimos 12 meses.",
    comoSeLlega: "nivel 10 y más puntos que nadie en 12 meses", enLaEscalera: "Estrella roja y nombre dorado en el ranking y en los duelos; juega con todo lo del Emperador. Solo puede haber una Leyenda en todo el juego",
    sala: "Sala de Leyendas", dias: "{n} días", desde: "desde el {fecha}", ahora: "Ahora", sinLeyenda: "Todavía nadie ha llegado a ser la Leyenda.", actual: "La Leyenda ahora: {nombre}", puntos12: "{n} puntos en 12 meses" },
  cuentaNivel: { titulo: "Tu cuenta", nivel: "Nivel de cuenta {n}", pista: "Sube con todo lo que juegas, con cualquier facción: cada nivel da 60 de oro del héroe, cada 5 un aspecto y cada 10 más oro al empezar las partidas.", sube: "Nivel de cuenta {n}: +{oro} de oro del héroe", aspecto: "Aspecto nuevo: {nombre}", oroInicial: "+{n} de oro al empezar cada partida", siguiente: "Siguiente nivel a {n} puntos" },
  poderes: { boton: "Poder", usar: "Usar {nombre}", confirmar: "¿Usar «{nombre}»? {texto}", quedan: "Te queda {n} uso", quedanVarios: "Te quedan {n} usos", gastado: "Ya has usado el poder del líder en esta partida.", activo: "{nombre}: en marcha hasta tu próximo turno", bloqueado: "El poder del líder se abre en el nivel 5 de la facción." },
  medallas: "Medallas",
  conectado: "Conectado",
  cambiarFigura: "Cambiar figura",
  tuFigura: "Tu figura",
  escalonAspirante: "Recluta",
  medallaNueva: "Medalla nueva",
  victoria: "¡Victoria!",
  derrota: "Derrota",
  posiciones: ["Primero", "Segundo", "Tercero", "Cuarto", "Quinto", "Sexto", "Séptimo", "Octavo"],
  tuTotal: "Tu total",
  verResumen: "Ver resumen",
  repeticion: { boton: "Ver repetición", titulo: "Repetición", turnos: "{n} turnos guardados", reproducir: "▶ Reproducir", pausa: "❚❚ Pausa" },
  compartir: { boton: "Compartir", titulo: "Tu partida", texto: "{puntos} puntos en {mapa}. Final War: Medieval.", guardar: "Mantén pulsada la imagen para guardarla o copiarla.", descargar: "Descargar" },
  medallasPista: "{n} de {total}",
  nivelesMedalla: ["Bronce", "Plata", "Oro"],
  siguienteObjetivo: "Siguiente",
  nivelMaximo: "Nivel máximo",
  rankingSumaPista: "Suma de los puntos de todas tus partidas.",
  rankingMejorPista: "Tu mejor puntuación en una sola partida.",
  tuPosicion: "Tu posición",
  sinRanking: "Todavía no hay partidas en el ranking. ¡Sé el primero!",
  nubeCargando: "Conectando con la nube…",
  sinConexion: "Sin conexión con el ranking. Tus puntos se guardan en el aparato y se enviarán cuando haya red.",
  guardarEnRanking: "Guardar en el ranking",
  enviadoRanking: "Enviado al ranking",
  pendienteRanking: "Se enviará al ranking cuando entres con tu cuenta",
  errCorreoUsado: "Ese correo ya tiene cuenta. Prueba a entrar.",
  errCredenciales: "Correo o contraseña incorrectos.",
  errClaveCorta: "La contraseña necesita al menos 6 caracteres.",
  errCorreo: "Ese correo no parece válido.",
  errDemasiado: "Demasiados intentos. Espera un minuto.",
  errRed: "No hay conexión. Inténtalo más tarde.",
  errNombre: "Pon un nombre de 2 a 20 letras.",
  iaEtiqueta: "IA",
  iaUltimaPartida: "Los jugadores marcados IA son tus rivales de la última partida.",
  escalon: "Escalón",
  teFaltan: "Te faltan {n} puntos para {nombre}.",
  tutorial: "Tutorial",
  saltarTutorial: "Saltar", minimizar: "Minimizar", maximizar: "Ver de nuevo",
  entendido: "¡Entendido!",
  primeraVez: "¿Primera vez? El tutorial son tres minutos jugando.",
  jugarDirecto: "Jugar directamente",
  tutorialPasos: {
    seleccionar: "Este es tu pueblo: la estrella lo marca como capital. Tu héroe está dentro. Toca el circulito que señala la flecha (la guarnición, 1/1) para sacarlo.",
    mover: "Los hexágonos claros son adonde puede ir. Toca el que señala la flecha: pisar un hexágono lo hace tuyo, y las monedas (minas) y estrellas (puntos clave) valen puntos.",
    finTurno: "Cada turno tu reino ingresa oro (arriba a la izquierda). Pulsa Fin de turno, donde apunta la flecha, para ver jugar al rival.",
    reclutar: "Toca los martillos que señala la flecha y elige un campesino: 10 oro. Los soldados solo se reclutan en ciudades y castillos.",
    explorar: "Manda tropas a las minas y estrellas que señala la flecha: valen puntos al final. Con 40 oro, la flecha azul del pueblo lo hace ciudad. Juega unos turnos.",
    atacar: "Ataca: selecciona una tropa y toca al enemigo que señala la flecha (los enemigos atacables salen en rojo). Verás el daño antes de confirmar. Cuerpo a cuerpo hay contraataque; los arqueros disparan sin recibirlo. Cuida a tu héroe: si muere, no vuelve.",
    final: "Para tomar un pueblo enemigo: mata a la guarnición, deja las murallas a cero (asedio) y entra. Gana quien más puntos tenga al turno 15 o quien elimine a los demás. ¡Suerte!",
  },
  jugador: "Jugador",
  tu: "Tu reino",
  ia: "IA",
  hexagono: "Hexágono",
  hexagonos: "Hexágonos",
  heroesMatados: "Héroes abatidos",
  verDetalle: "Ver el detalle", sano: "sano", detalleCorto: "más", fundarCorto: "Pueblo", atrincherarCorto: "Atrinch.", licenciarCorto: "Licenciar", reclutarCorto: "Reclutar", lineaVacia: "Toca una tropa o un pueblo para ver qué puede hacer.", sinDueno: "Sin dueño", iasJugando: "Los rivales están jugando…",
  oroDisponible: "Tienes {n} de oro.",
  confirmarCiudad: "¿Mejorar a ciudad por {n} de oro? Más guarnición, más murallas y recluta de todo.",
  rapidaResumen: "Partida rápida: {n} turnos, solo oro. Gana quien más puntos tenga.",
  heroe: "Héroe",
  nadie: "Sin dueño",
  de: "de",
  vida: "Vida",
  ataque: "Ataque",
  defensa: "Defensa",
  asedio: "Asedio",
  alcance: "Alcance",
  movimiento: "Movimiento",
  mantenimiento: "Mantenimiento",
  coste: "Coste",
  produce: "Produce",
  murallas: "Murallas",
  capital: "Capital",
  aislado: "Aislado",
  almacen: "Almacén",
  guarnicion: "Guarnición",
  construcciones: "Construcciones",
  vacio: "vacío",
  reclutar: "Reclutar",
  mejorarTropa: "Mejorar tropa",
  mejorarACiudad: "Mejorar a ciudad",
  construirCastillo: "Construir castillo",
  reclamar: "Reclamar",
  fundar: "Fundar",
  castillo: "Castillo",
  fundarPueblo: "Fundar pueblo",
  salir: "Salir",
  atrincherar: "Atrincherarse",
  atrincherada: "Atrincherada",
  irA: "Ir a…",
  irAPista: "Toca el hexágono de destino. La tropa irá sola cada turno.",
  destino: "Destino",
  cancelarDestino: "Cancelar destino",
  enemigoCerca: "se detiene: enemigo cerca",
  siguienteTropa: "Siguiente tropa",
  tropasPendientes: "Tienes {n} tropa(s) que aún pueden actuar.",
  verTropa: "Ver tropa",
  terminarIgual: "Terminar igualmente",
  reino: "Reino",
  tesoro: "Tesoro",
  hucha: "Tienes",
  entraPorTurno: "Ingresos",
  salePorTurno: "Gastos",
  balance: "Balance",
  recurso: "Recurso",
  enCurso: "en curso",
  hechas: "hechas",
  cadaUno: "a {n} cada uno",
  neto: "Neto",
  porQue: "por qué",
  sinIngresos: "Nada",
  yacimientosParados: "Yacimientos que no producen",
  zonasAisladas: "Zonas aisladas",
  asentamientos: "Asentamientos",
  tropas: "Tropas",
  tecnologias: "Tecnologías",
  tuReinoEs: "Juegas con {reino}, el reino {color}. Tu capital: {capital}.",
  idioma: "Idioma", idiomaAviso: "El juego se recargará para cambiar el idioma.",
  fichas: {
    mantenimientoCorto: "mant.",
    sinGuarnicion: "Sin guarnición: si abren brecha, el enemigo entra andando.", sinGuarnicionBrecha: "Sin guarnición y con brecha: el enemigo entra andando.",
    sinInvestigarNada: "No estás investigando nada.", esTecnologia: "{nombre} (tecnología)", delHeroe: " del héroe",
    nombresAsent: "Nombres de asentamiento", cuerpoACuerpo: "cuerpo a cuerpo", seReclutaEn: "Se recluta en", mejoraA: "Mejora a", especial: "Especial",
    puedeFundar: "Puede fundar pueblos", noMoverDisparar: "No puede moverse y disparar en el mismo turno", comoSeConsigue: "Cómo se consigue",
    loFunda: "Lo funda un campesino", mejorando: "Mejorando un {que}", seConstruye: "Se construye en un hexágono tuyo vacío",
    huecosGuarnicion: "Huecos de guarnición", plusDefensa: "Plus de defensa", reclutaFicha: "Recluta", todasLasTropas: "Todas las tropas",
    mejoraTropas: "Mejora tropas", si: "Sí", no: "No", alConquistarlo: "Al conquistarlo", pasaA: "Pasa a {que}", tarda: "Tarda", desbloquea: "Desbloquea",
    mover: "Mover", noSePuede: "no se puede", unaCasilla: "una casilla, como siempre", teParas: "al entrar, se acaba tu movimiento", casilla1: "1 casilla por turno", casillasN: "{n} casillas por turno", sePuedeConstruir: "Se puede construir",
    carreteraDesc: "La construye un campesino en un hexágono tuyo. Entrar cuesta {n} punto. Los asentamientos cuentan como carretera.",
    aLaGuarnicion: "a la guarnición", brechaSinPlus: "brecha: sin plus", pistaMover: "Toca un hexágono claro para mover, rojo para atacar, naranja para asediar.",
    noProduce: "No produce: no está conectado a un asentamiento.", tuMayus: "Tú", mantCadaUna: "{n} cada una; la mitad si está acuartelada" },
  legal: "Legal", verPrivacidad: "Política de privacidad", verCondiciones: "Condiciones de uso", version: "Versión",
  borrarCuenta: "Borrar mi cuenta", borrarCuentaAviso: "Se borra tu cuenta, tu héroe, tus puntuaciones y tus duelos. No se puede deshacer y no se puede recuperar.", borrarCuentaConfirmar: "¿Seguro que quieres borrar tu cuenta y todo tu progreso?", borrarCuentaHecho: "Cuenta borrada. Tu progreso en este dispositivo sigue aquí.", borrarCuentaError: "No se ha podido borrar. Escribe a {contacto} y la borramos a mano.",
  aceptasAlCrear: "Al crear la cuenta aceptas las {condiciones} y la {privacidad}.",
  paleta: "Colores", paletaNormal: "Normales", paletaDaltonicos: "Para daltonismo", paletaPista: "Cambia los colores de los reinos por otros que se distinguen sin ver bien el rojo y el verde.",
  colorAzul: "azul",
  colorRojo: "rojo",
  colorVerde: "verde",
  tuSufijo: "(tú)",
  tuCapital: "Tu capital",
  mapaNumero: "Mapa nº",
  mapa: "Mapa",
  mapaAleatorio: "Aleatorio",
  avanzado: "Avanzado",
  puedeMoverse: "Puede moverse ({n})",
  contraGuarnicion: "Contra la guarnición",
  contraMurallas: "Contra las murallas",
  sinContraataque: "sin contraataque",
  quitas: "Quitas",
  explicaAtaque: "Atacar guarnición golpea a la tropa de dentro (protegida por las murallas mientras estén en pie). Asediar golpea a las murallas.",
  reporte: { boton: "Informar de un problema o sugerencia", titulo: "Informar de un problema o sugerencia", problema: "Algo falla", sugerencia: "Tengo una idea", queHaPasado: "Cuéntanos qué ha pasado y qué estabas haciendo.", queMejorarias: "¿Qué mejorarías o qué te gustaría que tuviera el juego?", conPartida: "Se enviará también cómo está tu partida ahora, para poder verlo.", enviar: "Enviar", vacio: "Escribe algo antes de enviar.", gracias: "¡Gracias! Lo miraremos.", guardado: "Ahora no hay conexión: se enviará solo en cuanto haya internet." },
  glosario: "Glosario", objetivoBoton: "Objetivo",
  carretera: "Carretera",
  construirCarretera: "Construir carretera",
  terreno: "Terreno",
  pasos: "pasos",
  conCarretera: "con carretera",
  experiencia: "Experiencia",
  salida: "Salida: ataca desde dentro sin el plus de las murallas en este intercambio. Si mata, sale al hexágono.",
  personalidades: { equilibrada: "equilibrada", guardiana: "guardiana", expansionista: "expansionista", belicosa: "belicosa", implacable: "implacable" },
  sobre: "Sobre",
  sinInvestigar: "No estás investigando nada. Puedes empezar {tec} ({coste}).",
  verTecnologias: "Ver tecnologías",
  buscar: "Buscar…",
  pestanas: { facciones: "Facciones", bandos: "Bandos", tropas: "Tropas", asentamientos: "Asentamientos", tecnologias: "Tecnologías", recursos: "Recursos", terrenos: "Terrenos", reglas: "Reglas" },
  verEnGlosario: "Ver en el glosario",
  licenciar: "Licenciar",
  deserta: "deserta",
  bancarrotaAviso: "¡Bancarrota! {n} tropas desertan por falta de oro.",
  bancarrotaAvisoUna: "¡Bancarrota! {tropa} deserta por falta de oro.",
  bancarrotaFin: "Bancarrota a la vista: el próximo turno te faltarán {oro} de oro y desertarán {n} tropas (las más baratas primero). Licencia tropas o consigue oro.",
  verReino: "Ver reino",
  licenciarConfirmar: "¿Disolver esta tropa? No se devuelve nada.",
  ingresos: "Ingresos",
  gastos: "Gastos",
  porTurno: "por turno",
  atacar: "Atacar",
  asediar: "Asediar",
  atacarGuarnicion: "Atacar guarnición",
  cancelar: "Cancelar",
  confirmar: "Confirmar",
  haces: "Haces",
  recibes: "Recibes",
  hiciste: "Hiciste",
  recibiste: "Recibiste",
  a: "a",
  yaActuo: "Ya ha actuado",
  sinMovimiento: "Sin movimiento",
  puedeActuar: "Puede actuar",
  investigando: "Investigando",
  investigar: "Investigar",
  investigado: "Investigado",
  turnos: "turnos",
  requiere: "Requiere",
  disponible: "Disponible",
  bloqueado: "Bloqueado",
  nada: "Nada",
  cerrar: "Cerrar",
  ganaste: "¡Has ganado!",
  perdiste: "Has sido eliminado.",
  gano: "ha ganado la partida.", victoriaPara: "Victoria para {nombre}",
  eliminado: "eliminado",
  jugadores: "Rivales",
  empezar: "Empezar partida",
  continuar: "Continuar partida",
  tamanoMapa: "Tamaño del mapa",
  dificultad: "Dificultad",
  tipoPartida: "Tipo de partida",
  tuBando: "Tu bando",
  bando: "Bando",
  bandoAleatorio: "Aleatorio",
  bandoAleatorioPista: "Te toca un bando al azar. Cada bando tiene un rasgo propio; míralos en el glosario.",
  limiteTurnos: "Turnos", finPartida: "Fin de la partida", finPuntos: "Por puntos", finEliminacion: "Por eliminación",
  finPuntosPista: "Al acabar el turno {n} gana quien más puntos tenga. Antes gana quien elimine a los demás.",
  finEliminacionPista: "Sin límite de turnos: se juega hasta que solo quede un reino en pie. Puede durar mucho.",
  sinLimite: "Sin límite",
  puntos: "Puntos", rival: "rival",
  victoriaPorPuntos: "Por puntos, al acabarse los turnos", objetivoFallido: "Se acabaron los turnos sin cumplir el objetivo", capitalPerdida: "Cayó el pueblo principal que había que defender",
  rasgo: "Rasgo",
  bonoContra: "+{n}: {atacante} contra {etiqueta}",
  defensaContraTxt: "+{n} defensa de {defensor} contra {etiqueta}",
  defensaContra: "Defensa contra",
  bonusContra: "Bonus contra",
  etiquetasNombre: { heridas: "tropas heridas", lanza: "lanza", espada: "espada", montada: "caballería", armadura: "armadura", a_pie: "infantería", a_distancia: "tropas a distancia", ligera: "tropas ligeras", maquina: "máquinas" },
  tipos: { rapida: "Rápida", normal: "Lenta", personalizada: "Personalizada", dia: "Mapa del día", duelo: "Duelo", campana: "Campaña", batalla: "Batalla semanal", escenario: "Gran batalla", resistir: "Resistir" },
  conquistas: "Conquistas",
  matadas: "Bajas causadas",
  perdidas: "Bajas sufridas",
  oroGanado: "Oro ganado",
  lineaTiempo: "Asentamientos por turno",
  records: "Récords",
  partidas: "partidas",
  ganadas: "ganadas",
  racha: "racha",
  mejorRacha: "mejor",
  mejorVictoria: "mejor victoria",
  puntosHoy: "hoy",
  puntosSemana: "esta semana",
  puntosTotal: "en total",
  mejorPartida: "mejor partida",
  revancha: "Revancha (mismo mapa)",
  otraPartida: "Otra partida",
  rapida: "Rápida",
  normalPartida: "Lenta",
  personalizada: "Personalizada",
  opcionesPersonalizadas: "tamaño, tecnología, hucha, recursos, mapa",
  huchaInicial: "Hucha inicial",
  huchaNormal: "Normal",
  huchaDoble: "Doble",
  huchaTriple: "Triple",
  arbolCompleto: "Árbol completo (se investiga)",
  todoDesbloqueado: "Todo desbloqueado (partida rápida)",
  recursosMapa: "Recursos",
  equilibrados: "Equilibrados (lo mismo cerca de cada capital)",
  aleatorios: "Aleatorios",
  facil: "Fácil",
  normal: "Normal",
  pequeno: "Pequeño",
  mediano: "Mediano",
  grande: "Grande",
  semilla: "Semilla",
  registro: "Registro",
  ayuda: "Ayuda",
  ayudaTexto: [
    "Toca una tropa tuya para ver adónde puede ir y a quién puede atacar.",
    "Pisar un hexágono lo hace tuyo.",
    "Las minas de oro producen si están unidas a un asentamiento tuyo.",
    "Un campesino puede fundar un pueblo en un hexágono tuyo vacío.",
    "Mete tropas en tus asentamientos: sin guarnición y con las murallas a cero, el enemigo entra andando.",
    "Las catapultas rompen murallas. La infantería también, pero muy despacio.",
    "Si no puedes pagar el mantenimiento, desertan tropas hasta que puedas.",
  ],
  errores: {
    sin_accion: "Esa tropa ya ha actuado este turno. Elige otra o termina el turno.",
    sin_movimiento: "Ya no puede moverse más este turno. Termina el turno y volverá a moverse.",
    no_es_tuya: "No es tuya.",
    hex_ocupado: "Ese hexágono está ocupado.",
    fuera_de_alcance: "Está lejos: acércate un hexágono más.",
    sin_recursos: "Te falta oro. Termina el turno para cobrar, o licencia una tropa.",
    sin_tecnologia: "Te falta una tecnología.",
    nivel_heroe: "Tu facción aún no tiene nivel para esta tropa.",
    sin_oro: "No tienes oro del héroe suficiente.", ya_tienes: "Ya lo tienes.", no_se_vende: "No se vende.", no_tienes: "No lo tienes.", sin_puntos: "No tienes puntos de mejora.", tope: "Ya está al máximo.", requiere: "Falta otra mejora antes.",
    sin_hueco: "No hay sitio: la guarnición está llena y los hexágonos de alrededor, ocupados. Saca una tropa fuera.",
    ya_reclutado: "Ya ha reclutado este turno. Podrá otra vez el turno que viene.",
    demasiado_cerca: "Demasiado cerca de otro asentamiento.",
    no_puede_fundar: "Esta tropa no puede fundar.",
    ya_es_tuyo: "Ya es tuyo.",
    no_desde_dentro: "Las tropas cuerpo a cuerpo tienen que salir para atacar.",
    catapulta_movida: "La catapulta no puede moverse y disparar en el mismo turno.",
    no_hay_objetivo: "No hay objetivo.",
    ya_investigando: "Ya estás investigando algo.",
    ya_atrincherada: "Ya está atrincherada.",
    ya_hay_carretera: "Ya hay carretera.",
    no_aqui: "Solo en {donde}.",
    no_se_puede: "No se puede.",
    hex_no_tuyo: "El hexágono no es tuyo: písalo primero.",
    terreno_no_construible: "No se construye en este terreno.",
    solo_acuartelada: "Solo dentro de una ciudad: métela en la guarnición.",
    solo_en_ciudad: "Solo en una ciudad, no en {tipo}.",
    no_se_atrinchera: "La caballería no se atrinchera.",
    falta_campesino: "Hace falta un campesino encima: él lo construye y se queda de guarnición.",
    murallas_en_pie: "Sin brecha no se entra: hay que dejar las murallas a cero.",
    cerca_de_enemigo: "Demasiado cerca de un asentamiento enemigo (hace falta 2 o más).",
    ya_dormida: "Ya está dormida.",
    no_dormida: "No está dormida.",
    otra_faccion: "Esa tropa es de otra facción.", sin_esa_tropa: "Tu facción no tiene esa tropa.", no_la_tienes: "Aún no tienes esa facción.",
    poder_gastado: "Ya has usado el poder del líder en esta partida.", poder_en_marcha: "El poder ya está en marcha.", no_tras_atacar: "Después de atacar solo puede apartarse: no puede conquistar.",
  },
  faltan: "Te faltan {que}.",
  requiereTec: "Requiere {tec}.",
  cercaDe: "{nombre} está a {d}; hace falta {min}.",
  sinHuecoDetalle: "Guarnición llena y sin hexágono libre alrededor.",
  porQueNo: "Por qué no",
  sonido: "Sonido",
  musica: "Música",
  creditos: "Créditos",
  creditoMusica: "Música de Alexander Nakarada (creatorchords.com), vía free-stock-music.com, licencia CC BY 4.0: \"Lively Tavern\" en el menú; \"Village Ambiance\", \"Might & Magic\" y \"Medieval Chateau\" en la partida.",
  creditoIconos: "Iconos del menú de Lorc y Delapouite (game-icons.net), licencia CC BY 3.0.",
  tocaParaEntrar: "Toca para entrar",
  mejorarA: "Mejorar a",
  dormir: "Dormir",
  despertar: "Despertar",
  dormida: "Dormida",
  dormirPista: "Dormida no cuenta como pendiente al acabar el turno ni sale en Siguiente tropa. Despierta sola si un enemigo se pone al lado o, si dormía herida, al curarse del todo.",
  evolucionPuntos: "Evolución de los puntos",
  puntosAlMarcador: "puntos a tu marcador",
  puntoClaveVale: "vale {n} puntos al final para quien lo posea",
  siguienteTropaCorto: "Sig. tropa",
  sinCarreteras: "Sin carreteras",
  sonidoOn: "Activado",
  sonidoOff: "Silencio",
  desgloseVeterania: "veteranía",
  desgloseTerreno: "terreno",
  desgloseAtrincherada: "atrincherada",
  desgloseMurallas: "murallas",
  desgloseOtros: "tecnología y bando",
  eventos: {
    refuerzos: "Refuerzos para {jugador}: {tropas}", cambiaBando: "Cambia de bando: {jugador}", retirada: "Se va de la pelea: {jugador}", objetivo: "El objetivo ha cambiado", avisoGuion: "{clave}",
    mover: "{tropa} se mueve.",
    reclamar: "{jugador} reclama un hexágono.",
    ataque: "{atacante} ataca a {defensor}: {dano} de daño{extra}.",
    contraataque: "{defensor} contraataca: {dano} de daño{extra}.",
    muere: "{tropa} muere.",
    asciende: "{jugador}: {tropa} asciende a {nivel}.",
    despierta: "{tropa} despierta en {asentamiento}: enemigo cerca.",
    despiertaCurada: "{tropa} despierta en {asentamiento}: ya está curada.",
    asedio: "{atacante} asedia {asentamiento}: −{dano} murallas{extra}.",
    brecha: "¡Brecha en {asentamiento}!",
    conquista: "{jugador} conquista {asentamiento}.",
    funda: "{jugador} funda {asentamiento}.",
    recluta: "{jugador} recluta {tropa} en {asentamiento}.",
    mejoraTropa: "{tropa} mejora a {nuevo}.",
    castillo: "{jugador} construye un castillo: {asentamiento}.",
    ciudad: "{asentamiento} es ahora ciudad.",
    investiga: "{jugador} investiga {tec}.",
    investigado: "{jugador} ha descubierto {tec}.",
    bancarrota: "{jugador} no puede pagar: {tropa} deserta.",
    licencia: "{jugador} licencia a {tropa}.",
    atrinchera: "{tropa} se atrinchera.",
    carretera: "{jugador} construye una carretera.",
    eliminado: "{jugador} ha sido eliminado.",
    poder: "{jugador} usa {poder}.", saqueo: "{jugador} saquea {asentamiento}: +{oro} de oro.", botin: "{jugador}: +{oro} de oro.", estacas: "{tropa} se clava en las estacas: −{dano}.", sed: "La sed: {tropa} pierde {dano} de vida.",
    victoria: "{jugador} gana la partida.",
    turno: "— Turno {turno} —",
  },
};
