// English for everything that lives inside the data (names, descriptions, traits, quests, medals, items…).
// The loader swaps these in when the language is English; anything missing stays in Spanish.
// Keys are the internal ids, so they never change when the Spanish wording changes.
window.FWM = window.FWM || {};
FWM.traducciones = FWM.traducciones || {};

FWM.traducciones.en = {
  tropas: {
    campesino: { nombre: "Peasant", descripcion: "The basic troop. Cheap, weak, and the only one that can found villages. Good for claiming ground and for filling garrisons." },
    lancero: { nombre: "Spearman", descripcion: "Solid infantry. Good defence: it goes in front and takes the hits. Its wall of pikes punishes cavalry (+15), but a swordsman slips inside it." },
    arquero: { nombre: "Archer", descripcion: "Shoots the neighbouring hex without taking a counterattack (two hexes from a hill). It wears the enemy down rather than killing. In a garrison it defends from inside without exposing itself." },
    espadachin: { nombre: "Swordsman", descripcion: "Nimble, deadly infantry. Slips inside the spears (+15 against spearmen) and its buckler stops arrows (+10 defence against ranged troops), but a cavalry charge rolls over it." },
    caballero: { nombre: "Knight", descripcion: "The shock troop. Hits hard, moves two hexes and takes a beating. Its charge rolls over swordsmen (+15), but it fears the wall of spears. Expensive to recruit and to keep." },
    catapulta: { nombre: "Catapult", descripcion: "The siege engine. Breaks walls from two hexes away and hits the garrison on the way, out of reach of archers. It can't move and shoot in the same turn and it can't defend itself: escort it." },
    monje: { nombre: "Monk", descripcion: "Doesn't fight: heals. At the end of your turn it heals 10 to each of your troops next to it. Weak and with no counterattack: keep it behind the line." },
    ballestero: { nombre: "Crossbowman", descripcion: "A flat shot that punches through armour (+10 against armoured troops). Like the catapult, it can't move and shoot in the same turn." },
    alabardero: { nombre: "Halberdier", descripcion: "Long halberd: +15 against cavalry, and the swordsman finds no way in (no bonus against it). Steady armoured infantry." },
    infanteria_pesada: { nombre: "Heavy infantry", descripcion: "A shield wall. The toughest troop on foot: it takes whatever you throw at it (+10 defence against ranged troops) and its maces open breaches in walls. Slow and expensive to keep." },
    caballeria_pesada: { nombre: "Heavy cavalry", descripcion: "The charge that decides the battle. Rolls over swordsmen (+15) and sweeps away archers and machines (+20). Only a wall of spears stops it. Costs a fortune every turn." },
    trabuco: { nombre: "Trebuchet", descripcion: "The wall-breaker. Hits from three hexes, out of reach of everything, and brings a wall down in two shots. It can't move and shoot in the same turn, and in the open it's a sitting target." },
    caballero_santiago: { nombre: "Knight of Santiago", descripcion: "A knight of a military order: a knight a little better at everything, and next to one of your villages nobody can shift him (+10 defence). Costs a little more." },
    berserker: { nombre: "Berserker", descripcion: "A warrior who goes into a trance: a swordsman a little better at everything, with the same bonuses, and the more wounded he is the harder he hits (+5 attack for every 20 health lost, up to +15). Costs a little more." },
    arquero_largo: { nombre: "Longbowman", descripcion: "The English yew bow: a slightly better archer who shoots two hexes away, further than any other shooter. Costs a little more." },
    jinete_mandinga: { nombre: "Mandinka rider", descripcion: "The empire's cavalry: a slightly better knight, who needs no iron. Costs a little more." },
    mameluco: { nombre: "Mamluk", descripcion: "An elite soldier trained since childhood: a slightly better knight, and his mail protects him from arrows (+10 defence against ranged troops). Costs a little more." },
    arquero_caballo: { nombre: "Horse archer", descripcion: "Shoots at the gallop: a slightly better archer, with twice the movement. Like all cavalry, spearmen get +15 against him. Costs a little more." },
    guardian_bosque: { nombre: "Forest guardian", descripcion: "A spearman with a great oak shield: a slightly better spearman, with the same +15 against cavalry, and in the forest he holds even better (+5 defence). Costs a little more." },
    heroe_hechicera: { nombre: "Sorceress", descripcion: "Casts lightning two hexes away, and magic goes straight through armour. Little defence: keep her out of reach. Heals the troops next to her." },
    heroe_mansa: { nombre: "Mansa", descripcion: "The lord of gold. He fights well up close and every enemy who falls fills his chest. His spear guard protects those who fight beside him." },
    heroe_kan: { nombre: "Khan", descripcion: "Rider and archer. He shoots and is gone before anyone answers. The riders beside him go further." },
    heroe_espadachin: { nombre: "Swordsman", descripcion: "Balanced. Slips between the spears and his buckler stops arrows. His presence makes the troops beside him tougher." },
    heroe_arquero: { nombre: "Archer", descripcion: "Shoots one hex away without taking a counterattack, and further from a hill. He spurs on the shooters." },
    heroe_nordico: { nombre: "Norseman", descripcion: "Hits like no one else, and hits harder the more wounded he is. Little armour. His shouts fire up those beside him." },
    heroe_alquimista: { nombre: "Alchemist", descripcion: "Throws fire at a hex: the target burns and the enemies next to it are scorched. His salves heal those beside him." },
  },
  asentamientos: {
    pueblo: { nombre: "Village", descripcion: "The starting settlement and the way to expand. A peasant founds it. It gives gold, recruits peasants and has one garrison slot." },
    ciudad: { nombre: "City", descripcion: "An upgraded village. It's your economy and your quality army: more gold, recruits every troop, and it's the only place troops can be upgraded." },
    castillo: { nombre: "Castle", descripcion: "Pure defence. Built on any empty hex of yours. Three garrison slots, thick walls and a big defence bonus for whoever is inside. It produces almost nothing." },
  },
  terrenos: {
    llanura: { nombre: "Plain", descripcion: "Open ground. Costs one step and gives nothing." },
    bosque: { nombre: "Forest", descripcion: "Costs double to move through (a slow troop spends its whole turn entering). Whoever is inside gains +10 defence. Timber comes from forests with a resource." },
    colina: { nombre: "Hill", descripcion: "Costs double to move through (a slow troop spends its whole turn entering). +10 defence, and archers shoot one hex further from up there. Quarries and mines are usually here." },
    montana: { nombre: "Mountain", descripcion: "Impassable. It creates passes and bottlenecks." },
    agua: { nombre: "Water", descripcion: "Impassable." },
  },
  yacimientos: {
    bosque: { nombre: "Woodland", descripcion: "Gives timber while it's yours and connected to a settlement of yours." },
    mina_oro: { nombre: "Gold mine", descripcion: "Gives gold. The resource you need most: everything costs gold." },
    cantera: { nombre: "Quarry", descripcion: "Gives stone, for castles and defences." },
    mina_hierro: { nombre: "Iron mine", descripcion: "Gives iron, for heavy troops and catapults." },
    punto_clave: { nombre: "Key point", descripcion: "Produces nothing. Worth 10 points at the end of the game to whoever holds it then. Start thinking about them early." },
  },
  recursos: {
    oro: { nombre: "Gold", descripcion: "The currency for everything: recruiting, upkeep, building and research. It comes from settlements and gold mines." },
    madera: { nombre: "Timber", descripcion: "Comes from forests. For upgrading to a city, light troops and catapults." },
    piedra: { nombre: "Stone", descripcion: "Comes from quarries. For castles and fortifications." },
    hierro: { nombre: "Iron", descripcion: "Comes from iron mines. For knights and catapults." },
  },
  tecnologias: {
    agricultura: { nombre: "Agriculture", descripcion: "Every village and city produces +1 gold. Allows upgrading a village to a city." },
    canteria: { nombre: "Masonry", descripcion: "Every quarry produces +1 stone." },
    maquinaria: { nombre: "Machinery", descripcion: "Every forest produces +1 timber." },
    milicia: { nombre: "Militia", descripcion: "Allows recruiting spearmen." },
    fortificacion: { nombre: "Fortification", descripcion: "Castles: +1 garrison slot, +10 defence, +40 walls." },
    catapulta: { nombre: "Catapult", descripcion: "Allows recruiting catapults." },
    arqueria: { nombre: "Archery", descripcion: "Allows recruiting archers." },
    caballeria: { nombre: "Cavalry", descripcion: "Allows recruiting knights." },
  },
  bandos: {
    castilla: { nombre: "Crown of Castile", rasgo: "Castles cost half the stone (in Quick games, 25% less gold).", descripcion: "A land of castles. The Reconquista was won by fortifying every frontier." },
    inglaterra: { nombre: "Kingdom of England", rasgo: "Archers +10 attack.", descripcion: "The longbow decided whole battles. Its archers are the best in the known world." },
    francia: { nombre: "Kingdom of France", rasgo: "Knights +10 defence and 5 gold cheaper.", descripcion: "French heavy cavalry is the hammer of Europe: expensive, slow to muster, unstoppable." },
    ming: { nombre: "Ming Dynasty", rasgo: "Catapults +20 siege and range 4.", descripcion: "Gunpowder, engineers and walls: nobody besieges like the Middle Kingdom." },
    abasi: { nombre: "Abbasid Caliphate", rasgo: "Every gold mine produces +1.", descripcion: "Baghdad, the House of Wisdom and the gold routes: trade is their army." },
    vikingos: { nombre: "Vikings", rasgo: "Plunder: when you take a settlement you carry off its gold.", descripcion: "The men of the north: longships, axes and a hunger for land that reached from Newfoundland to Constantinople." },
    mali: { nombre: "Mali Empire", rasgo: "Gold of Mali: 8% more gold every turn.", descripcion: "The golden empire of the Niger: Timbuktu, its libraries, and the pilgrimage of Mansa Musa, which brought down the price of gold in Cairo." },
    saladino: { nombre: "Sultanate of Saladin", rasgo: "Hardened riders: mounted troops heal more when they rest.", descripcion: "Egypt and Syria in a single hand: the Mamluk cavalry, the engineers of Cairo and the man who took back Jerusalem." },
    mongoles: { nombre: "Mongol Empire", rasgo: "Steppe: riders cross forests and hills as if they were flat.", descripcion: "The steppe tribes united by Genghis Khan: the largest land empire there has ever been, built on horseback." },
    avaros: { nombre: "Avar Khaganate", rasgo: "All your mounted troops +10 attack.", descripcion: "Riders from the plain who took tribute from every forest people." },
    eslavos: { nombre: "Slavic tribes", rasgo: "Children of the forest: more defence in forests and hills, and infantry crosses forests without slowing down.", descripcion: "The peoples of the great eastern forests before the kingdoms existed: wooden villages, axes, spears and gods of thunder and spring." },
    aragon: { nombre: "Crown of Aragon", rasgo: "Every settlement produces +1 gold.", descripcion: "Barcelona, Valencia and half of Italy: a crown that lived off the sea and trade." },
    portugal: { nombre: "Kingdom of Portugal", rasgo: "Peasants +1 movement and 3 gold cheaper.", descripcion: "A long, narrow kingdom: whoever moves fast across its land can defend an impossible border." },
    granada: { nombre: "Emirate of Granada", rasgo: "Your settlements give the garrison +10 defence and have +20 walls.", descripcion: "The last kingdom of al-Andalus: mountains, towers and a knack for holding out that lasted two centuries." },
    sacro_imperio: { nombre: "Holy Roman Empire", rasgo: "Spearmen and halberdiers +10 defence.", descripcion: "Hundreds of cities and princes under a single crown: its strength is the infantry of the free cities." },
    noruega: { nombre: "Kingdom of Norway", rasgo: "Swordsmen +10 attack and +10 health.", descripcion: "Heirs of the Norsemen: few, tough and used to fighting far from home." },
    polonia: { nombre: "Kingdom of Poland", rasgo: "Knights and heavy cavalry 10 gold cheaper.", descripcion: "Endless plains and the best cavalry in the east: it defends by charging." },
    bizancio: { nombre: "Byzantine Empire", rasgo: "Archers and crossbowmen +1 range.", descripcion: "The walls of Constantinople and Greek fire: a thousand years of holding off everyone who came." },
    venecia: { nombre: "Republic of Venice", rasgo: "Every gold mine and every city produces +1 gold.", descripcion: "No army and no land of its own: money, galleys and mercenaries paid on time." },
    escocia: { nombre: "Kingdom of Scotland", rasgo: "All your infantry +5 defence.", descripcion: "Mountains, bogs and walls of pikes: you win by choosing the ground and waiting." },
    hungria: { nombre: "Kingdom of Hungary", rasgo: "All your mounted troops +10 attack.", descripcion: "Steppe riders settled on the plain: they arrive before you see them coming." },
    barbaros: { nombre: "Barbarian hordes", rasgo: "They don't build or collect gold: they just keep coming.", descripcion: "They come from all four sides, wave after wave, and there are more of them every time." },
    azteca: { nombre: "Aztec Empire", rasgo: "Peasants +10 attack and troops gain double experience.", descripcion: "Jaguar and eagle warriors: the infantry is the army, and every battle forges veterans." },
  },
  heroesClases: {
    mansa: { nombre: "Mansa", descripcion: "The lord of gold. He fights well up close and every enemy who falls fills his chest. His spear guard protects those who fight beside him.", rasgo: "Every enemy troop he defeats: +5 gold. Aura: +1 defence to troops next to him." },
    kan: { nombre: "Khan", descripcion: "Rider and archer. He shoots and is gone before anyone answers. The riders beside him go further.", rasgo: "Can move after shooting. Aura: riders next to him get +1 movement." },
    hechicera: { nombre: "Sorceress", descripcion: "Casts lightning two hexes away, and magic goes straight through armour. Little defence: keep her out of reach. Heals the troops next to her.", rasgo: "Lightning at 2 hexes, +8 against armoured troops. At the end of your turn she heals 10 to your troops next to her." },
    espadachin: { nombre: "Swordsman", descripcion: "Balanced. Slips between the spears and his buckler stops arrows. His presence makes the troops beside him tougher.", rasgo: "+10 against spears, +5 defence against arrows. Aura: +1 defence." },
    arquero: { nombre: "Archer", descripcion: "Shoots one hex away without taking a counterattack, and further from a hill. He spurs on the shooters.", rasgo: "Shoots 1 hex; +1 range on a hill. Aura: +1 attack to ranged troops." },
    nordico: { nombre: "Norseman", descripcion: "Hits like no one else, and hits harder the more wounded he is. Little armour. His shouts fire up those beside him.", rasgo: "Fury: +5 attack for every 25 health lost (up to +10). Aura: +1 attack." },
    alquimista: { nombre: "Alchemist", descripcion: "Throws fire at a hex: the target burns and the enemies next to it are scorched. His salves heal those beside him.", rasgo: "Fire: his attack burns 5 on enemies next to the target. Aura: resting troops heal +3 more." },
  },
  heroesNiveles: { 1: "Recruit", 2: "Squire", 3: "Soldier", 4: "Sergeant", 5: "Knight", 6: "Captain", 7: "Lord", 8: "Prince", 9: "King", 10: "Emperor", 11: "Legend" },
  facciones: {
    castilla: { nombre: "Crown of Castile", pais: "Spain", lider: "Alfonso VIII", estilo: "Defensive and balanced", descripcion: "Holds out and wins by wearing the enemy down. The faction to learn with: it forgives mistakes. Defending its own land it's very hard to break; far from home it loses its edge.",
      rasgo: { nombre: "Frontier land", texto: "Your troops on your own territory get +3 defence." }, poder: { nombre: "Las Navas", texto: "Until your next turn, all your troops +5 attack and +5 defence." } },
    vikingos: { nombre: "Vikings", pais: "Norway", lider: "Harald Hardrada", estilo: "Fast attack", descripcion: "Strikes first and hard, and lives off what it plunders. If it doesn't push forward it runs out of gold; if it pushes well, it sweeps everything away.",
      rasgo: { nombre: "Plunder", texto: "When you take a settlement you carry off its gold: 15 from a village, 25 from a city or a castle." }, poder: { nombre: "Fury of the North", texto: "Until your next turn, all your foot troops +10 attack." } },
    inglaterra: { nombre: "Kingdom of England", pais: "United Kingdom", lider: "Edward I", estilo: "Ranged", descripcion: "Wins without the enemy ever reaching it. Behind a wall of spearmen its archers have no rival; if the cavalry gets to them, they fall quickly.",
      rasgo: { nombre: "Marksmen", texto: "All your ranged troops get +3 attack." }, poder: { nombre: "Rain of arrows", texto: "Until your next turn, all your ranged troops shoot one hex further." } },
    mali: { nombre: "Mali Empire", pais: "Mali", lider: "Mansa Musa", estilo: "Economic", descripcion: "Wins with its purse. Mansa Musa is said to be the richest man in history: Mali makes more gold and spends it better. Its army is bigger, even if each troop hits less hard.",
      rasgo: { nombre: "Gold of Mali", texto: "You earn 8% more gold every turn." }, poder: { nombre: "The griots", texto: "The Mansa's singers lift everyone's spirits: all your troops recover 15 health at once." } },
    saladino: { nombre: "Sultanate of Saladin", pais: "Egypt and Syria", lider: "Saladin", estilo: "Elite cavalry", descripcion: "Few troops, but the best. Everything turns on a very expensive cavalry that you can't afford to lose. Its naphtha throwers burn whatever they touch.",
      rasgo: { nombre: "Hardened riders", texto: "Your mounted troops heal 5 more when they rest." }, poder: { nombre: "Hattin", texto: "Thirst: every enemy troop next to yours loses 10 health (never below 1)." } },
    mongoles: { nombre: "Mongol Empire", pais: "Mongolia", lider: "Genghis Khan", estilo: "Total mobility", descripcion: "It's everywhere. The only faction that fights on horseback and at range at the same time: it harasses, shoots and is gone before anyone answers. The hardest to handle.",
      rasgo: { nombre: "Steppe", texto: "Your mounted troops enter forests and hills as if they were plains." }, poder: { nombre: "The Yam", texto: "The relay-post network: this turn, all your troops get +2 movement." } },
    eslavos: { nombre: "Slavic tribes", pais: "Eastern Europe", lider: "Vesna", estilo: "Forest and endurance", descripcion: "It fights where the enemy doesn't want to go. In forests and hills it's almost impossible to dislodge, and its sorceress heals whoever fights beside her. In open ground and without heavy cavalry, it suffers.",
      rasgo: { nombre: "Children of the forest", texto: "Your troops in forests or hills get +3 defence, and those on foot cross forests as if they were plains." }, poder: { nombre: "Winter", texto: "Until your next turn, every enemy troop moves 1 less (never below 1)." } },
  },
  heroesMejoras: {
    vigor: { nombre: "Vigour", texto: "+5 hero health" },
    filo: { nombre: "Edge", texto: "+3 hero attack" },
    temple: { nombre: "Mettle", texto: "+1 hero defence" },
    paso_ligero: { nombre: "Light step", texto: "+1 hero movement" },
    segundo_aliento: { nombre: "Second wind", texto: "The hero heals 10 at the start of your turn if he didn't attack on the previous one" },
    coraza: { nombre: "Cuirass", texto: "+4 hero defence against ranged troops" },
    escudo_hermanos: { nombre: "Shield of brothers", texto: "Troops next to the hero: +2 defence" },
    grito: { nombre: "War cry", texto: "Troops next to the hero: +2 attack" },
    cirujano: { nombre: "Surgeon", texto: "Troops next to the hero that rest heal +5 more" },
    estandarte: { nombre: "Banner", texto: "The aura reaches 2 hexes" },
    disciplina: { nombre: "Discipline", texto: "Troops next to the hero and dug in: +2 more defence" },
    inspiracion: { nombre: "Inspiration", texto: "Troops next to the hero: +1 experience per fight" },
    tesorero: { nombre: "Treasurer", texto: "+1 gold per turn" },
    leva: { nombre: "Levy", texto: "Peasants cost 1 gold less" },
    armero: { nombre: "Armourer", texto: "Swordsmen and spearmen cost 1 gold less" },
    cantero: { nombre: "Stonemason", texto: "Your settlements' walls: +10 maximum integrity" },
    forrajeo: { nombre: "Foraging", texto: "Troops in your own territory heal +4 more" },
    maestre: { nombre: "Master of the household", texto: "The capital can recruit twice per turn" },
    caminos: { nombre: "Roads", texto: "Your troops move +1 if they start the turn in your own territory" },
    gala: { nombre: "Finery", texto: "A piece of finery (looks only)" },
  },
  medallas: {
    primera_victoria: { nombre: "First victory", descripcion: "Win your first game." },
    intacto: { nombre: "Not a scratch", descripcion: "Win against 3 opponents (or a duel) without losing a single troop." },
    del_dia: { nombre: "King of the day", descripcion: "Daily maps won: {n}." },
    relampago: { nombre: "Lightning", descripcion: "Win before turn {n}." },
    carnicero: { nombre: "Butcher", descripcion: "Kill {n} enemy troops in one game." },
    estratega: { nombre: "Strategist", descripcion: "Finish a game holding {n} key points." },
    conquistador: { nombre: "Conqueror", descripcion: "Take {n} settlements in one game." },
    racha5: { nombre: "Unstoppable", descripcion: "Win {n} games in a row." },
    fuego7: { nombre: "Constancy", descripcion: "Play {n} days in a row." },
    tres_bandos: { nombre: "Diplomat", descripcion: "Win with {n} different factions." },
    veterano: { nombre: "Veteran", descripcion: "Play {n} games." },
    cazador: { nombre: "Hunter", descripcion: "Enemy heroes slain: {n}." },
    duelista: { nombre: "Duellist", descripcion: "Duels won against other players: {n}." },
    implacable: { nombre: "Tamer", descripcion: "Games won on hard: {n}." },
    campana: { nombre: "Chronicler", descripcion: "Beat {n} campaign maps." },
  },
  objetos: {
    capa_granate: { nombre: "Maroon cloak", texto: "Looks only: a maroon cloak" },
    capa_azul: { nombre: "Blue travelling cloak", texto: "Looks only: a blue cloak" },
    estandarte_leon: { nombre: "Lion banner", texto: "Looks only: a banner with a lion on your back" },
    capa_armino: { nombre: "Ermine cloak", texto: "Looks only: a speckled white cloak, fit for a king" },
    manto_estrellas: { nombre: "Starry mantle", texto: "Looks only: a night-blue mantle with stars" },
    capa_oro: { nombre: "Golden cloak", texto: "Looks only: a golden cloak" },
    capa_lobo: { nombre: "Wolf pelt", texto: "Looks only: a wolf pelt over the shoulders" },
    estandarte_dragon: { nombre: "Dragon banner", texto: "Looks only: Harald's banner, a black dragon on red" },
    capa_arquero: { nombre: "Archer's cloak", texto: "Looks only: a green woodland cloak" },
    capa_leones: { nombre: "Cloak of the lions", texto: "Looks only: a red cloak with golden lions" },
    capa_indigo: { nombre: "Indigo mantle", texto: "Looks only: a mantle dyed indigo" },
    manto_dorado: { nombre: "Golden mantle of Mali", texto: "Looks only: the golden mantle of the first king of Mali" },
    capa_seda: { nombre: "Silk cloak", texto: "Looks only: green Damascus silk" },
    capa_aguila: { nombre: "Eagle cloak", texto: "Looks only: a yellow cloak with Saladin's eagle" },
    capa_fieltro: { nombre: "Felt cloak", texto: "Looks only: steppe felt, good against the cold" },
    capa_abedul: { nombre: "Birch cloak", texto: "Looks only: wool dyed the colour of birch bark" },
    manto_primavera: { nombre: "Mantle of spring", texto: "Looks only: the green mantle of the one who brought spring to the tribes" },
    capa_estepa: { nombre: "Khan's mantle", texto: "Looks only: the sky-blue mantle of the khan of all the tribes" },
    espada_hierro: { nombre: "Iron sword", texto: "+2 attack" },
    lanza_larga: { nombre: "Long spear", texto: "+5 against cavalry" },
    hacha: { nombre: "Woodcutter's axe", texto: "+10 siege" },
    maza: { nombre: "War mace", texto: "+5 against armoured troops, +5 siege" },
    sable: { nombre: "Rider's sabre", texto: "+5 against troops on foot" },
    espada_larga: { nombre: "Longsword", texto: "+3 attack, +5 health" },
    martillo: { nombre: "Siege hammer", texto: "+20 siege, +1 attack" },
    espada_capitan: { nombre: "Captain's sword", texto: "+2 attack; troops beside him +1 attack" },
    mandoble: { nombre: "Greatsword", texto: "+3 attack, +10 health" },
    rodela: { nombre: "Buckler", texto: "+1 defence" },
    escudo_puas: { nombre: "Spiked shield", texto: "+1 defence, +1 attack" },
    escudo_reforzado: { nombre: "Reinforced shield", texto: "+2 defence" },
    escudo_torre: { nombre: "Tower shield", texto: "+1 defence, and +3 more against ranged troops" },
    escudo_blason: { nombre: "Blazoned shield", texto: "+2 defence to troops garrisoned with the hero" },
    egida: { nombre: "Aegis", texto: "+3 defence" },
    mula: { nombre: "Mule", texto: "+5 health" },
    poni: { nombre: "Pony", texto: "+10 health" },
    caballo: { nombre: "Horse", texto: "+1 movement" },
    caballo_barda: { nombre: "Barded horse", texto: "+1 movement, +1 defence" },
    corcel: { nombre: "Warhorse", texto: "+1 movement, +10 health" },
    gorro_lana: { nombre: "Woollen cap", texto: "+5 health" },
    casco_hierro: { nombre: "Iron helmet", texto: "+1 defence" },
    yelmo: { nombre: "Helm", texto: "+1 defence, +5 health" },
    yelmo_cimera: { nombre: "Crested helm", texto: "+1 defence; troops beside him +1 attack" },
    diadema: { nombre: "Treasurer's diadem", texto: "+1 gold per turn" },
    corona_laurel: { nombre: "Laurel crown", texto: "+1 gold per turn, +5 health" },
    corona_rey: { nombre: "King's crown", texto: "+2 gold per turn, +1 defence" },
    pocima: { nombre: "Resurrection draught", texto: "If the hero dies, he returns to the capital next turn with half his health. It's used up." },
    capa_embajador: { nombre: "Ambassador's cloak", texto: "Looks only: a green and gold cloak" },
  },
  misiones: {
    gana: "Win a game",
    gana_bando: "Win with {bando}",
    mata8: "Kill 8 troops in one game",
    funda2: "Found 2 villages in one game",
    dia: "Play the daily map",
    heroe_vivo: "Win with your hero alive",
    toma1: "Take a settlement",
    clave4: "Finish holding 4 key points",
    rapido: "Win before turn 16",
    pierde2: "Win losing 2 troops or fewer",
    mata5: "Kill 5 troops in one game",
    duelo: "Play an online duel",
    gana_duelo: "Win an online duel",
    heroe_mata: "Slay the enemy hero",
    clave2: "Finish holding 2 key points",
    toma2: "Take 2 settlements in one game",
    gana_rapida: "Win a Quick game",
    juega2: "Play 2 games",
    mata12: "Kill 12 troops across all of today's games",
    gana2: "Win 2 games",
    s_gana5: "Win 5 games",
    s_mata40: "Kill 40 troops",
    s_duelos3: "Play 3 online duels",
    s_bandos3: "Win with 2 different factions",
    s_dias3: "Play 3 daily maps",
    s_toma5: "Take 5 settlements",
    s_heroes5: "Slay 5 heroes",
  },
  mapas: {
    hoz: { nombre: "The Gorge", texto: "A river splits the land in two; it can only be crossed in two places." },
    torres: { nombre: "The Four Towers", texto: "Four realms in the corners and the riches in the middle." },
    isla: { nombre: "The Island", texto: "A lake in the middle; the land bridges decide the game." },
    sierra: { nombre: "The Mountain Pass", texto: "A range crosses the map; you have to go through the passes." },
    costa: { nombre: "The Coast", texto: "A strip of land between the sea and the mountains." },
    europa: { nombre: "Europe", texto: "From Iberia to Constantinople. Twelve possible realms, a whole continent and plenty of room to get it wrong." },
    iberia: { nombre: "Iberia", texto: "Five crowns in one peninsula. Every border is a war half finished." },
    britannia: { nombre: "Britannia", texto: "Scotland, England, the Norsemen of Dublin and the continent across the channel." },
    fiordo: { nombre: "The Fjords", texto: "Arms of the sea that reach far inland: you cross by the isthmuses." },
    mar_norte: { nombre: "The North Sea", texto: "Islands joined by sandbanks: whoever holds the crossings holds the sea." },
    marca: { nombre: "The Welsh March", texto: "Hills, thick woods and castles at every pass." },
    evesham: { nombre: "Evesham", texto: "A bend in the river closes in the town: only one way out by land." },
    niger: { nombre: "The Niger", texto: "The great river splits the savanna; its islands are crossings and traps." },
    sabana: { nombre: "The Savanna", texto: "Tall grass to the horizon and groves to hide in." },
    hattin: { nombre: "The Horns of Hattin", texto: "Two hills in the middle of a dry plain; the lake is far away." },
    nilo: { nombre: "The Nile Delta", texto: "The river opens into branches before it reaches the sea." },
    estepa: { nombre: "The Steppe", texto: "Endless flatland: here, whoever gets there first is in charge." },
    gobi: { nombre: "The Gobi", texto: "Stone, bare ridges and oases where everyone meets." },
    bosque_viejo: { nombre: "The Old Forest", texto: "Endless oaks and birches: whoever knows the paths is in charge." },
    llanura_avara: { nombre: "The Riders' Plain", texto: "Open grass to the horizon and forest only at the edges: here the horses rule." },
    arena: { nombre: "The Palisade", texto: "A valley open on all four sides. Nobody is coming to help." },
  },
  escenarios: {
    europa: { nombre: "Europe", texto: "From Iberia to Constantinople. Twelve possible realms, a whole continent and plenty of room to get it wrong." },
    iberia: { nombre: "Iberia", texto: "Five crowns in one peninsula. Every border is a war half finished." },
    britannia: { nombre: "Britannia", texto: "Scotland, England, the Norsemen of Dublin and the continent across the channel." },
  },
  campana: {
    1: { nombre: "The river mill", texto: "Cross the river, drive them out of their village and get your grain back.",
      voz: "Your captain", historia: "The king has died and he left no children. Nobody is in charge around here any more. Last night some men crossed the river, walked into your mill and took the grain. There are only a few of them and they are badly armed, but if nobody stops them they will come back every week." },
    2: { nombre: "The coast mines", texto: "Take the two gold mines on the coast and pay your soldiers.",
      voz: "Your captain", historia: "You have driven the thieves off, but your soldiers have not been paid for two months. On the coast there are two gold mines guarded by a lord with very few men. If they are yours, you can pay for a real army." },
    3: { nombre: "The three oaths", texto: "Your two allies have joined the enemy. Take the middle of the valley from them.",
      voz: "Your captain", historia: "With the mines you can pay your men now, but there is bad news. The other two families of the valley, who swore to defend it with you, have gone over to Alvar the Crow: the general who has taken the king's crown. This morning they moved their armies into the middle of the valley." },
    4: { nombre: "The mountain pass", texto: "Take the two mountain passes before they close the road on you.",
      voz: "A shepherd from the mountains", historia: "The valley is yours now, my lord, and the road goes on north. Behind these mountains the Crow's lands begin. There are only two narrow ways through, and he has men watching both. Climbing is the easy part; the hard part is not having them waiting for us at the top." },
    5: { nombre: "The burned bridges", texto: "Three enemies surround the lake. Get through on the strips of land that are left.",
      voz: "Your captain", historia: "We are on the other side of the mountains now, on his land. The Crow has burned two of the lake bridges to slow us down and promised a thousand gold coins to whoever kills you. Three of his lords have surrounded the water and are blocking our way." },
    6: { nombre: "Empty coffers", texto: "You start with half the gold. Cross the river and spend every coin wisely.",
      voz: "Your captain", historia: "We are far from home and deep in enemy land. And tonight the man who looked after your money ran off with half the chest: they say he has gone over to the Crow. Ahead of us there is another river and two lords waiting on the far bank." },
    7: { nombre: "The siege", texto: "Three armies have you surrounded. Break out on one side and hit back.",
      voz: "Your captain", historia: "The Crow has sent his best lords after you. Three of them have shut us in among their towers. We must break out on one side before they close the circle completely." },
    8: { nombre: "The charge", texto: "Open field and three enemies. Strike first: win and the warhorse is yours.",
      voz: "Your master of horse", historia: "We are out of the trap and now we are the ones giving chase. There are no rivers or towers to hide behind here: it is open ground between the sea and the mountains, and that is good for horses. Let me go out first, my lord, and you will see them run." },
    9: { nombre: "Iron mountains", texto: "You only have twelve turns. Cross the passes before the snow arrives.",
      voz: "Your captain", historia: "These mountains are the last thing between us and the Crow's Tower. He has called in everyone who owes him a favour and put them on the roads. They only have to hold for twelve days: after that the snow comes and nobody will get through until spring." },
    10: { nombre: "The Crow's Tower", texto: "Cross the lake and take the Tower. Win, and the crown is yours.",
      voz: "Alvar the Crow", historia: "“Well, well. The boy from the mill. You got further than anyone expected.” Alvar speaks to you calmly from the top of his wall. “I did not kill the king. The crown was lying on the floor and I picked it up, that is all. Cross the lake if you dare. I will be waiting, with everything I have left.”" },
  },
  // campaigns of the factions (13 Sep 2026): `_` is the campaign itself; numbers are the chapters.
  // Castile's chapters are translated above in `campana`.
  campanas: {
    castilla: { _: { nombre: "The Crow", destino: "The Crow's Tower", pista: "Ten hand-made maps, each harder than the last. Each map you beat gives its prize only once." } },
    vikingos: {
      _: { nombre: "Harald's saga", destino: "Stamford Bridge", pista: "From a boy fleeing a lost battle to King of Norway… and one last voyage to England. Ten chapters, one after another." },
      1: { nombre: "The escape", texto: "Drive Knut's men off the coast and get a ship.", voz: "Rognvald, your friend",
        historia: "Your brother, King Olaf, has fallen in battle. You're only fifteen and you got out alive, but wounded. The new king's men are searching the woods for you. If we reach the coast, we can take a ship and get far away." },
      2: { nombre: "The emperor's guard", texto: "Drive the pirates off the mines and earn your place in the guard.", voz: "The captain of the guard",
        historia: "You've crossed the sea to Constantinople, the biggest city in the world. The emperor pays the northern warriors who protect him in gold. But nobody knows you here: to join his guard you have to show what you're worth." },
      3: { nombre: "The island of castles", texto: "Cross to the southern island and take its castles for the emperor.", voz: "The captain of the guard",
        historia: "You're in the emperor's guard now. He is sending you to a southern island full of castles. If you take it, he'll let you keep part of the loot. For the first time, you'll command your own men." },
      4: { nombre: "The hidden treasure", texto: "Beat the emperor's soldiers in the passes and save the gold.", voz: "Rognvald, your friend",
        historia: "You've gathered a lot of gold on the island, and now the emperor wants it for himself. He says you owe him everything. We've hidden the treasure and we have to get it through the mountain passes before his soldiers arrive." },
      5: { nombre: "The prince of the east", texto: "Clear the river of bandits and the prince will give you his daughter.", voz: "Elisiv, the prince's daughter",
        historia: "With the gold safe, you've reached the lands of the great prince of the east. I'm his daughter. My father says I'll marry you if you clear the bandits from the river road. I've already said yes." },
      6: { nombre: "Coming home", texto: "Your nephew won't share the crown. Get through the fjords.", voz: "Elisiv, your wife",
        historia: "We're going back to Norway with a ship full of gold. But your nephew Magnus is king now and won't share the crown with anyone. His chieftains are blocking our way in the fjords. Let them see we haven't come to beg." },
      7: { nombre: "The King of Denmark", texto: "Svein has taken Denmark. Drive him off your islands.", voz: "Rognvald, your friend",
        historia: "Magnus has died and now you're the only King of Norway. But Svein has taken Denmark, which was Magnus's, and his ships are already at our islands. They fight like we do: this is going to be hard." },
      8: { nombre: "The northern isles", texto: "Take the northern isles: they'll be your harbour for sailing to England.", voz: "An English messenger",
        historia: "I bring news from England, my lord: our king has died without children. Many say the crown could be yours. But to cross the sea with an army you first need the northern isles, and their lords want no master." },
      9: { nombre: "Fulford", texto: "You've landed in England. Beat the earls before their king arrives.", voz: "Rognvald, your friend",
        historia: "We've landed with three hundred ships. The northern earls and their men are waiting for us by a river, near the city of York. If we beat them quickly, the city will open its gates before the English king arrives with his army." },
      10: { nombre: "Stamford Bridge", texto: "The English king has arrived. Cross the bridge and win England.", voz: "Harold, King of England",
        historia: "“Harald of Norway. You've come for my kingdom. I'll give you a piece of England: seven feet of English ground, as much as a man lying down takes up.” Harold speaks to you from the other side of the bridge. “My army has marched day and night to get here. We're waiting for you.”" },
    },
    inglaterra: {
      _: { nombre: "Prince Edward", destino: "Evesham", pista: "A prince held captive, an earl who has taken the kingdom and one year to turn it all around. Ten chapters, one after another." },
      1: { nombre: "The captive prince", texto: "Beat the earl's guards and escape to the woods.", voz: "Your squire",
        historia: "Your father, the king, lost the battle of Lewes. Since then Earl Simon de Montfort has held you both prisoner. Today the guards are letting you out for a ride. Race their horses until they're worn out and escape on the only fresh one. It's now or never, my prince." },
      2: { nombre: "The horse race", texto: "Beat the earl's riders chasing you through the mountains.", voz: "Roger Mortimer",
        historia: "Very clever, prince! You raced your guards' horses until they were worn out, and escaped on the only fresh one. Now they're after you. Cross the mountains to my lands and you'll be safe here." },
      3: { nombre: "The lords of the March", texto: "Take the middle of the valley and the border lords will follow you.", voz: "Roger Mortimer",
        historia: "You're safe on my lands, but a prince without an army scares nobody. The border lords don't trust you. Take the middle of the valley from the earl's barons, and they'll come to swear loyalty." },
      4: { nombre: "The Severn crossings", texto: "Close the crossings of the great river so the earl can't get over.", voz: "Roger Mortimer",
        historia: "Now you have an army. Earl Simon is on the other side of the great river, with the Welsh on his side. If we close the crossings, he'll be shut in the west, far from London and his friends." },
      5: { nombre: "Gloucester", texto: "The city of Gloucester is the key to the west. Take it.", voz: "The Earl of Gloucester",
        historia: "I used to be with Simon, but I got tired of his orders, and now I'm with you, prince. His men still hold my city, Gloucester. It has good walls: we'll have to surround it well." },
      6: { nombre: "Kenilworth", texto: "The earl's son is sleeping outside the castle. Attack before he arms himself.", voz: "Your squire",
        historia: "The earl's son, also called Simon, is coming to help his father with another army. They arrived tired and are sleeping outside Kenilworth castle, by the lake. If we attack at dawn, they'll never manage to join up." },
      7: { nombre: "The Welsh hills", texto: "The Welsh know every path in the hills. Get through anyway.", voz: "Roger Mortimer",
        historia: "Llywelyn, the Prince of Wales, is sending his archers to help the earl. They were born in these hills and know every track. Be careful: their bows are long and they shoot from where you least expect." },
      8: { nombre: "The king's archers", texto: "Open field. Your longbowmen against the earl's cavalry.", voz: "Your squire",
        historia: "You've learned something from the Welsh, prince: their longbows reach further than anything. Now you have them too. The earl is sending his cavalry against us in open country. Put the archers behind the spears." },
      9: { nombre: "The Avon crossing", texto: "The earl is escaping south. Close the river crossing and beat his barons.", voz: "Roger Mortimer",
        historia: "Earl Simon has found another way over the river and is escaping south to join his son. He doesn't know his son has no army left. There's only one road open to him. If we get to the crossing first, we'll have him trapped." },
      10: { nombre: "Evesham", texto: "The earl is shut in the river bend. Win, and the kingdom goes back to your father.", voz: "Simon de Montfort",
        historia: "“Prince Edward. When you were a boy, I taught you to use a sword myself. I see you learned well… but not well enough to beat me.” The earl looks at you from the town, with the river behind him. “Here, between the water and the hill, we decide who rules England.”" },
    },
    mali: {
      _: { nombre: "The Lion of Mali", destino: "Kirina", pista: "The story the griots have sung for eight hundred years: the boy who couldn't walk and the smith king of Sosso. Ten chapters, one after another." },
      1: { nombre: "The boy with the iron bar", texto: "Beat the queen's guard and take your family somewhere safe.", voz: "Balla Fasséké, the griot",
        historia: "Listen, for this story is true. As a boy you couldn't walk and everyone laughed at you. Today you stood up leaning on an iron bar and walked in front of the whole village. The queen who rules the palace is afraid of you now, and has sent her guards after you." },
      2: { nombre: "The kingdom of Mema", texto: "Drive off the horse thieves and the King of Mema will give you soldiers.", voz: "The King of Mema",
        historia: "You've walked for years far from home, from kingdom to kingdom, with your mother and sisters. Here, in Mema, I give you a roof. But first I want to know if you can lead men: some thieves are taking the horses from my pastures. Drive them off." },
      3: { nombre: "Bad news", texto: "Sumaoro has conquered your land. Go back along the river and clear the way.", voz: "Messengers from your people",
        historia: "We've come a very long way to find you. Sumaoro, the smith king of Sosso, has conquered our land. They say he's a sorcerer and spears can't touch him. Everyone remembers the boy with the iron bar. Come back, we beg you." },
      4: { nombre: "The river chiefs", texto: "Take the river crossings before Sumaoro and the village chiefs will join you.", voz: "Balla Fasséké, the griot",
        historia: "You've come back with the King of Mema's army, but alone you can't beat Sumaoro. The chiefs of the river villages are watching to see who is stronger. If you take the river crossings before his soldiers, they'll give you their warriors." },
      5: { nombre: "The open savanna", texto: "His soldiers wear iron; yours ride horses. Fight in the open.", voz: "Your chief of riders",
        historia: "Sumaoro has the best smiths in the world, and all his soldiers wear iron. They're heavy and slow. We have fast horses. Don't fight where he wants: draw him onto the open savanna and run rings round him." },
      6: { nombre: "The kidnapped griot", texto: "Your griot has escaped. Beat the guards chasing him.", voz: "Your chief of riders",
        historia: "Months ago, Sumaoro carried off Balla Fasséké, your griot, the voice who sings your story. Tonight he escaped! He's running towards our towers, but the sorcerer's guards are chasing him. Go and find him before they catch him." },
      7: { nombre: "The sorcerer's secret", texto: "Your sister brings Sumaoro's secret. Beat the guards surrounding her at the lake.", voz: "Your sister Nana Triban",
        historia: "Brother, I've come from Sumaoro's palace and I know his secret: his magic is useless against an arrow tipped with the spur of a white rooster. But his guards have followed me to the lake, and they're surrounding the paths. Help me cross." },
      8: { nombre: "The twelve kings", texto: "Sumaoro attacks before the twelve kings can gather. Hold, then strike back.", voz: "Balla Fasséké, the griot",
        historia: "With the secret in your hands, the twelve kings of the river have sworn loyalty to you. Sumaoro knows it, and has sent his whole army against you before the others arrive. You have to hold out until they're all together." },
      9: { nombre: "The mountains of Sosso", texto: "The sorcerer hides in his mountains. Get through before the rains come.", voz: "Your chief of riders",
        historia: "Sumaoro has lost and is falling back to his bare mountains. Behind them lies the plain of Kirina, where everything will be decided. But the rains are coming, and in twelve days the roads will be mud. We have to get through now." },
      10: { nombre: "Kirina", texto: "The battle of Kirina. Win and you'll be the first king of all Mali.", voz: "Sumaoro, the smith king",
        historia: "“Son of Sogolon. As a child you crawled along the ground, and now you come for me with twelve kings behind you.” Sumaoro speaks with a voice like thunder. “I am the smith king: iron obeys me. Come to Kirina, and we'll see whose name the griots sing tomorrow.”" },
    },
    saladino: {
      _: { nombre: "The Sultan", destino: "Hattin", pista: "A young soldier who ends up ruling Egypt and Syria, and a lord who breaks every truce. Ten chapters, one after another." },
      1: { nombre: "Alexandria", texto: "Your uncle has left you the city. Hold out and drive the enemy off the mines.", voz: "Shirkuh, your uncle",
        historia: "Nephew, I have to take the army out to find food. I'm leaving you in charge of Alexandria. You have few soldiers, and the Franks surround the city by land. I'm not asking you to win: I'm asking you not to lose it." },
      2: { nombre: "Vizier of Egypt", texto: "You're the new vizier. Make the emirs of the delta obey you.", voz: "Al-Qadi al-Fadil, your secretary",
        historia: "Your uncle has died, may he rest in peace, and the caliph has named you Vizier of Egypt: the one who rules in his name. But the emirs of the delta say you're too young a soldier. We have to show them who's in charge now." },
      3: { nombre: "Damietta", texto: "A huge fleet is attacking the mouth of the Nile. Defend Damietta.", voz: "Al-Qadi al-Fadil, your secretary",
        historia: "Two hundred ships, my lord! The Greeks of Byzantium and the Franks have come together to Damietta, at the mouth of the Nile. If the city falls, the river is open all the way to Cairo. We have to get there before they all land." },
      4: { nombre: "Damascus", texto: "The emirs are fighting over Damascus. Get there before anyone else.", voz: "Your brother al-Adil",
        historia: "Nur al-Din, the lord of Syria, has died and left a young son. His emirs are fighting over the city of Damascus like dogs over a bone. The people of the city will open the gates to us if we arrive first." },
      5: { nombre: "Aleppo", texto: "Aleppo, in the north, won't accept you. Cross the mountains and surround it.", voz: "Your brother al-Adil",
        historia: "Damascus is ours now, but Aleppo, in the north, doesn't want us. It has the highest walls in all Syria and lies behind the mountains. As long as Aleppo isn't with us, Syria will stay split in two." },
      6: { nombre: "Montgisard", texto: "You've lost half your gold. Beat your pursuers with what you have left.", voz: "Your brother al-Adil",
        historia: "We were overconfident, brother. We thought young King Baldwin wouldn't dare come out, and he surprised us at Montgisard. We've lost half the men and half the gold. Now we have to get back to Egypt across the river, and they're after us." },
      7: { nombre: "The caravans", texto: "Raynald attacks the caravans even though there's a truce. Drive his riders off the road.", voz: "A merchant on the road",
        historia: "My lord, help us! Raynald of Châtillon, the lord of Kerak castle, has attacked our caravan. There's a truce, but he doesn't care: he robs, burns and takes people prisoner. He says nobody will stop him." },
      8: { nombre: "Kerak castle", texto: "Surround Raynald's castle and break its walls.", voz: "Your brother al-Adil",
        historia: "We've reached Kerak, Raynald's nest. There's a wedding inside, and the groom's mother has sent us food from the feast. You've ordered no shots at the tower where the newlyweds sleep. At the rest of the castle, yes." },
      9: { nombre: "The wells of Sephoria", texto: "The enemy army leaves the water behind. Take the passes and leave them thirsty.", voz: "Al-Qadi al-Fadil, your secretary",
        historia: "The biggest army the Franks have ever gathered has left Sephoria, where they had water to spare, to come for us. It's terribly hot. If we take the passes on the road, they'll reach the battle dying of thirst." },
      10: { nombre: "The Horns of Hattin", texto: "The great battle between the two hills. Win and the enemy kingdom will fall.", voz: "Raynald of Châtillon",
        historia: "“Saladin. I broke your truce and I'd break it again.” Raynald shouts from the top of one of the two hills, his mouth dry. “I have the biggest army this kingdom has ever seen. Here, between these two horns of rock, I'll teach you what fighting is.”" },
    },
    mongoles: {
      _: { nombre: "Temujin", destino: "Chakirmaut", pista: "A boy abandoned on the steppe, a blood brother and the war for every tribe. Ten chapters, one after another." },
      1: { nombre: "The wooden yoke", texto: "Escape the Tayichiud camp and get back to your family.", voz: "Hoelun, your mother",
        historia: "Son, your father died of poison and the tribe left us alone on the steppe with nothing. Now the Tayichiud have caught you and put a wooden yoke round your neck. Tonight they're having a feast. Escape and come back to us." },
      2: { nombre: "The eight horses", texto: "Thieves have taken your horses. Chase them with your new friend.", voz: "Bo'orchu, your new friend",
        historia: "I don't know you at all, but I like you. Some thieves took your family's eight horses, didn't they? Take my horse, it's fresh, and let's go after them together. From today, what's yours is mine, and what's mine is yours." },
      3: { nombre: "Börte", texto: "The Merkits have taken your wife. Beat their warriors across the lake and rescue her.", voz: "Jamukha, your blood brother",
        historia: "Brother, I've heard. The Merkits came into your camp at night and took Börte, your wife. You're not going alone: when we were boys we swore to be brothers, and a brother doesn't stand and watch. My riders are coming with you." },
      4: { nombre: "The river pastures", texto: "The clans are choosing between Jamukha and you. Take the pastures before him.", voz: "Börte, your wife",
        historia: "I'm home now, thanks to you and Jamukha. But can't you see? The clans are starting to choose: some follow you and some follow him. Jamukha wants the rich ones; you want the ones who are worth something. Take the river pastures before the tribe splits in two." },
      5: { nombre: "The Tatars", texto: "The men who poisoned your father are in the desert. Go after them.", voz: "Bo'orchu, your friend",
        historia: "The Tatars, the ones who poisoned your father, have attacked the border of the Chinese empire. Its emperor will pay whoever punishes them. It's the chance to avenge your father, and get paid for it too. We'll cross the desert." },
      6: { nombre: "The thirteen camps", texto: "Jamukha has beaten you. With half your gold, hold out in the mountains and strike back.", voz: "Börte, your wife",
        historia: "Jamukha attacked you by surprise with thirteen camps of warriors, and you lost. He isn't your brother any more: now he's your rival. We have half the men and half the gold left. We have to reach the mountains before they catch us." },
      7: { nombre: "Toghrul's trap", texto: "Toghrul, who was like a father to you, has set a trap. Break out and beat the Keraites.", voz: "Bo'orchu, your friend",
        historia: "It's a trap, Temujin! Toghrul, khan of the Keraites, invited you to a wedding, but Jamukha has convinced him you're dangerous. His camps are closing in on us. We have to break through before they surround us completely." },
      8: { nombre: "The muddy water", texto: "You have few men left, but loyal ones. Surprise Toghrul's camp.", voz: "Börte, your wife",
        historia: "You only have a handful of men left, and you've drunk muddy water together, swearing never to part. They're few, but each is worth a hundred. Toghrul thinks you're finished and is celebrating. Tonight they won't be expecting you." },
      9: { nombre: "The campfires", texto: "The Naimans are twice as many. Make them think you're more and win the passes.", voz: "Bo'orchu, your friend",
        historia: "The last great people of the steppe, the Naimans, have joined Jamukha. They have twice as many men as we do. Tonight, let every soldier light five fires: when they see them, they'll think there are a great many of us." },
      10: { nombre: "Chakirmaut", texto: "The last battle for the whole steppe. Win and all the tribes will be one.", voz: "Jamukha",
        historia: "“Temujin, brother. When we were boys we played on the frozen river and I gave you a bone arrowhead.” Jamukha speaks from the mountain, with the Naimans behind him. “Now one of us has to take the whole steppe. Come and find me.”" },
    },
    eslavos: {
      _: { nombre: "Vesna", destino: "Spring", pista: "A burnt village, a girl the storms listen to, and every forest tribe against the khagan. Ten chapters, one after another." },
      1: { nombre: "The burning village", texto: "Drive the Avar riders out of the forest.", voz: "Grandmother Zlata",
        historia: "Vesna, child, the riders from the plain have burnt the village. You have the gift: the storms listen to you. Take whoever is left to the old forest. They don't know the paths; we do." },
      2: { nombre: "The river toll", texto: "Beat the khagan's collectors who hold the river crossings.", voz: "Radim, the blacksmith",
        historia: "The Avars charge us to cross the river: grain, furs and boys for their army. I forge the spears and you bring down the lightning. If we take both crossings from them, the toll is over." },
      3: { nombre: "The lake tribe", texto: "Borislav won't join you. Beat his warriors and show him you're stronger together.", voz: "Radim, the blacksmith",
        historia: "The lake tribe wants nothing to do with us. Their chief, Borislav, says a girl doesn't give orders to anyone. So prove him wrong: if you win, his warriors will follow you." },
      4: { nombre: "The thunder hills", texto: "The Avars keep watch from the hills. Drive them out before the bulk of their army arrives.", voz: "Borislav, chief of the lake",
        historia: "You beat me fairly, sorceress, and my word stands: my men are yours. From the thunder hills the Avars can see every road. If we take them, we'll know where they're coming from before they get here." },
      5: { nombre: "The long winter", texto: "Little gold and a lot of cold. Hold out in the forest and beat those who come for you.", voz: "Grandmother Zlata",
        historia: "I don't remember a winter this hard. The granaries are almost empty and the Avars know it: they're coming now that we're weak. But the cold is ours too. Let them come into the forest and see." },
      6: { nombre: "The traders on the coast", texto: "The Avars sell their prisoners on the coast. Beat the traders and their escort and free your people.", voz: "Radim, the blacksmith",
        historia: "Do you know where they take the people the Avars capture? They sell them to traders who come from the west along the coast. My brother is among them. If we win there, he'll come home, and many others with him." },
      7: { nombre: "The seven tribes", texto: "The khagan wants to buy the tribes that are wavering. Beat their chiefs before they sell out completely.", voz: "Borislav, chief of the lake",
        historia: "Seven tribes are meeting between the four towers to decide whether they go with you or with the Avars' gold. The khagan's envoys are already there, handing out gifts. Get there before they decide, and let them see which side the strength is on." },
      8: { nombre: "Out of the forest", texto: "For the first time you leave the forest. Hold the riders off in open ground and win.", voz: "Radim, the blacksmith",
        historia: "There are many of us now, Vesna, from every tribe. But as long as we keep hiding among the trees, the khagan will rule the plain. We have to go out. Their horses are fast, but our spears are long." },
      9: { nombre: "The Ring", texto: "The khagan has left his camp lightly guarded. Beat the guard of the Ring before he returns.", voz: "Grandmother Zlata",
        historia: "The Avars keep everything they've stolen in their great round camp, the Ring, surrounded by stockades. The khagan has ridden out with his army and left it with few guards. There won't be another chance like this, child." },
      10: { nombre: "Spring", texto: "The battle that decides who rules the plain and the forest.", voz: "Bayan, the khagan",
        historia: "“So you're the witch of the forest.” Khagan Bayan looks down at you from his horse, with his whole army behind him. “My grandfathers took tribute from your people, and my grandsons will take it from your grandchildren. Your spring ends here.”" },
    },
  },
  // nombres de los enemigos de las campañas (reinos y malos finales)
  reinos: { "Los ladrones del río": "The river thieves", "El señor de las minas": "The lord of the mines", "Casa de Lara": "House of Lara", "Casa de Haro": "House of Haro", "Guardia del paso oeste": "West pass guard", "Guardia del paso este": "East pass guard", "Señores del lago": "Lords of the lake", "Los del otro río": "The men across the river", "Las torres del Cuervo": "The Crow's towers", "Jinetes del Cuervo": "The Crow's riders", "Los del Cuervo": "The Crow's men", "Deudores del Cuervo": "The Crow's debtors", "Los fieles del Cuervo": "The Crow's faithful",
    "Los hombres de Knut": "Knut's men", "Piratas del estrecho": "Pirates of the straits", "Señores de la isla": "Lords of the island", "Soldados del emperador": "The emperor's soldiers", "Bandidos del río": "River bandits", "Jefes de Magnus": "Magnus's chieftains", "Reino de Dinamarca": "Kingdom of Denmark", "Señores de las islas": "Lords of the isles", "Los condes del norte": "The northern earls", "Los sajones": "The Saxons", "Reino de Inglaterra": "Kingdom of England",
    "Guardias del conde": "The earl's guards", "Jinetes del conde": "The earl's riders", "Barones del valle": "Barons of the valley", "Galeses del conde": "The earl's Welshmen", "Barones rebeldes": "Rebel barons", "Guarnición de Gloucester": "Gloucester garrison", "El joven Simón": "Young Simon", "Caballeros del joven Simón": "Young Simon's knights", "Galeses de Llywelyn": "Llywelyn's Welshmen", "Caballeros del conde": "The earl's knights", "Los barones del conde": "The earl's barons",
    "Guardia de la reina": "The queen's guard", "Ladrones de caballos": "Horse thieves", "Soldados de Sosso": "Soldiers of Sosso", "Aliados de Sumaoro": "Sumaoro's allies", "Herreros de Sosso": "Smiths of Sosso", "Guardia de Sumaoro": "Sumaoro's guard", "Ejército de Sosso": "Army of Sosso", "Reino de Sosso": "Kingdom of Sosso",
    "Los francos": "The Franks", "Emires del delta": "Emirs of the delta", "Flota de Bizancio": "Byzantine fleet", "Emires de Siria": "Emirs of Syria", "Guardia de Alepo": "Aleppo guard", "El rey Balduino": "King Baldwin", "Jinetes de Kerak": "Riders of Kerak", "Guardia de Kerak": "Kerak guard", "Ejército del reino": "The kingdom's army", "Señorío de Kerak": "Lordship of Kerak",
    "Jinetes ávaros": "Avar riders", "Cobradores del kagan": "The khagan's collectors", "Guerreros de Borislav": "Borislav's warriors", "Vigías ávaros": "Avar lookouts", "Tratantes del oeste": "Traders from the west", "Tribus que dudan": "Wavering tribes", "Emisarios del kagan": "The khagan's envoys", "Jinetes del kagan": "The khagan's riders", "Guardia del Anillo": "Guard of the Ring", "Kaganato ávaro": "Avar Khaganate",
    "Los taichiutos": "The Tayichiud", "Ladrones de la estepa": "Steppe thieves", "Los merkitas": "The Merkits", "Los de Yamuja": "Jamukha's men", "Clanes de la estepa": "Steppe clans", "Los tártaros": "The Tatars", "Los keraítas": "The Keraites", "Los naimanos": "The Naimans",
    "Alvar el Cuervo": "Alvar the Crow", "Harold, rey de Inglaterra": "Harold, King of England", "Simón de Montfort": "Simon de Montfort", "Sumaoro, el rey herrero": "Sumaoro, the smith king", "Reinaldo de Châtillon": "Raynald of Châtillon", "Yamuja": "Jamukha" },
  batallas: {
    navas: { nombre: "Las Navas de Tolosa", historia: "The Christian army had been stuck for days before a mountain range nobody knew how to cross. A shepherd showed them a hidden pass and they appeared on the other side, behind the Almohad camp.", regla: "Two relentless opponents. Whoever holds the mountain passes wins." },
    hastings: { nombre: "Hastings", historia: "William crossed the channel with his army while Harold was fighting the Vikings at the other end of the kingdom. Harold marched back exhausted and still held the hill all day.", regla: "A single relentless opponent. Triple starting gold and 12 turns: it's all decided at once." },
    granada: { nombre: "The siege of Granada", historia: "The last city of the Nasrid kingdom held out behind its towers, with the whole plain to supply it. The besiegers built a camp of stone to show they had no intention of leaving.", regla: "Three relentless opponents. The rich centre decides everything." },
    stirling: { nombre: "Stirling Bridge", historia: "The river was crossed only by a wooden bridge two riders wide. Wallace waited until half the English army was on the other side, and then came down from the hill.", regla: "One relentless opponent and a river with two crossings. Choose where you wait." },
    paris: { nombre: "The siege of Paris", historia: "Paris fitted entirely on an island in the Seine, joined to land by two fortified bridges. Hundreds of Viking ships came up the river in autumn and stayed for almost a year.", regla: "Three opponents, half the gold and 20 turns: a war of endurance." },
  },
  glosario: {
    partida: { titulo: "The game", texto: "A game is 15 turns (20 in duels; the campaign and the battle of the week set their own). Whoever has the most points at the end wins, or whoever wipes out the rest first. Everything costs gold: there are no other resources. Your points are shown at the top, next to the turn." },
    puntos: { titulo: "Points", texto: "Village 10, city 20, castle 15. Each hex of yours 1. Each gold mine of yours 2. Each key point (star) 10. Each enemy troop you kill 2, and the enemy hero 10. Each of your troops still alive is worth its upkeep. 1 point for every 10 gold you hold at the end." },
    turno: { titulo: "The turn", texto: "At the start of your turn you collect the gold from your settlements and mines, pay your troops' upkeep, the ones that rested heal, and the walls nobody attacked are repaired. Then you move and act with each troop and press End turn. Undo takes back a move; attacks can't be undone." },
    mover: { titulo: "Moving and acting", texto: "Tap one of your troops: the highlighted hexes are where it can go, the red ones who it can attack, the orange ones what it can besiege. Each troop has movement points (2 for most, 4 for cavalry) and one action per turn. A plain costs 2, forest and hill 4; as long as some point is left you can take one more step. Stepping on a hex makes it yours, key points included: moving is already conquering." },
    insignias: { titulo: "The badges on the map", texto: "When you select one of your troops its badges appear on the right: the shield digs it in (+10 defence until it moves), the hammers (peasants only) open Village and Castle, the red X disbands it and the i opens its full card. On your settlements: the hammers at the bottom left open the list of troops to recruit, the circle at the bottom right is the garrison (tap it to pick a troop inside) and the blue arrow at the top right upgrades a village to a city if you have the gold. Tapping the settlement anywhere else opens its card." },
    heroe: { titulo: "Your hero", texto: "Your hero is your faction's leader. He joins every game as one more troop, starts in your capital and costs no upkeep. His aura improves the troops next to him when he's out in the open. If he dies he doesn't come back in that game (unless he carries a draught) and your opponent gains 10 points. Outside the game, each faction levels up on its own, from 1 to 10, with the points you pile up: its own unit is yours from level 1 and the leader's power opens at level 5. Each step gives an upgrade point to spend on his card, and that's also where you equip items." },
    terreno: { titulo: "Terrain", texto: "Forests and hills cost double and give +10 defence to whoever stands on them. From a hill, archers shoot one hex further. Mountains can't be crossed. Garrisoned troops don't get the terrain bonus: they already have the one from the walls." },
    solo_oro: { titulo: "Mines and key points", texto: "Gold mines (the coin) give 1 gold per turn if they're linked by your own hexes to a settlement of yours; an enemy troop standing on one stops it. Key points (the star) produce nothing but are worth 10 points at the end to whoever holds them then: the same as a whole village. Stepping on them is enough to make them yours." },
    dano: { titulo: "How damage is worked out", texto: "Damage = attack − defence, minimum 10. Before attacking you see what you'll deal and what you'll take. If the defender survives and the attacker was melee, it counterattacks by the same rule. Archers, crossbowmen and catapults attack at range without taking a counterattack. War machines (catapult, trebuchet) never counterattack." },
    dado: { titulo: "The die", texto: "Every blow rolls a hidden die: two out of three blows land exactly; one in six deals 10 more (clean hit) and one in six deals 10 less (glancing)." },
    heridas: { titulo: "Wounds and healing", texto: "A wounded troop hits weaker: its real attack is its attack times the health it has left. A troop that does nothing on its turn recovers 10 health in its own territory and 20 inside a settlement. The monk heals 10 to the troops next to him at the end of your turn." },
    triangulo: { titulo: "Sword, spear and horse", texto: "The swordsman beats the spearman (+15: he slips inside the pikes). The spearman beats the knight (+15: the wall of spears). The knight beats the swordsman (+15: the charge). The swordsman stops arrows with his buckler (+10 defence against ranged troops). The halberdier carries a polearm but the swordsman has no bonus against him. Archers wear everyone down and die if anything reaches them." },
    avanzar: { titulo: "Advancing after a kill", texto: "When a melee troop kills another, it advances onto the dead one's hex and makes it yours, even if it was attacking from inside a settlement (a sally). Shooters don't advance. If the dead one was the last of a garrison and the walls are at zero, the attacker walks in and takes the settlement; if the walls still stand, it stays outside." },
    guarnicion: { titulo: "Garrison", texto: "A settlement doesn't defend itself: it has garrison slots (1 for a village, more for a city and a castle). Move a troop inside to garrison it: it gains the walls' defence bonus and pays half upkeep. Shooters fire from inside without exposing themselves; melee troops can make a sally (without the bonus on that blow). With no garrison and a breach, the enemy just walks in. A recruited troop goes into a free slot or appears beside it." },
    murallas: { titulo: "Walls and sieges", texto: "The walls are the settlement's integrity (top left of its hex). While they stand, the garrison has the defence bonus. Besieging hits them: the catapult from a distance and without exposing itself (hurting the garrison on the way); infantry with ladders, slowly and taking a counterattack. At 0 there's a breach." },
    conquista: { titulo: "Conquering", texto: "To take a settlement: kill the whole garrison, bring the walls to zero and walk in. If a melee troop kills the last defender with the breach already open, it walks in on the same blow. A captured city drops to a village; a castle stays a castle. Castles are built by a peasant on a hex of yours (the hammers on his badge), never closer than 2 hexes to an enemy settlement." },
    fundar: { titulo: "Founding a village", texto: "A peasant on a hex of yours, three or more hexes from any settlement, founds a village for 20 gold (the hammers on his badge); the peasant is used up. A village upgrades to a city for 40 gold with the blue arrow: more garrison, stronger walls and it recruits everything. Villages only recruit peasants." },
    experiencia: { titulo: "Experience", texto: "Every fight survived gives one experience point; a kill gives two more. At 3 points the troop is a Veteran (+5 attack, +5 defence); at 8, Elite (+10 and +10). It shows as chevrons. The hero doesn't earn chevrons: his progress is the one outside the game." },
    mantenimiento: { titulo: "Upkeep and bankruptcy", texto: "Every troop costs gold per turn (half if it's garrisoned). When you press End turn the game warns you if you won't be able to pay next turn. If you can't, troops desert starting with the cheapest. You can disband troops with the red X on their badge, with no refund." },
    victoria: { titulo: "Victory and elimination", texto: "On the last turn whoever has the most points wins; before that, whoever wipes out the rest. A realm is wiped out when it has no settlements and no troops. In online duels there are 60 seconds per turn; three turns without touching anything, or 30 seconds disconnected, counts as forfeiting." },
    dificultad: { titulo: "Easy, normal and hard", texto: "Easy: clumsy opponents, for learning. Normal: opponents with a plan, each with its own character (guardian, expansionist, warlike…). Hard: relentless opponents who come for you, hunt your hero if they see him wounded, step on every mine and key point and start with 25% more gold." },
    fuera: { titulo: "Outside the game", texto: "When you finish you add up points (leaderboard, faction level and account level) and hero gold (for the item shop or to get factions). There are three quests a day and two a week, a streak of days played, medals with rewards, the daily map (the same for everyone), six campaigns of ten hand-made maps (one per faction) with rewards, the battle of the week (a map with its own rules that changes on Monday, with its own leaderboard), online duels with Elo and a weekly league, and challenges to friends by code." },
  },
  legal: {
    actualizado: "15 September 2026",
    privacidad: {
      titulo: "Privacy policy",
      secciones: [
        { h: "The short version", p: "You can play the whole game with no account and without giving us any data. An account is only needed to appear on the leaderboard and to play duels against other people." },
        { h: "Who is responsible", p: "{titular}. For anything about your data, write to {contacto}." },
        { h: "What we keep if you create an account", p: "Your email and your password (encrypted, we never see it), the name you choose for the leaderboard, your hero and his level, the score of the games you send, the duels you play and your Elo. Nothing else: we don't ask for your real name, your age, your location or your contacts." },
        { h: "What we keep without an account", p: "Your game, your hero and your records stay on the device itself (browser storage) and never leave it. We also keep a few anonymous usage notes (that the game was opened, that a game was started or finished) with a random device identifier, to know whether the game makes sense to people. They can't be linked to you." },
        { h: "What for", p: "So that the leaderboard, the duels and your progress across devices work, and to improve the game. No advertising and no commercial profiling." },
        { h: "Who we share it with", p: "Nobody, except the provider that hosts the database (Supabase), which acts on our behalf and keeps the data in {paisDatos}. Your player name, your hero and your score are public inside the game: that's what a leaderboard is. Your email is never shown." },
        { h: "Purchases", p: "Factions are bought through Google Play or the App Store, and they handle the payment: we never see your card. To know what you've bought we use RevenueCat, which receives an anonymous identifier (or your account's, if you have one) and the list of your purchases, never your payment details." },
        { h: "How long", p: "As long as you have the account. If you delete it, everything of yours is deleted right away. The anonymous usage notes are kept for a year at most." },
        { h: "Your rights", p: "You can see, correct or delete your data whenever you want. To delete everything there's a «Delete my account» button in Settings; you can also ask by writing to {contacto}. You have the right to complain to the data protection authority in your country." },
        { h: "Age", p: "The game isn't meant for children under {edad}. If that's you, ask a parent or guardian to create the account, or play without one." },
        { h: "Changes", p: "If this changes, you'll be told in the game. Last updated: {actualizado}." },
      ],
    },
    condiciones: {
      titulo: "Terms of use",
      secciones: [
        { h: "What this is", p: "Final War: Medieval is a turn-based strategy game. Using it is free. By playing you accept these terms." },
        { h: "Your account", p: "You're responsible for what's done with your account and for keeping your password safe. Choose a name that doesn't insult anyone, impersonate anyone or advertise anything; offensive names are changed or removed." },
        { h: "Fair play", p: "No cheating: modifying the game to get fake scores, automating games, abusing bugs or making extra accounts to inflate the leaderboard. If that happens the score is corrected and, if it's repeated, the account is closed." },
        { h: "Duels", p: "Duels are live and on the clock. If you leave or lose connection, the game may be counted as lost: that's only fair on the person waiting at the other end." },
        { h: "What's inside", p: "The game, its texts, drawings and music belong to their authors; the music has its own licence, credited in Settings → Credits. You can take screenshots and videos and post them wherever you like." },
        { h: "Purchases", p: "The game is free with two factions. The other five are sold in the app stores (Google Play and App Store) and can also be earned with hero gold. A purchase is a licence to use that faction in the game for as long as the game exists; refunds follow each store's rules. You can restore your purchases from the faction shop." },
        { h: "No warranties", p: "The game is offered as it is. It may have bugs, it may stop being available and you may lose progress (especially if you play without an account). We're not liable for damages arising from using it." },
        { h: "Changes and leaving", p: "These terms may change; you'll be told in the game. You can leave whenever you want by deleting your account from Settings." },
        { h: "Contact", p: "{contacto}. Last updated: {actualizado}." },
      ],
    },
  },
};
