// English for everything that lives inside the data (names, descriptions, traits, quests, medals, items…).
// The loader swaps these in when the language is English; anything missing stays in Spanish.
// Keys are the internal ids, so they never change when the Spanish wording changes.
window.FWM = window.FWM || {};
FWM.traducciones = FWM.traducciones || {};

FWM.traducciones.en = {
  tropas: {
    campesino: { nombre: "Peasant", descripcion: "The basic troop. Cheap, weak, and the only one that can found villages. Good for claiming ground and for filling garrisons." },
    lancero: { nombre: "Spearman", descripcion: "Solid infantry. Good defence: it goes in front and takes the hits. Its wall of pikes punishes cavalry (+15), but a swordsman slips inside it." },
    arquero: { nombre: "Archer", descripcion: "Shoots the neighbouring hex without taking a counterattack (two hexes from a hill). It wears the enemy down rather than killing. In a garrison it defends from inside without exposing itself." },
    espadachin: { nombre: "Swordsman", descripcion: "Nimble, deadly infantry. Slips inside the spears (+15 against spearmen) and its buckler stops arrows (+10 defence against ranged troops), but a cavalry charge rolls over it." },
    caballero: { nombre: "Knight", descripcion: "The shock troop. Hits hard, moves two hexes and takes a beating. Its charge rolls over swordsmen (+15), but it fears the wall of spears. Expensive to recruit and to keep." },
    catapulta: { nombre: "Catapult", descripcion: "The siege engine. Breaks walls from two hexes away and hits the garrison on the way, out of reach of archers. It can't move and shoot in the same turn and it can't defend itself: escort it." },
    monje: { nombre: "Monk", descripcion: "Doesn't fight: heals. At the end of your turn it heals 10 to each of your troops next to it. Weak and with no counterattack: keep it behind the line." },
    ballestero: { nombre: "Crossbowman", descripcion: "A flat shot that punches through armour (+10 against armoured troops). Like the catapult, it can't move and shoot in the same turn." },
    alabardero: { nombre: "Halberdier", descripcion: "Long halberd: +15 against cavalry, and the swordsman finds no way in (no bonus against it). Steady armoured infantry." },
    infanteria_pesada: { nombre: "Heavy infantry", descripcion: "A shield wall. The toughest troop on foot: it takes whatever you throw at it (+10 defence against ranged troops) and its maces open breaches in walls. Slow and expensive to keep." },
    caballeria_pesada: { nombre: "Heavy cavalry", descripcion: "The charge that decides the battle. Rolls over swordsmen (+15) and sweeps away archers and machines (+20). Only a wall of spears stops it. Costs a fortune every turn." },
    trabuco: { nombre: "Trebuchet", descripcion: "The wall-breaker. Hits from three hexes, out of reach of everything, and brings a wall down in two shots. It can't move and shoot in the same turn, and in the open it's a sitting target." },
    heroe_espadachin: { nombre: "Swordsman", descripcion: "Balanced. Slips between the spears and his buckler stops arrows. His presence makes the troops beside him tougher." },
    heroe_arquero: { nombre: "Archer", descripcion: "Shoots one hex away without taking a counterattack, and further from a hill. He spurs on the shooters." },
    heroe_nordico: { nombre: "Norseman", descripcion: "Hits like no one else, and hits harder the more wounded he is. Little armour. His shouts fire up those beside him." },
    heroe_alquimista: { nombre: "Alchemist", descripcion: "Throws fire at a hex: the target burns and the enemies next to it are scorched. His salves heal those beside him." },
  },
  asentamientos: {
    pueblo: { nombre: "Village", descripcion: "The starting settlement and the way to expand. A peasant founds it. It gives gold, recruits peasants and has one garrison slot." },
    ciudad: { nombre: "City", descripcion: "An upgraded village. It's your economy and your quality army: more gold, recruits every troop, and it's the only place troops can be upgraded." },
    castillo: { nombre: "Castle", descripcion: "Pure defence. Built on any empty hex of yours. Three garrison slots, thick walls and a big defence bonus for whoever is inside. It produces almost nothing." },
  },
  terrenos: {
    llanura: { nombre: "Plain", descripcion: "Open ground. Costs one step and gives nothing." },
    bosque: { nombre: "Forest", descripcion: "Costs double to move through (a slow troop spends its whole turn entering). Whoever is inside gains +10 defence. Timber comes from forests with a resource." },
    colina: { nombre: "Hill", descripcion: "Costs double to move through (a slow troop spends its whole turn entering). +10 defence, and archers shoot one hex further from up there. Quarries and mines are usually here." },
    montana: { nombre: "Mountain", descripcion: "Impassable. It creates passes and bottlenecks." },
    agua: { nombre: "Water", descripcion: "Impassable." },
  },
  yacimientos: {
    bosque: { nombre: "Woodland", descripcion: "Gives timber while it's yours and connected to a settlement of yours." },
    mina_oro: { nombre: "Gold mine", descripcion: "Gives gold. The resource you need most: everything costs gold." },
    cantera: { nombre: "Quarry", descripcion: "Gives stone, for castles and defences." },
    mina_hierro: { nombre: "Iron mine", descripcion: "Gives iron, for heavy troops and catapults." },
    punto_clave: { nombre: "Key point", descripcion: "Produces nothing. Worth 10 points at the end of the game to whoever holds it then. Start thinking about them early." },
  },
  recursos: {
    oro: { nombre: "Gold", descripcion: "The currency for everything: recruiting, upkeep, building and research. It comes from settlements and gold mines." },
    madera: { nombre: "Timber", descripcion: "Comes from forests. For upgrading to a city, light troops and catapults." },
    piedra: { nombre: "Stone", descripcion: "Comes from quarries. For castles and fortifications." },
    hierro: { nombre: "Iron", descripcion: "Comes from iron mines. For knights and catapults." },
  },
  tecnologias: {
    agricultura: { nombre: "Agriculture", descripcion: "Every village and city produces +1 gold. Allows upgrading a village to a city." },
    canteria: { nombre: "Masonry", descripcion: "Every quarry produces +1 stone." },
    maquinaria: { nombre: "Machinery", descripcion: "Every forest produces +1 timber." },
    milicia: { nombre: "Militia", descripcion: "Allows recruiting spearmen." },
    fortificacion: { nombre: "Fortification", descripcion: "Castles: +1 garrison slot, +10 defence, +40 walls." },
    catapulta: { nombre: "Catapult", descripcion: "Allows recruiting catapults." },
    arqueria: { nombre: "Archery", descripcion: "Allows recruiting archers." },
    caballeria: { nombre: "Cavalry", descripcion: "Allows recruiting knights." },
  },
  bandos: {
    castilla: { nombre: "Crown of Castile", rasgo: "Castles cost half the stone (in Quick games, 25% less gold).", descripcion: "A land of castles. The Reconquista was won by fortifying every frontier." },
    inglaterra: { nombre: "Kingdom of England", rasgo: "Archers +10 attack.", descripcion: "The longbow decided whole battles. Its archers are the best in the known world." },
    francia: { nombre: "Kingdom of France", rasgo: "Knights +10 defence and 5 gold cheaper.", descripcion: "French heavy cavalry is the hammer of Europe: expensive, slow to muster, unstoppable." },
    ming: { nombre: "Ming Dynasty", rasgo: "Catapults +20 siege and range 4.", descripcion: "Gunpowder, engineers and walls: nobody besieges like the Middle Kingdom." },
    abasi: { nombre: "Abbasid Caliphate", rasgo: "Every gold mine produces +1.", descripcion: "Baghdad, the House of Wisdom and the gold routes: trade is their army." },
    azteca: { nombre: "Aztec Empire", rasgo: "Peasants +10 attack and troops gain double experience.", descripcion: "Jaguar and eagle warriors: the infantry is the army, and every battle forges veterans." },
  },
  heroesClases: {
    espadachin: { nombre: "Swordsman", descripcion: "Balanced. Slips between the spears and his buckler stops arrows. His presence makes the troops beside him tougher.", rasgo: "+10 against spears, +5 defence against arrows. Aura: +1 defence." },
    arquero: { nombre: "Archer", descripcion: "Shoots one hex away without taking a counterattack, and further from a hill. He spurs on the shooters.", rasgo: "Shoots 1 hex; +1 range on a hill. Aura: +1 attack to ranged troops." },
    nordico: { nombre: "Norseman", descripcion: "Hits like no one else, and hits harder the more wounded he is. Little armour. His shouts fire up those beside him.", rasgo: "Fury: +5 attack for every 25 health lost (up to +10). Aura: +1 attack." },
    alquimista: { nombre: "Alchemist", descripcion: "Throws fire at a hex: the target burns and the enemies next to it are scorched. His salves heal those beside him.", rasgo: "Fire: his attack burns 5 on enemies next to the target. Aura: resting troops heal +3 more." },
  },
  heroesNiveles: { 1: "Recruit", 2: "Squire", 3: "Soldier", 4: "Knight", 5: "Lord", 6: "King", 7: "Emperor", 8: "The Legend" },
  heroesMejoras: {
    vigor: { nombre: "Vigour", texto: "+5 hero health" },
    filo: { nombre: "Edge", texto: "+1 hero attack" },
    temple: { nombre: "Mettle", texto: "+1 hero defence" },
    paso_ligero: { nombre: "Light step", texto: "+1 hero movement" },
    segundo_aliento: { nombre: "Second wind", texto: "The hero heals 10 at the start of your turn if he didn't attack on the previous one" },
    coraza: { nombre: "Cuirass", texto: "+2 hero defence against ranged troops" },
    escudo_hermanos: { nombre: "Shield of brothers", texto: "Troops next to the hero: +1 defence" },
    grito: { nombre: "War cry", texto: "Troops next to the hero: +1 attack" },
    cirujano: { nombre: "Surgeon", texto: "Troops next to the hero that rest heal +3 more" },
    estandarte: { nombre: "Banner", texto: "The aura reaches 2 hexes" },
    disciplina: { nombre: "Discipline", texto: "Troops next to the hero and dug in: +2 more defence" },
    inspiracion: { nombre: "Inspiration", texto: "Troops next to the hero: +1 experience per fight" },
    tesorero: { nombre: "Treasurer", texto: "+1 gold per turn" },
    leva: { nombre: "Levy", texto: "Peasants cost 1 gold less" },
    armero: { nombre: "Armourer", texto: "Swordsmen and spearmen cost 1 gold less" },
    cantero: { nombre: "Stonemason", texto: "Your settlements' walls: +5 maximum integrity" },
    forrajeo: { nombre: "Foraging", texto: "Troops in your own territory heal +2 more" },
    maestre: { nombre: "Master of the household", texto: "The capital can recruit twice per turn" },
    caminos: { nombre: "Roads", texto: "Your troops move +1 if they start the turn in your own territory" },
    gala: { nombre: "Finery", texto: "A piece of finery (looks only)" },
  },
  medallas: {
    primera_victoria: { nombre: "First victory", descripcion: "Win your first game." },
    intacto: { nombre: "Not a scratch", descripcion: "Win against 3 opponents (or a duel) without losing a single troop." },
    del_dia: { nombre: "King of the day", descripcion: "Daily maps won: {n}." },
    relampago: { nombre: "Lightning", descripcion: "Win before turn {n}." },
    carnicero: { nombre: "Butcher", descripcion: "Kill {n} enemy troops in one game." },
    estratega: { nombre: "Strategist", descripcion: "Finish a game holding {n} key points." },
    conquistador: { nombre: "Conqueror", descripcion: "Take {n} settlements in one game." },
    racha5: { nombre: "Unstoppable", descripcion: "Win {n} games in a row." },
    fuego7: { nombre: "Constancy", descripcion: "Play {n} days in a row." },
    tres_bandos: { nombre: "Diplomat", descripcion: "Win with {n} different realms." },
    veterano: { nombre: "Veteran", descripcion: "Play {n} games." },
    cazador: { nombre: "Hunter", descripcion: "Enemy heroes slain: {n}." },
    duelista: { nombre: "Duellist", descripcion: "Duels won against other players: {n}." },
    implacable: { nombre: "Tamer", descripcion: "Games won on hard: {n}." },
    campana: { nombre: "Chronicler", descripcion: "Beat {n} campaign maps." },
  },
  objetos: {
    espada_hierro: { nombre: "Iron sword", texto: "+1 attack" },
    lanza_larga: { nombre: "Long spear", texto: "+15 against cavalry" },
    hacha: { nombre: "Woodcutter's axe", texto: "+10 siege" },
    espada_capitan: { nombre: "Captain's sword", texto: "+2 attack; troops beside him +1 attack" },
    mandoble: { nombre: "Greatsword", texto: "+3 attack, −1 defence" },
    rodela: { nombre: "Buckler", texto: "+1 defence" },
    escudo_torre: { nombre: "Tower shield", texto: "+2 defence against ranged troops" },
    escudo_blason: { nombre: "Blazoned shield", texto: "+1 defence to troops garrisoned with the hero" },
    egida: { nombre: "Aegis", texto: "+3 defence" },
    mula: { nombre: "Mule", texto: "+5 health" },
    caballo: { nombre: "Horse", texto: "+1 movement" },
    corcel: { nombre: "Warhorse", texto: "+1 movement, +1 attack" },
    gorro_lana: { nombre: "Woollen cap", texto: "+5 health" },
    yelmo: { nombre: "Helm", texto: "+1 defence, +5 health" },
    corona_laurel: { nombre: "Laurel crown", texto: "+1 gold per turn" },
    corona_rey: { nombre: "King's crown", texto: "+2 gold per turn, +1 defence" },
    pocima: { nombre: "Resurrection draught", texto: "If the hero dies, he returns to the capital next turn with half his health. It's used up." },
    capa_embajador: { nombre: "Ambassador's cloak", texto: "Looks only: a green and gold cloak" },
  },
  misiones: {
    gana: "Win a game",
    gana_bando: "Win with {bando}",
    mata8: "Kill 8 troops in one game",
    funda2: "Found 2 villages in one game",
    dia: "Play the daily map",
    heroe_vivo: "Win with your hero alive",
    toma1: "Take a settlement",
    clave4: "Finish holding 4 key points",
    rapido: "Win before turn 16",
    pierde2: "Win losing 2 troops or fewer",
    mata5: "Kill 5 troops in one game",
    duelo: "Play an online duel",
    gana_duelo: "Win an online duel",
    heroe_mata: "Slay the enemy hero",
    clave2: "Finish holding 2 key points",
    toma2: "Take 2 settlements in one game",
    gana_rapida: "Win a Quick game",
    juega2: "Play 2 games",
    mata12: "Kill 12 troops across all of today's games",
    gana2: "Win 2 games",
    s_gana5: "Win 5 games",
    s_mata40: "Kill 40 troops",
    s_duelos3: "Play 3 online duels",
    s_bandos3: "Win with 3 different realms",
    s_dias3: "Play 3 daily maps",
    s_toma5: "Take 5 settlements",
    s_heroes5: "Slay 5 heroes",
  },
  mapas: {
    hoz: { nombre: "The Gorge", texto: "A river splits the land in two; there are only two fords." },
    torres: { nombre: "The Four Towers", texto: "Four realms in the corners and the riches in the middle." },
    isla: { nombre: "The Island", texto: "A lake in the middle; the land bridges decide the game." },
    sierra: { nombre: "The Mountain Pass", texto: "A range crosses the map; you have to go through the passes." },
    costa: { nombre: "The Wild Coast", texto: "A strip of land between the sea and the mountains." },
    europa: { nombre: "Europe", texto: "From Iberia to Constantinople. Twelve possible realms, a whole continent and plenty of room to get it wrong." },
    iberia: { nombre: "Iberia", texto: "Five crowns in one peninsula. Every border is a war half finished." },
    britannia: { nombre: "Britannia", texto: "Scotland, England, the Norsemen of Dublin and the continent across the channel." },
    arena: { nombre: "The Palisade", texto: "A valley open on all four sides. Nobody is coming to help." },
  },
  escenarios: {
    europa: { nombre: "Europe", texto: "From Iberia to Constantinople. Twelve possible realms, a whole continent and plenty of room to get it wrong." },
    iberia: { nombre: "Iberia", texto: "Five crowns in one peninsula. Every border is a war half finished." },
    britannia: { nombre: "Britannia", texto: "Scotland, England, the Norsemen of Dublin and the continent across the channel." },
  },
  campana: {
    1: { nombre: "The first fief", texto: "A weak neighbour on the other side of the river. Learn to cross and to take his village." },
    2: { nombre: "The northern mines", texto: "The coast is narrow and the mines are few. Whoever holds them rules." },
    3: { nombre: "Three realms", texto: "Two opponents and a rich centre. Don't let them share it out." },
    4: { nombre: "The mountain pass", texto: "The range is only crossed through the passes. Hold them or take them." },
    5: { nombre: "The island", texto: "Three realms around the lake. The land bridges are worth gold." },
    6: { nombre: "Empty coffers", texto: "You start with half the gold. Every coin counts." },
    7: { nombre: "The siege", texto: "Three relentless realms all around you. Hold out and hit back." },
    8: { nombre: "The charge", texto: "Open plains and three opponents. Win and the warhorse is yours." },
    9: { nombre: "Iron mountains", texto: "Little time and a lot of passes to hold." },
    10: { nombre: "The throne", texto: "The last battle. Win and you'll wear the king's crown." },
  },
  batallas: {
    navas: { nombre: "Las Navas de Tolosa", historia: "The Christian army had been stuck for days before a mountain range nobody knew how to cross. A shepherd showed them a hidden pass and they appeared on the other side, behind the Almohad camp.", regla: "Two relentless opponents. Whoever holds the mountain passes wins." },
    hastings: { nombre: "Hastings", historia: "William crossed the channel with his army and had the ships burned on the beach: there would be no retreat. Harold arrived exhausted from the north and still held the hill all day.", regla: "A single relentless opponent. Triple starting gold and 12 turns: it's all decided at once." },
    granada: { nombre: "The siege of Granada", historia: "The last city of the Nasrid kingdom held out behind its towers, with the whole plain to supply it. The besiegers built a camp of stone to show they had no intention of leaving.", regla: "Three relentless opponents. The rich centre decides everything." },
    stirling: { nombre: "Stirling Bridge", historia: "The river was crossed only by a wooden bridge two riders wide. Wallace waited until half the English army was on the other side, and then came down from the hill.", regla: "One relentless opponent and a river with two crossings. Choose where you wait." },
    paris: { nombre: "The siege of Paris", historia: "Paris fitted entirely on an island in the Seine, joined to land by two fortified bridges. Hundreds of Viking ships came up the river in autumn and stayed for almost a year.", regla: "Three opponents, half the gold and 20 turns: a war of endurance." },
  },
  glosario: {
    partida: { titulo: "The game", texto: "A game is 15 turns (20 in duels; the campaign and the battle of the week set their own). Whoever has the most points at the end wins, or whoever wipes out the rest first. Everything costs gold: there are no other resources. Your points are shown at the top, next to the turn." },
    puntos: { titulo: "Points", texto: "Village 10, city 20, castle 15. Each hex of yours 1. Each gold mine of yours 2. Each key point (star) 10. Each enemy troop you kill 2, and the enemy hero 10. Each of your troops still alive is worth its upkeep. 1 point for every 10 gold you hold at the end." },
    turno: { titulo: "The turn", texto: "At the start of your turn you collect the gold from your settlements and mines, pay your troops' upkeep, the ones that rested heal, and the walls nobody attacked are repaired. Then you move and act with each troop and press End turn. Undo takes back a move; attacks can't be undone." },
    mover: { titulo: "Moving and acting", texto: "Tap one of your troops: the highlighted hexes are where it can go, the red ones who it can attack, the orange ones what it can besiege. Each troop has movement points (2 for most, 4 for cavalry) and one action per turn. A plain costs 2, forest and hill 4; as long as some point is left you can take one more step. Stepping on a hex makes it yours, key points included: moving is already conquering." },
    insignias: { titulo: "The badges on the map", texto: "When you select one of your troops its badges appear on the right: the shield digs it in (+10 defence until it moves), the hammers (peasants only) open Village and Castle, the red X disbands it and the i opens its full card. On your settlements: the hammers at the bottom left open the list of troops to recruit, the circle at the bottom right is the garrison (tap it to pick a troop inside) and the blue arrow at the top right upgrades a village to a city if you have the gold. Tapping the settlement anywhere else opens its card." },
    heroe: { titulo: "Your hero", texto: "Your hero joins every game as one more troop, starts in your capital and costs no upkeep. He is one of four classes (swordsman, archer, norseman, alchemist), each with its own trait, and his aura improves the troops next to him when he's out in the open. If he dies he doesn't come back in that game (unless he carries a draught) and your opponent gains 10 points. Outside the game he levels up with the points you pile up: each step gives an upgrade point to spend on his card, and each level unlocks a new unit. The items you find are equipped on his card." },
    terreno: { titulo: "Terrain", texto: "Forests and hills cost double and give +10 defence to whoever stands on them. From a hill, archers shoot one hex further. Mountains can't be crossed. Garrisoned troops don't get the terrain bonus: they already have the one from the walls." },
    solo_oro: { titulo: "Mines and key points", texto: "Gold mines (the coin) give 1 gold per turn if they're linked by your own hexes to a settlement of yours; an enemy troop standing on one stops it. Key points (the star) produce nothing but are worth 10 points at the end to whoever holds them then: the same as a whole village. Stepping on them is enough to make them yours." },
    dano: { titulo: "How damage is worked out", texto: "Damage = attack − defence, minimum 10. Before attacking you see what you'll deal and what you'll take. If the defender survives and the attacker was melee, it counterattacks by the same rule. Archers, crossbowmen and catapults attack at range without taking a counterattack. War machines (catapult, trebuchet) never counterattack." },
    dado: { titulo: "The die", texto: "Every blow rolls a hidden die: two out of three blows land exactly; one in six deals 10 more (clean hit) and one in six deals 10 less (glancing)." },
    heridas: { titulo: "Wounds and healing", texto: "A wounded troop hits weaker: its real attack is its attack times the health it has left. A troop that does nothing on its turn recovers 10 health in its own territory and 20 inside a settlement. The monk heals 10 to the troops next to him at the end of your turn." },
    triangulo: { titulo: "Sword, spear and horse", texto: "The swordsman beats the spearman (+15: he slips inside the pikes). The spearman beats the knight (+15: the wall of spears). The knight beats the swordsman (+15: the charge). The swordsman stops arrows with his buckler (+10 defence against ranged troops). The halberdier carries a polearm but the swordsman has no bonus against him. Archers wear everyone down and die if anything reaches them." },
    avanzar: { titulo: "Advancing after a kill", texto: "When a melee troop kills another, it advances onto the dead one's hex and makes it yours, even if it was attacking from inside a settlement (a sally). Shooters don't advance. If the dead one was the last of a garrison and the walls are at zero, the attacker walks in and takes the settlement; if the walls still stand, it stays outside." },
    guarnicion: { titulo: "Garrison", texto: "A settlement doesn't defend itself: it has garrison slots (1 for a village, more for a city and a castle). Move a troop inside to garrison it: it gains the walls' defence bonus and pays half upkeep. Shooters fire from inside without exposing themselves; melee troops can make a sally (without the bonus on that blow). With no garrison and a breach, the enemy just walks in. A recruited troop goes into a free slot or appears beside it." },
    murallas: { titulo: "Walls and sieges", texto: "The walls are the settlement's integrity (top left of its hex). While they stand, the garrison has the defence bonus. Besieging hits them: the catapult from a distance and without exposing itself (hurting the garrison on the way); infantry with ladders, slowly and taking a counterattack. At 0 there's a breach." },
    conquista: { titulo: "Conquering", texto: "To take a settlement: kill the whole garrison, bring the walls to zero and walk in. If a melee troop kills the last defender with the breach already open, it walks in on the same blow. A captured city drops to a village; a castle stays a castle. Castles are built by a peasant on a hex of yours (the hammers on his badge), never closer than 2 hexes to an enemy settlement." },
    fundar: { titulo: "Founding a village", texto: "A peasant on a hex of yours, three or more hexes from any settlement, founds a village for 20 gold (the hammers on his badge); the peasant is used up. A village upgrades to a city for 40 gold with the blue arrow: more garrison, stronger walls and it recruits everything. Villages only recruit peasants." },
    experiencia: { titulo: "Experience", texto: "Every fight survived gives one experience point; a kill gives two more. At 3 points the troop is a Veteran (+5 attack, +5 defence); at 8, Elite (+10 and +10). It shows as chevrons. The hero doesn't earn chevrons: his progress is the one outside the game." },
    mantenimiento: { titulo: "Upkeep and bankruptcy", texto: "Every troop costs gold per turn (half if it's garrisoned). When you press End turn the game warns you if you won't be able to pay next turn. If you can't, troops desert starting with the cheapest. You can disband troops with the red X on their badge, with no refund." },
    victoria: { titulo: "Victory and elimination", texto: "On the last turn whoever has the most points wins; before that, whoever wipes out the rest. A realm is wiped out when it has no settlements and no troops. In online duels there are 60 seconds per turn; three turns without touching anything, or 30 seconds disconnected, counts as forfeiting." },
    dificultad: { titulo: "Easy, normal and hard", texto: "Easy: clumsy opponents, for learning. Normal: opponents with a plan, each with its own character (guardian, expansionist, warlike…). Hard: relentless opponents who come for you, hunt your hero if they see him wounded, step on every mine and key point and start with 25% more gold." },
    fuera: { titulo: "Outside the game", texto: "When you finish you add up points (leaderboard and hero level) and hero gold (for the item shop). There are three quests a day and two a week, a streak of days played, medals with rewards, the daily map (the same for everyone), a campaign of ten hand-made maps with rewards, the battle of the week (a map with its own rules that changes on Monday, with its own leaderboard), online duels with Elo and a weekly league, and challenges to friends by code." },
  },
  legal: {
    privacidad: {
      titulo: "Privacy policy",
      secciones: [
        { h: "The short version", p: "You can play the whole game with no account and without giving us any data. An account is only needed to appear on the leaderboard and to play duels against other people." },
        { h: "Who is responsible", p: "{titular}. For anything about your data, write to {contacto}." },
        { h: "What we keep if you create an account", p: "Your email and your password (encrypted, we never see it), the name you choose for the leaderboard, your hero and his level, the score of the games you send, the duels you play and your Elo. Nothing else: we don't ask for your real name, your age, your location or your contacts." },
        { h: "What we keep without an account", p: "Your game, your hero and your records stay on the device itself (browser storage) and never leave it. We also keep a few anonymous usage notes (that the game was opened, that a game was started or finished) with a random device identifier, to know whether the game makes sense to people. They can't be linked to you." },
        { h: "What for", p: "So that the leaderboard, the duels and your progress across devices work, and to improve the game. No advertising and no commercial profiling." },
        { h: "Who we share it with", p: "Nobody, except the provider that hosts the database (Supabase), which acts on our behalf and keeps the data in {paisDatos}. Your player name, your hero and your score are public inside the game: that's what a leaderboard is. Your email is never shown." },
        { h: "How long", p: "As long as you have the account. If you delete it, everything of yours is deleted right away. The anonymous usage notes are kept for a year at most." },
        { h: "Your rights", p: "You can see, correct or delete your data whenever you want. To delete everything there's a «Delete my account» button in Settings; you can also ask by writing to {contacto}. You have the right to complain to the data protection authority in your country." },
        { h: "Age", p: "The game isn't meant for children under {edad}. If that's you, ask a parent or guardian to create the account, or play without one." },
        { h: "Changes", p: "If this changes, you'll be told in the game. Last updated: {actualizado}." },
      ],
    },
    condiciones: {
      titulo: "Terms of use",
      secciones: [
        { h: "What this is", p: "Final War: Medieval is a turn-based strategy game. Using it is free. By playing you accept these terms." },
        { h: "Your account", p: "You're responsible for what's done with your account and for keeping your password safe. Choose a name that doesn't insult anyone, impersonate anyone or advertise anything; offensive names are changed or removed." },
        { h: "Fair play", p: "No cheating: modifying the game to get fake scores, automating games, abusing bugs or making extra accounts to inflate the leaderboard. If that happens the score is corrected and, if it's repeated, the account is closed." },
        { h: "Duels", p: "Duels are live and on the clock. If you leave or lose connection, the game may be counted as lost: that's only fair on the person waiting at the other end." },
        { h: "What's inside", p: "The game, its texts, drawings and music belong to their authors; the music has its own licence, credited in Settings → Credits. You can take screenshots and videos and post them wherever you like." },
        { h: "No warranties", p: "The game is offered as it is. It may have bugs, it may stop being available and you may lose progress (especially if you play without an account). We're not liable for damages arising from using it." },
        { h: "Changes and leaving", p: "These terms may change; you'll be told in the game. You can leave whenever you want by deleting your account from Settings." },
        { h: "Contact", p: "{contacto}. Last updated: {actualizado}." },
      ],
    },
  },
};
