// Tropas. Cada una es una "carta". Los stats son la base: el motor les suma
// tecnologías, plus de asentamiento, terreno y habilidades al calcularlos.
//
// etiquetas: sirven para que tecnologías y habilidades apunten a grupos
//   ("+1 defensa a todo lo que tenga armadura").
// alcance 0 = cuerpo a cuerpo (ataca al vecino y recibe contraataque).
// alcance N = dispara hasta N hexágonos sin contraataque.
// habilidades: lista de { tipo, ...parametros, condicion } (vacía en v1).
// bonos: ataque extra contra tropas con una etiqueta: { lanza: 15 } = +15 contra lanceros.
// defensaContra: defensa extra cuando el atacante lleva una etiqueta: { a_distancia: 10 } = +10 contra flechas y piedras.
window.FWM = window.FWM || {};
FWM.datosBase = FWM.datosBase || {};

FWM.datosBase.tropas = {
  campesino: {
    nombre: "Campesino",
    descripcion: "La tropa básica. Barata, débil, y la única que puede fundar pueblos. Sirve para reclamar terreno y para hacer bulto en las guarniciones.",
    etiquetas: ["a_pie", "cuerpo_a_cuerpo", "ligera"],
    stats: { ataque: 10, asedio: 10, defensa: 10, vida: 40, alcance: 0, movimiento: 2 },
    tipoDano: "normal",
    coste: { oro: 10 },
    mantenimiento: 1,
    requiere: [],
    mejoraA: ["lancero", "arquero", "espadachin"],
    puedeFundar: true,
    disparaSinMover: false,
    habilidades: [],
    icono: "campesino",
  },
  lancero: {
    nombre: "Lancero",
    descripcion: "La infantería sólida. Buena defensa: va delante y aguanta los golpes. Su muro de picas castiga a la caballería (+15), pero el espadachín se le cuela dentro.",
    etiquetas: ["a_pie", "cuerpo_a_cuerpo", "armadura", "lanza"],
    stats: { ataque: 20, asedio: 10, defensa: 30, vida: 60, alcance: 0, movimiento: 2 },
    bonos: { montada: 15 },
    tipoDano: "normal",
    coste: { oro: 20, madera: 2 },
    mantenimiento: 2,
    requiere: ["milicia"],
    mejoraA: ["caballero"],
    puedeFundar: false,
    disparaSinMover: false,
    habilidades: [],
    icono: "lancero",
  },
  arquero: {
    nombre: "Arquero",
    descripcion: "Dispara al hexágono vecino sin recibir contraataque (a dos desde una colina). Desgasta, no mata. Acuartelado, defiende desde dentro sin exponerse.",
    etiquetas: ["a_pie", "a_distancia", "ligera"],
    stats: { ataque: 20, asedio: 0, defensa: 10, vida: 40, alcance: 1, movimiento: 2 },
    tipoDano: "normal",
    coste: { oro: 20, madera: 2 },
    mantenimiento: 2,
    requiere: ["arqueria"],
    mejoraA: [],
    puedeFundar: false,
    disparaSinMover: false,
    habilidades: [],
    icono: "arquero",
  },
  espadachin: {
    nombre: "Espadachín",
    descripcion: "Infantería ágil y letal. Se cuela dentro de las lanzas (+15 contra lanceros) y su rodela para flechas (+10 de defensa contra tropas a distancia), pero la carga de la caballería lo arrolla.",
    etiquetas: ["a_pie", "cuerpo_a_cuerpo", "armadura", "espada"],
    stats: { ataque: 40, asedio: 10, defensa: 20, vida: 70, alcance: 0, movimiento: 2 },
    bonos: { lanza: 15 },
    defensaContra: { a_distancia: 10 },
    tipoDano: "normal",
    coste: { oro: 25, hierro: 2 },
    mantenimiento: 3,
    requiere: ["milicia"],
    mejoraA: ["caballero"],
    puedeFundar: false,
    disparaSinMover: false,
    habilidades: [],
    icono: "espadachin",
  },
  caballero: {
    nombre: "Caballero",
    descripcion: "La tropa de choque. Pega fuerte, mueve dos hexágonos y aguanta mucho. Su carga arrolla a los espadachines (+15), pero teme el muro de lanzas. Cara de reclutar y de mantener.",
    etiquetas: ["montada", "cuerpo_a_cuerpo", "armadura"],
    stats: { ataque: 50, asedio: 10, defensa: 20, vida: 80, alcance: 0, movimiento: 4 },
    bonos: { espada: 15 },
    tipoDano: "normal",
    coste: { oro: 30, hierro: 2 },
    mantenimiento: 4,
    requiere: ["caballeria"],
    mejoraA: ["caballeria_pesada"],
    puedeFundar: false,
    disparaSinMover: false,
    habilidades: [],
    icono: "caballero",
  },
  catapulta: {
    nombre: "Catapulta",
    descripcion: "La máquina de asedio. Rompe murallas desde dos hexágonos y de paso golpea a la guarnición, fuera del alcance de los arqueros; no puede moverse y disparar en el mismo turno y no se defiende: hay que escoltarla.",
    etiquetas: ["maquina", "a_distancia", "asedio"],
    stats: { ataque: 20, asedio: 25, defensa: 0, vida: 40, alcance: 2, movimiento: 2 },
    tipoDano: "normal",
    coste: { oro: 40, madera: 3, hierro: 2 },
    mantenimiento: 3,
    requiere: ["catapulta"],
    mejoraA: ["trabuco"],
    puedeFundar: false,
    disparaSinMover: true, // no puede moverse y disparar en el mismo turno
    habilidades: [],
    icono: "catapulta",
  },
  // ---- unidades que abre el héroe por nivel (nivelHeroe) ----
  monje: {
    nombre: "Monje",
    descripcion: "No pelea: cura. Al acabar tu turno, cura 10 a cada tropa tuya pegada a él. Débil y sin contraataque: guárdalo detrás de la línea.",
    etiquetas: ["a_pie", "cuerpo_a_cuerpo", "sanador"],
    stats: { ataque: 5, asedio: 0, defensa: 10, vida: 40, alcance: 0, movimiento: 2 },
    tipoDano: "normal",
    coste: { oro: 25 },
    mantenimiento: 2,
    requiere: [], nivelHeroe: 2,
    mejoraA: [], puedeFundar: false, habilidades: [],
    cura: 10,
    icono: "monje",
  },
  ballestero: {
    nombre: "Ballestero",
    descripcion: "Tiro tenso que atraviesa armaduras (+10 contra tropas con armadura). Como la catapulta, no puede moverse y disparar en el mismo turno.",
    etiquetas: ["a_pie", "a_distancia"],
    stats: { ataque: 25, asedio: 0, defensa: 10, vida: 40, alcance: 1, movimiento: 2 },
    bonos: { armadura: 10 },
    tipoDano: "normal",
    coste: { oro: 30 },
    mantenimiento: 2,
    requiere: [], nivelHeroe: 3,
    mejoraA: [], puedeFundar: false, disparaSinMover: true, habilidades: [],
    icono: "ballestero",
  },
  alabardero: {
    nombre: "Alabardero",
    descripcion: "Alabarda larga: +15 contra caballería, y el espadachín no encuentra hueco (no tiene bono contra él). Infantería de armadura, firme.",
    etiquetas: ["a_pie", "cuerpo_a_cuerpo", "armadura", "alabarda"],
    stats: { ataque: 25, asedio: 10, defensa: 30, vida: 65, alcance: 0, movimiento: 2 },
    bonos: { montada: 15 },
    tipoDano: "normal",
    coste: { oro: 30 },
    mantenimiento: 3,
    requiere: [], nivelHeroe: 4,
    mejoraA: ["infanteria_pesada"], puedeFundar: false, habilidades: [],
    icono: "alabardero",
  },
  infanteria_pesada: {
    nombre: "Infantería pesada",
    descripcion: "Pared de escudos. La tropa más dura a pie: aguanta lo que le echen (+10 de defensa contra tropas a distancia) y sus mazas abren brecha en las murallas. Lenta y cara de mantener.",
    etiquetas: ["a_pie", "cuerpo_a_cuerpo", "armadura", "pesada"],
    stats: { ataque: 30, asedio: 20, defensa: 45, vida: 95, alcance: 0, movimiento: 2 },
    defensaContra: { a_distancia: 10 },
    tipoDano: "normal",
    coste: { oro: 45 },
    mantenimiento: 4,
    requiere: [], nivelHeroe: 5,
    mejoraA: [], puedeFundar: false, habilidades: [],
    icono: "infanteria_pesada",
  },
  caballeria_pesada: {
    nombre: "Caballería pesada",
    descripcion: "La carga que decide la batalla. Arrolla a los espadachines (+15) y barre a arqueros y máquinas (+20). Solo el muro de lanzas la frena. Cuesta una fortuna cada turno.",
    etiquetas: ["montada", "cuerpo_a_cuerpo", "armadura", "pesada"],
    stats: { ataque: 60, asedio: 15, defensa: 30, vida: 100, alcance: 0, movimiento: 4 },
    bonos: { espada: 15, a_distancia: 20 },
    tipoDano: "normal",
    coste: { oro: 55 },
    mantenimiento: 5,
    requiere: [], nivelHeroe: 6,
    mejoraA: [], puedeFundar: false, habilidades: [],
    icono: "caballeria_pesada",
  },
  trabuco: {
    nombre: "Trabuco",
    descripcion: "El derribamurallas. Golpea a tres hexágonos, fuera del alcance de todo, y tira una muralla en dos disparos. No puede moverse y disparar en el mismo turno, y en campo abierto es un blanco.",
    etiquetas: ["maquina", "a_distancia", "asedio"],
    stats: { ataque: 30, asedio: 45, defensa: 0, vida: 45, alcance: 3, movimiento: 2 },
    tipoDano: "normal",
    coste: { oro: 70 },
    mantenimiento: 5,
    requiere: [], nivelHeroe: 7,
    mejoraA: [], puedeFundar: false, disparaSinMover: true, habilidades: [],
    icono: "trabuco",
  },
};

// Tabla de tipos de daño contra tipos de armadura. En v1 todo vale 1.
// Ejemplo futuro: { flecha: { placas: 0 } } → las flechas no atraviesan placas.
FWM.datosBase.tiposDano = {
  normal: { nombre: "Normal", contra: {} },
};
